import "./ditto.css";
import ListRow from "./components/list-row";
import Logo from "./components/logo";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/artikel", label2: "Artikel" },
    { href: "/newsletter", label2: "Newsletter" },
    { href: "/podcast", label: "Synapsensprung – Wo Technologie, Philosophie und Gesellschaft aufeinandertreffen", label2: "Podcast" },
    { href: "/kai-spriestersbach", label2: "Über mich" }
];
const Logo_data = [
    { alt: "", imgSrc: "/assets/cloned/images/2437c20ee55c.jpg" },
    { alt: "OMR Education", imgSrc: "/assets/cloned/images/84ada14c5261.jpg" },
    { alt: "Tagesspiegel Background", imgSrc: "/assets/cloned/images/0f81afb5e8fe.png" },
    { alt: "", imgSrc: "/assets/cloned/images/51b5f1bde536.png" },
    { alt: "heise online", imgSrc: "/assets/cloned/images/164c7759b69d.jpg" },
    { alt: "", imgSrc: "/assets/cloned/images/6fa51a7d95ba.jpg" },
    { alt: "ARD SEARCH & REACH", imgSrc: "/assets/cloned/images/76263a053cd4.png" },
    { alt: "SWR3", imgSrc: "/assets/cloned/images/dd8b9b1d5a10.jpg" }
];
const ListRow2_data = [
    { text: "Analyse Ihrer Geschäftsprozesse und -ziele" },
    { text: "Erkennung von Optimierungspotenzialen durch KI" },
    { text: "Entwicklung konkreter, auf Ihr Unternehmen zugeschnittener Use Cases" }
];
const ListRow2_data2 = [
    { text: "Von der Konzeption über die Entwicklung bis zur Implementierung" },
    { text: "Regelmäßige Abstimmungen und Anpassungen an Ihre Bedürfnisse" },
    { text: "Agile Entwicklungsmethoden für maximale Flexibilität und Effizienz" }
];
const ListRow2_data3 = [
    { text: "Bei Bedarf greife ich auf hochqualifizierte Entwickler:innen, Data Scientists und ML Ops Expert:innen zurück" },
    { text: "Kombination von technischer Expertise mit Branchenwissen" },
    { text: "Sicherstellung höchster Qualitätsstandards in der Entwicklung" }
];
const ListRow2_data4 = [
    { text: "Schulung Ihrer Mitarbeiter im Umgang mit der neuen KI-Lösung" },
    { text: "Unterstützung bei der Einführung und Anpassung bestehender Prozesse" },
    { text: "Langfristige Begleitung zur Optimierung und Weiterentwicklung" }
];
const ListRow3_data = [
    { text: "Analysephase", text2: ": Ich verstehe Ihr Unternehmen und identifiziere vielversprechende KI-Anwendungsfälle." },
    { text: "Konzeptionsphase", text2: ": Gemeinsam entwickeln wir ein detailliertes Konzept für Ihren KI-Prototyp." },
    { text: "Entwicklungsphase", text2: ": Ich koordiniere die Entwicklung und setze bei Bedarf erfahrene Spezialisten ein." },
    { text: "Testphase", text2: ": Der Prototyp wird unter realen Bedingungen rigoros getestet und optimiert." },
    { text: "Implementierungsphase", text2: ": Ich unterstütze Sie bei der nahtlosen Integration in Ihre Geschäftsprozesse." },
    { text: "Nachbetreuungsphase", text2: ": Ich biete kontinuierliche Unterstützung und Weiterentwicklung nach der Einführung." }
];
const ListRow3_data2 = [
    { text: "Persönliche Expertise", text2: ": Profitieren Sie von meinem fundierten Wissen in KI und Geschäftsprozessoptimierung." },
    { text: "Maßgeschneiderte Lösungen", text2: ": Jeder Prototyp wird speziell für Ihre individuellen Bedürfnisse entwickelt." },
    { text: "Praxisorientierung", text2: ": Ich fokussiere mich auf reale Geschäftsergebnisse, nicht auf Hype." },
    { text: "Zukunftssicherheit", text2: ": Bleiben Sie mit modernster KI-Technologie wettbewerbsfähig." },
    { text: "Ganzheitlicher Ansatz", text2: ": Von der Idee bis zur vollständigen Integration – ich bin an Ihrer Seite." },
    { text: "Flexibilität", text2: ": Als Einzelunternehmer biete ich Ihnen maximale Anpassungsfähigkeit und direkte Kommunikation." }
];
const ListRow_meta: string[][] = [
    ["n24", "style-5", "style-23"],
    ["n27", "style-6", "style-24"],
    ["n30", "style-7", "style-25"],
    ["n33", "style-8", "style-26"]
];
const Logo_meta: string[][] = [
    ["style-div-21", "style-div-44"],
    ["style-link-4", "style-image-2"],
    ["style-div-2", "style-div-65"],
    ["style-div-6", "style-p-9"],
    ["style-div", "style-div-45"],
    ["style-div-63", "style-footer-nav"],
    ["style-ul-17", "style-li-20"],
    ["style-link-5", "style-span-3"]
];
const ListRow2_meta: string[][] = [
    ["style-link-8"],
    ["style-span-6"],
    ["style-div-66"]
];
const ListRow2_meta2: string[][] = [
    ["style-p-176"],
    ["style-blockquote-15"],
    ["style-p-200"]
];
const ListRow2_meta3: string[][] = [
    ["style-p-202"],
    ["style-cite-3"],
    ["style-link-23"]
];
const ListRow2_meta4: string[][] = [
    ["style-blockquote-2"],
    ["style-p-185"],
    ["style-strong-135"]
];
const ListRow3_meta: string[][] = [
    ["style-p-213", "style-strong-130"],
    ["style-p-205", "style-blockquote-3"],
    ["style-p-207", "style-p-23"],
    ["style-blockquote-4", "style-p-152"],
    ["style-p-24", "style-hr-2"],
    ["style-heading-40", "style-p-25"]
];
const ListRow3_meta2: string[][] = [
    ["style-p-183", "style-hr-6"],
    ["style-heading-17", "style-p-86"],
    ["style-p-12", "style-p-17"],
    ["style-strong-2", "style-p-208"],
    ["style-heading", "style-p-28"],
    ["style-blockquote-13", "style-p-195"]
];
const ListRow3_styles = [
    { className: "mt-2" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" }
];
const ListRow3_styles2 = [
    { className: "mt-2" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" }
];

export default function Page() {
  return (
    <>
      <a className="box-content w-px h-px block absolute top-0 left-0 -m-px overflow-hidden text-primary underline [clip-path:inset(50%)] cursor-pointer" data-ditto-id="style-wp-skip-link" href="#wp--skip-link--target" id="wp-skip-link">
        Zum Inhalt springen
      </a>
      <div className="box-content block">
        <header className="box-content border-b border-solid border-b-clr-0 block [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif]">
          <div className="block">
            <div className="block relative px-5">
              <div className="flex max-w-280 mx-auto py-3.5 justify-between items-center gap-5">
                <div className="block leading-0">
                  <a className="box-content h-[51.7px] inline-block text-primary underline cursor-pointer" data-ditto-id="style-link" data-component="link" href="/" rel="home">
                    <img className="box-content w-30 h-13 inline max-w-full overflow-clip aspect-[auto_318/137]" data-ditto-id="style-image" data-component="image" alt="Afaik min" height="137" src="/assets/cloned/svg/d179f89faeae.svg" width="318" />
                  </a>
                </div>
                {" "}
                <div className="flex justify-end items-center">
                  <nav className="box-content flex relative flex-wrap justify-end items-center gap-5 text-[1.0625rem] font-medium leading-[1.8125rem] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:leading-[1.75rem]" data-component="nav" aria-label="Haupnav">
                    <button className="hidden min-w-0 align-middle leading-[1.3125rem] tracking-[normal] text-center cursor-pointer max-md:flex max-md:leading-[1.1875rem]" aria-haspopup="dialog" aria-label="Menü öffnen">
                      <svg className="box-content w-6 h-6 block overflow-hidden pointer-events-none" aria-hidden="true" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" focusable="false" fill="currentColor">
                        <path d="M4 7.5h16v1.5H4z" />
                        <path d="M4 15h16v1.5H4z" />
                      </svg>
                    </button>
                    {" "}
                    <div className="box-content block relative gap-5 max-md:hidden" data-ditto-id="style-modal-1" id="modal-1">
                      <div className="box-content block gap-5">
                        <div className="box-content block relative gap-5">
                          <div className="box-content flex flex-wrap justify-end items-center gap-5" id="modal-1-content">
                            <ul className="flex relative flex-wrap justify-end items-center gap-5 [list-style-type:none] list-outside">
                              <li className="box-content flex relative items-center" data-ditto-id="style-li">
                                <a className="box-content h-[1.8375rem] block z-1 cursor-pointer md:max-lg:h-[1.775rem]" data-ditto-id="style-link-2" data-component="link" href="/ki-beratung" title="Meine KI-Beratungsleistungen im Detail">
                                  <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-span">
                                    Beratung
                                  </span>
                                </a>
                                <button className="w-[0.65rem] h-[0.65rem] block ml-[4.3px] self-center [font-family:Arial] font-normal leading-0 tracking-[normal] text-center cursor-pointer md:max-lg:w-2.5 md:max-lg:h-2.5 md:max-lg:ml-1" data-ditto-id="style-untermen-von-beratung" data-component="button" aria-expanded="false" aria-label="Untermenü von Beratung">
                                  <svg className="box-content w-auto h-2.5 inline-block mt-[1.3px] overflow-hidden" data-ditto-id="style-icon" data-component="icon" aria-hidden="true" fill="none" height="12" viewBox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg" focusable="false">
                                    <path d="M1.50002 4L6.00002 8L10.5 4" strokeWidth="1.5" />
                                  </svg>
                                </button>
                              </li>
                              {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                              <li className="box-content flex relative items-center" data-ditto-id="style-li-2">
                                <a className="box-content h-[1.8375rem] block z-1 cursor-pointer md:max-lg:h-[1.775rem]" data-ditto-id="style-link-3" data-component="link" href="#">
                                  <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-span-2">
                                    Bücher
                                  </span>
                                </a>
                                <button className="w-[0.65rem] h-[0.65rem] block ml-[4.3px] self-center [font-family:Arial] font-normal leading-0 tracking-[normal] text-center cursor-pointer md:max-lg:w-2.5 md:max-lg:h-2.5 md:max-lg:ml-1" data-ditto-id="style-untermen-von-b-cher" data-component="button" aria-expanded="false" aria-label="Untermenü von Bücher">
                                  <svg className="box-content w-auto h-2.5 inline-block mt-[1.3px] overflow-hidden" data-ditto-id="style-icon-2" data-component="icon" aria-hidden="true" fill="none" height="12" viewBox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg" focusable="false">
                                    <path d="M1.50002 4L6.00002 8L10.5 4" strokeWidth="1.5" />
                                  </svg>
                                </button>
                              </li>
                            </ul>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </nav>
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </header>
        {" "}
        <div className="box-content h-[0.1875rem] block fixed top-0 inset-x-0 z-9999 mt-5 pointer-events-none" aria-hidden="true" />
        {" "}
        <main className="block relative mt-[4.8rem] px-5 max-md:mt-10 md:max-lg:mt-[2.875rem] 2xl:mt-20" id="wp--skip-link--target">
          <article className="block relative max-w-180 mx-auto px-10 max-md:px-5 md:max-lg:px-[30.7px]">
            <h1 className="block max-w-230 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[4.8125rem] font-extrabold leading-[4.8125rem] tracking-[-4.45px] [word-break:break-word] text-pretty max-md:text-[2.8125rem] max-md:leading-[2.8125rem] max-md:tracking-[-2.25px] md:max-lg:text-[3.125rem] md:max-lg:leading-[3.125rem] md:max-lg:tracking-[-2.9px]" data-component="heading">
              KI-Prototyp Service: Begleitung von der Idee zur praktischen KI-Anwendung in Ihrem Unternehmen
            </h1>
            {" "}
            <div className="box-content flow-root max-w-180 mt-14 [font-family:Georgia,_'Times_New_Roman',_Times,_serif] max-md:mt-8 md:max-lg:mt-[2.4rem]" data-ditto-id="style-figure">
              <blockquote className="border-l-[3px] border-solid border-l-foreground block max-w-180 mb-9 py-[0.15rem] pl-[1.35rem] font-light leading-[2rem] [overflow-wrap:break-word] text-pretty max-md:leading-[1.6875rem] md:max-lg:leading-[1.875rem]">
                <figure className="box-content w-75 h-[18.7375rem] table float-right ml-[2.7rem] max-md:w-[14.625rem] max-md:h-[14.6125rem] max-md:ml-[36.5px] md:max-lg:ml-10" data-ditto-id="style-div-62">
                  <img className="w-75 h-75 inline max-w-full overflow-clip aspect-[auto_2048/2047] align-bottom max-md:w-58.5 max-md:h-58.5" data-ditto-id="style-div-14" data-component="image" alt="Kai Spriestersbach" height="2047" sizes="(max-width: 2048px) 100vw, 2048px" src="/assets/cloned/images/8081749df70d.jpg" srcSet="/assets/cloned/images/8081749df70d.jpg 2048w, /assets/cloned/images/f69d1d89bca7.jpg 1024w, /assets/cloned/images/77a49ba50dcb.jpg 768w" width="2048" />
                </figure>
                {" "}
                <p className="box-content block mt-3.5 text-[1.75rem] leading-[2.5rem] max-md:text-[1.375rem] max-md:leading-[1.9375rem] md:max-lg:text-2xl md:max-lg:leading-[2.125rem] 2xl:text-[1.8125rem] 2xl:leading-[2.625rem]" data-ditto-id="style-heading-13">
                  In meiner langjährigen Erfahrung als KI-Experte und Unternehmer habe ich immer wieder festgestellt: Der wahre Wert von KI liegt nicht in der Technologie selbst, sondern in ihrer praktischen Anwendung zur Lösung realer Geschäftsprobleme. Mit meinem KI-Prototyp Service begleite ich Sie persönlich auf dem Weg von der ersten Idee bis zur erfolgreichen Implementierung einer maßgeschneiderten KI-Lösung.
                </p>
                {" "}
                <p className="box-content block mt-3.5 text-[1.75rem] leading-[2.5rem] max-md:text-[1.375rem] max-md:leading-[1.9375rem] md:max-lg:text-2xl md:max-lg:leading-[2.125rem] 2xl:text-[1.8125rem] 2xl:leading-[2.625rem]" data-ditto-id="style-p">
                  Dabei nutze ich mein tiefgreifendes Verständnis sowohl der technischen als auch der geschäftlichen Aspekte, um für Sie einen KI-Prototypen zu entwickeln, der echten Mehrwert schafft. Bei Bedarf greife ich auf ein Netzwerk hochqualifizierter Spezialisten zurück, um sicherzustellen, dass Ihr Projekt von den besten Köpfen profitiert.
                </p>
                {" "}
                <p className="box-content block mt-3.5 text-[1.75rem] leading-[2.5rem] max-md:text-[1.375rem] max-md:leading-[1.9375rem] md:max-lg:text-2xl md:max-lg:leading-[2.125rem] 2xl:text-[1.8125rem] 2xl:leading-[2.625rem]" data-ditto-id="style-form-2">
                  <strong className="box-content inline font-normal" data-ditto-id="style-label">
                    Mein Ziel ist es, Ihnen nicht nur eine funktionierende KI-Lösung zu liefern, sondern Sie auch zu befähigen, die Möglichkeiten der KI in Ihrem Unternehmen voll auszuschöpfen. Lassen Sie uns gemeinsam die Zukunft Ihres Unternehmens mit KI gestalten – praxisnah, effizient und mit messbarem Erfolg.
                  </strong>
                </p>
                {" "}
                <cite className="box-content block mt-3.5 text-[0.9375rem] leading-[1.375rem]">
                  <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-wp-block-search-input-2" data-component="link" href="/kai-spriestersbach">
                    Kai Spriestersbach
                  </a>
                  , Inhaber
                </cite>
              </blockquote>
              {" "}
              <h2 className="box-content block max-w-180 mt-[36.3px] mb-[0.5375rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[1.0625rem] [font-weight:750] leading-[1.25rem] tracking-[-0.6px] text-pretty max-md:mt-[2.1125rem] max-md:mb-2 max-md:text-base max-md:leading-[1.125rem] max-md:tracking-[-0.56px] md:max-lg:mt-[35.1px] md:max-lg:mb-[0.525rem] md:max-lg:leading-[1.1875rem] md:max-lg:tracking-[-0.59px]" data-ditto-id="style-suchen" data-component="heading">
                <br className="box-content inline" data-ditto-id="style-footer" />
                Bekannt aus
              </h2>
              {" "}
              <figure className="box-content flex max-w-180 my-[3.6rem] flex-wrap gap-3 max-md:my-8 md:max-lg:my-[2.4rem]" data-ditto-id="style-div-64">
                {Logo_data.map((d, i) => <Logo key={i} d={d} />)}
                {" "}
              </figure>
              {" "}
              <hr className="box-content w-24 h-0 border-b border-solid border-b-clr-1 block max-w-24 my-16 mx-auto overflow-hidden text-clr-0 max-md:my-10 md:max-lg:my-[2.875rem]" data-ditto-id="style-li-21" />
              {" "}
              <div className="box-content h-10 block clear-both max-w-180 mt-5" data-ditto-id="style-link-6" aria-hidden="true" />
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-span-4" data-component="heading">
                Entdecken Sie das volle Potenzial von KI für Ihr Geschäft
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-footer-nav-2">
                In der sich schnell entwickelnden Welt der künstlichen Intelligenz ist es entscheidend, nicht nur über KI zu sprechen, sondern sie auch praktisch und gewinnbringend einzusetzen. Mein KI-Prototyp Service bietet Ihnen genau das: Eine maßgeschneiderte Lösung, die Ihre Geschäftsideen mit modernster KI-Technologie in die Realität umsetzt.
              </p>
              {" "}
              <div className="flex max-w-180 my-16 gap-10 max-md:my-9 max-lg:flex-wrap max-md:gap-6 md:max-lg:my-[2.875rem] md:max-lg:gap-[30.7px]" data-ditto-id="style-ul-3">
                <div className="box-content block min-w-0 flex-1 [word-break:break-word] [overflow-wrap:break-word] max-lg:basis-full" data-ditto-id="style-li-25">
                  <p className="box-content block leading-[2.3125rem] text-pretty max-md:leading-[1.9375rem] md:max-lg:leading-[2.125rem]" data-ditto-id="style-link-7">
                    <strong className="box-content inline font-bold" data-ditto-id="style-span-5">
                      Identifizierung wertschöpfender KI-Anwendungsfälle
                    </strong>
                  </p>
                  {" "}
                  <ul className="block mt-5 pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-li-23">
                    {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                  </ul>
                  {" "}
                </div>
                {" "}
                <div className="box-content block min-w-0 flex-1 [word-break:break-word] [overflow-wrap:break-word] max-lg:basis-full" data-ditto-id="style-div-3">
                  <p className="box-content block leading-[2.3125rem] text-pretty max-md:leading-[1.9375rem] md:max-lg:leading-[2.125rem]" data-ditto-id="style-p-10">
                    <strong className="box-content inline font-bold" data-ditto-id="style-p-199">
                      Ganzheitliche Begleitung durch den Entwicklungsprozess
                    </strong>
                  </p>
                  {" "}
                  <ul className="block mt-5 pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-link-9">
                    {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} />)}
                  </ul>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="flex max-w-180 my-16 gap-10 max-md:my-9 max-lg:flex-wrap max-md:gap-6 md:max-lg:my-[2.875rem] md:max-lg:gap-[30.7px]" data-ditto-id="style-ftnref1">
                <div className="box-content block min-w-0 flex-1 [word-break:break-word] [overflow-wrap:break-word] max-lg:basis-full" data-ditto-id="style-p-201">
                  <p className="box-content block leading-[2.3125rem] text-pretty max-md:leading-[1.9375rem] md:max-lg:leading-[2.125rem]" data-ditto-id="style-p-181">
                    <strong className="box-content inline font-bold" data-ditto-id="style-ftnref2">
                      <strong className="box-content inline font-black" data-ditto-id="style-p-151">
                        <strong className="box-content inline" data-ditto-id="style-em-8">
                          Zugang zu einem Netzwerk erfahrener Spezialisten
                        </strong>
                      </strong>
                    </strong>
                  </p>
                  {" "}
                  <ul className="block mt-5 pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-p-204">
                    {ListRow2_data3.map((d, i) => <ListRow2 key={i} d={d} />)}
                  </ul>
                  {" "}
                </div>
                {" "}
                <div className="box-content block min-w-0 flex-1 [word-break:break-word] [overflow-wrap:break-word] max-lg:basis-full" data-ditto-id="style-p-206">
                  <p className="box-content block leading-[2.3125rem] text-pretty max-md:leading-[1.9375rem] md:max-lg:leading-[2.125rem]" data-ditto-id="style-p-203">
                    <strong className="box-content inline font-bold" data-ditto-id="style-strong">
                      <strong className="box-content inline font-black" data-ditto-id="style-hr">
                        <strong className="box-content inline" data-ditto-id="style-heading-48">
                          Nahtlose Integration in Ihr Unternehmen
                        </strong>
                      </strong>
                    </strong>
                  </p>
                  {" "}
                  <ul className="block mt-5 pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-p-11">
                    {ListRow2_data4.map((d, i) => <ListRow2 key={i} d={d} />)}
                  </ul>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="box-content h-7.5 block clear-both max-w-180 mt-5" data-ditto-id="style-p-186" aria-hidden="true" />
              {" "}
              <h3 className="box-content block max-w-180 mt-[3.3625rem] mb-[0.8rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[1.625rem] [font-weight:750] leading-[1.8125rem] tracking-[-0.9px] text-pretty max-lg:mt-[48.7px] max-lg:mb-[0.725rem] max-lg:text-[1.4375rem] max-lg:leading-[1.625rem] max-lg:tracking-[-0.81px] 2xl:mt-[65.5px] 2xl:mb-[0.975rem] 2xl:text-[1.9375rem] 2xl:leading-[2.25rem] 2xl:tracking-[-1.09px]" data-ditto-id="style-p-187" data-component="heading">
                Mein Prozess
              </h3>
              {" "}
              <ol className="block max-w-180 mt-5 pl-[30.5px] text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] [list-style-type:decimal] list-outside max-md:pl-[26.1px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:pl-[1.6875rem] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:pl-[31.3px] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-128">
                {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
              </ol>
              {" "}
              <div className="box-content h-20 block clear-both max-w-180 mt-5" data-ditto-id="style-p-26" aria-hidden="true" />
              {" "}
              <h3 className="box-content block max-w-180 mt-[3.3625rem] mb-[0.8rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[1.625rem] [font-weight:750] leading-[1.8125rem] tracking-[-0.9px] text-pretty max-lg:mt-[48.7px] max-lg:mb-[0.725rem] max-lg:text-[1.4375rem] max-lg:leading-[1.625rem] max-lg:tracking-[-0.81px] 2xl:mt-[65.5px] 2xl:mb-[0.975rem] 2xl:text-[1.9375rem] 2xl:leading-[2.25rem] 2xl:tracking-[-1.09px]" data-ditto-id="style-p-16" data-component="heading">
                Warum Sie sich für meinen Prototyp Service entscheiden sollten
              </h3>
              {" "}
              <figure className="box-content w-[177.3px] h-[36.7px] table float-right my-[3.6rem] ml-[2.7rem] max-md:w-[152.3px] max-md:h-[1.9375rem] max-md:my-8 max-md:ml-[36.5px] md:max-lg:w-[10.3375rem] md:max-lg:h-[2.125rem] md:max-lg:my-[2.4rem] md:max-lg:ml-10" data-ditto-id="style-blockquote-6">
                <img className="w-[11.0625rem] h-[2.3125rem] inline max-w-full overflow-clip align-bottom max-md:w-38 max-md:h-[1.9375rem] md:max-lg:w-[10.3125rem] md:max-lg:h-8.5" data-ditto-id="style-p-27" data-component="image" alt="Kai Spriestersbach" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" />
              </figure>
              {" "}
              <ul className="block max-w-180 mt-5 pl-[30.5px] text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] [list-style-type:disc] list-outside max-md:pl-[26.1px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:pl-[1.6875rem] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:pl-[31.3px] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-136">
                {ListRow3_data2.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles2[i]} />)}
              </ul>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-129">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-87">
                  Machen Sie den ersten Schritt in Richtung KI-gestützte Innovation. Kontaktieren Sie mich noch heute für ein unverbindliches Beratungsgespräch und entdecken Sie, wie wir gemeinsam Ihre Geschäftsideen mit KI zum Leben erwecken können.
                </strong>
              </p>
              {" "}
            </div>
          </article>
          {" "}
        </main>
        {" "}
        <footer className="box-content border-t border-solid border-t-clr-0 block mt-24 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] max-md:mt-14 md:max-lg:mt-[3.8375rem]" data-ditto-id="style-p-18">
          <div className="block relative pt-16 pb-[2.4rem] px-5 max-md:pt-9 max-lg:pb-6 md:max-lg:pt-[2.4rem] 2xl:pb-10" data-ditto-id="style-p-177">
            <div className="block max-w-280 mx-auto" data-ditto-id="style-strong-134">
              <div className="block leading-0" data-ditto-id="style-hr-7">
                <a className="box-content h-[51.7px] inline-block text-primary underline cursor-pointer" data-ditto-id="style-heading-49" data-component="link" href="/" rel="home">
                  <img className="box-content w-30 h-13 inline max-w-full overflow-clip aspect-[auto_318/137]" data-ditto-id="style-p-153" data-component="image" alt="Afaik min" height="137" src="/assets/cloned/svg/d179f89faeae.svg" width="318" />
                </a>
              </div>
              {" "}
              <div className="flex mt-5 flex-wrap justify-between items-start gap-5" data-ditto-id="style-ol-3">
                <div className="flex gap-[2.4rem] max-lg:flex-wrap max-lg:gap-6 2xl:gap-10" data-ditto-id="style-p-196">
                  <div className="box-content block min-w-0 basis-full [word-break:break-word] [overflow-wrap:break-word] max-lg:grow" data-ditto-id="style-em-9">
                    <p className="block text-muted-foreground text-[0.9375rem] leading-[1.5625rem] text-pretty" data-ditto-id="style-ul-18">
                      As Far As I Know
                    </p>
                  </div>
                  {" "}
                  <div className="box-content h-[25.3px] block min-w-0 flex-1 [word-break:break-word] [overflow-wrap:break-word] max-lg:h-5 max-lg:basis-full" data-ditto-id="style-p-19">
                    <div className="box-content w-0 h-5 block clear-both" data-ditto-id="style-ul-8" aria-hidden="true" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="flex flex-wrap justify-between items-start gap-36 max-md:gap-20 md:max-lg:gap-[5.7625rem]" data-ditto-id="style-li-4">
                  <nav className="box-content flex relative flex-col flex-wrap items-start gap-5 text-[0.9375rem] font-medium leading-[1.5625rem]" data-ditto-id="style-em-7" data-component="nav" aria-label="Footer Nav">
                    <ul className="flex relative flex-col flex-wrap items-start grow gap-5 [list-style-type:none] list-outside" data-ditto-id="style-p-194">
                      <li className="box-content flex relative items-center" data-ditto-id="style-strong-133">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-p-184" data-component="link" href="/newsletter">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-hr-3">
                            Newsletter abonnieren
                          </span>
                        </a>
                      </li>
                      <li className="box-content flex relative items-center" data-ditto-id="style-heading-47">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-p-154" data-component="link" href="/podcast">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-em-10">
                            Podcast Synapsensprung
                          </span>
                        </a>
                      </li>
                    </ul>
                  </nav>
                  {" "}
                  <nav className="box-content flex relative flex-col flex-wrap items-start gap-5 text-[0.9375rem] font-medium leading-[1.5625rem]" data-ditto-id="style-em-12" data-component="nav" aria-label="Footer Nav 2">
                    <ul className="flex relative flex-col flex-wrap items-start grow gap-5 [list-style-type:none] list-outside" data-ditto-id="style-p-209">
                      <li className="box-content flex relative items-center" data-ditto-id="style-heading-2">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-p-178" data-component="link" href="/datenschutz">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-p-20">
                            Datenschutz
                          </span>
                        </a>
                      </li>
                      <li className="box-content flex relative items-center" data-ditto-id="style-ul-2">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-p-88" data-component="link" href="/impressum">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-p-197">
                            Impressum
                          </span>
                        </a>
                      </li>
                    </ul>
                  </nav>
                </div>
                {" "}
              </div>
              {" "}
              <div className="box-content h-24 block clear-both mt-5 max-md:h-14 md:max-lg:h-[3.8375rem]" data-ditto-id="style-em-11" aria-hidden="true" />
              {" "}
              <div className="flex mt-5 flex-wrap justify-between items-center gap-2" data-ditto-id="style-p-21">
                <p className="box-content block text-[0.9375rem] leading-[1.5625rem] text-pretty" data-ditto-id="style-strong-74">
                  © Kai Spriestersbach
                </p>
                {" "}
                <p className="box-content block text-[0.9375rem] leading-[1.5625rem] text-pretty" data-ditto-id="style-p-22">
                  {"Gehosted von "}
                  <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-p-29" data-component="link" href="https://www.cms-admins.de/" rel="noopener" target="_blank">
                    CMS ADMINS
                  </a>
                </p>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
      </div>
      {" "}
    </>
  );
}
