import "./ditto.css";
import ListRow from "./components/list-row";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { id: "mega-menu-item-5623", href: "https://lexfridman.com/contact/", label: "Contact Lex" },
    { id: "mega-menu-item-3697", href: "https://twitter.com/lexfridman", label: "X / Twitter" },
    { id: "mega-menu-item-3698", href: "https://www.youtube.com/lexfridman", label: "YouTube" }
];
const ListRow_meta: string[][] = [
    ["n26", "style-id-11"],
    ["n28", "style-span"],
    ["n30", "style-span-2"]
];
const ListRow_styles = [
    { className: "max-md:hidden", className2: "whitespace-nowrap max-md:hidden" },
    { className: "max-md:hidden", className2: "whitespace-nowrap max-md:hidden" },
    {  }
];

export default function Page() {
  return (
    <>
      <div className="box-content block max-w-240 mx-40 overflow-hidden bg-background max-lg:px-6 max-md:max-w-none max-lg:mx-0 max-md:[overflow-x:initial] max-md:[overflow-y:initial] 2xl:mx-120" id="page">
        <a className="box-content w-px h-px block absolute -m-px overflow-hidden text-primary underline [clip-path:inset(50%)] cursor-pointer" data-ditto-id="style-link" data-component="link" href="#content">
          Skip to content
        </a>
        {" "}
        <header className="box-content block pt-6" id="masthead">
          <hgroup className="box-content block">
            {" "}
            <h2 className="box-content w-[20.5625rem] h-6 block absolute clear-both text-color-003 text-[0.8125rem] leading-6 text-left [clip-path:inset(50%)] max-md:text-center" data-component="heading">
              Research Scientist at MIT. Host of Lex Fridman Podcast.
            </h2>
            {" "}
          </hgroup>
          {" "}
          <nav className="box-content block mt-6 text-center" data-component="nav" id="site-navigation">
            <button className="border border-solid border-clr-0 hidden py-1.5 px-2.5 rounded-[3px] text-clr-1 text-[0.6875rem] leading-[1rem] bg-clr-2 bg-repeat-x shadow-[var(--clr-3)_0px_1px_2px_0px] cursor-pointer" style={{ backgroundImage: "linear-gradient(var(--clr-4), var(--clr-2))" }} aria-controls="mega-menu-primary" aria-expanded="false">
              Menu
            </button>
            {" "}
            <div className="block relative clear-both text-muted-foreground leading-[1.5rem] text-left [overflow-wrap:break-word] bg-surface-2 max-md:bg-[initial]" id="mega-menu-wrap-primary">
              <div className="box-content hidden max-md:h-10 max-md:flex max-md:z-1 max-md:rounded-xs max-md:leading-10 max-md:whitespace-nowrap max-md:text-nowrap max-md:bg-color-001 max-md:cursor-pointer">
                <div className="box-content block max-md:flex max-md:justify-start max-md:flex-1">
                  <div className="box-content w-0 block max-md:h-10 max-md:flex max-md:ml-1.5 max-md:self-center max-md:shrink-0" id="mega-toggle-block-1" />
                  <div className="box-content block max-md:w-21.5 max-md:flex max-md:ml-1.5 max-md:self-center max-md:shrink-0" id="mega-toggle-block-2">
                    <span className="box-content inline max-md:block">
                      <a className="box-content inline text-background text-[0.9375rem] leading-[1.625rem] cursor-pointer max-md:leading-[inherit] max-md:[cursor:inherit]" href="/">
                        Lex Fridman
                      </a>
                    </span>
                  </div>
                </div>
                <div className="box-content block max-md:flex max-md:justify-center max-md:basis-1/3" />
                <div className="box-content block max-md:flex max-md:justify-end max-md:flex-1">
                  <div className="box-content block pl-0.5 text-xl leading-8.5 cursor-pointer max-md:w-[4.4375rem] max-md:flex max-md:mx-1.5 max-md:self-center max-md:shrink-0 max-md:leading-[inherit] max-md:[cursor:inherit] after:content-[''] after:ml-[0.3125rem] after:text-background after:text-2xl after:leading-[2.5625rem] after:text-left max-md:after:block max-md:after:w-6 max-md:after:h-10 max-md:after:leading-10" id="mega-toggle-block-3">
                    <button className="block relative text-background text-sm leading-[1.5rem] max-md:whitespace-normal" aria-controls="mega-menu-primary" aria-expanded="false" aria-haspopup="true">
                      <span className="box-content inline">
                        MENU
                      </span>
                      <span className="box-content hidden">
                        MENU
                      </span>
                    </button>
                  </div>
                </div>
              </div>
              <ul className="block relative [list-style-type:none] list-outside max-md:hidden" id="mega-menu-primary">
                <li className="inline-block relative mr-2.5 align-middle" id="mega-menu-item-3323">
                  <a className="block relative px-2.5 text-muted leading-10 cursor-pointer whitespace-nowrap" data-ditto-id="style-link-2" data-component="link" href="/">
                    Lex Fridman
                  </a>
                </li>
                <li className="inline-block relative mr-2.5 align-middle" id="mega-menu-item-3695">
                  <a className="block relative px-2.5 text-muted leading-10 cursor-pointer" data-ditto-id="style-link-3" data-component="link" href="https://lexfridman.com/podcast">
                    Podcast
                  </a>
                </li>
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} styles={ListRow_styles[i]} />)}
              </ul>
            </div>
            {" "}
          </nav>
          {" "}
        </header>
        {" "}
        <div className="box-content block max-w-175 mx-32.5 text-base leading-4 max-md:mx-0 md:max-lg:mx-2.5 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-main" id="main">
          <div className="box-content block float-left max-md:[float:initial]" id="primary">
            <div className="box-content block" id="content" role="main">
              <article className="box-content block mb-18 pb-6 [overflow-wrap:break-word]" id="post-3952">
                <header className="box-content block mb-6">
                  <h1 className="box-content w-240 block clear-both min-w-240 -mx-32.5 pt-5 [font-family:Ubuntu,_sans-serif] text-[2.125rem] leading-[2.5625rem] text-center max-md:w-[20.4375rem] max-lg:min-w-0 max-lg:mx-0 md:max-lg:w-175" data-component="heading">
                    MIT Advanced Vehicle Technology Study
                  </h1>
                  {" "}
                </header>
                {" "}
                <div className="box-content block leading-[1.6875rem]">
                  <p className="box-content block mb-6">
                    It may be several decades before sensors, algorithms, and data collection are sufficiently developed to “solve” the full driving task. Until that time, human beings will remain an integral part of the driving task, monitoring the AI system as it performs anywhere from just over 0% to just under 100% of the driving. We launched the MIT Advanced Vehicle Technology (MIT-AVT) study to understand, through large-scale real-world driving data collection and large-scale deep learning based parsing of that data, how human-AI interaction in driving can be safe and enjoyable. The emphasis is on objective, data-driven analysis.
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-span-1653">
                    <strong className="box-content inline font-bold" data-ditto-id="style-mep-0">
                      {"Update: "}
                    </strong>
                    {"Please note that the initial version of this paper as it went through the review process referred to this study as the MIT "}
                    <em className="box-content inline italic" data-ditto-id="style-div-500">
                      Autonomous
                    </em>
                    {" Vehicle Technology Study. It was renamed to MIT "}
                    <em className="box-content inline italic">
                      Advanced
                    </em>
                    {" Vehicle Technology Study as the scope of our data collection and research efforts broadened to include vehicle technology beyond vehicle autonomy."}
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-div">
                    The following video introduces the study:
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-div-586">
                    <iframe className="box-content w-175 h-98.5 inline max-w-full mb-6 overflow-clip [background-size:100%_100%] bg-no-repeat max-md:w-[20.4375rem] max-lg:[background-size:initial] max-lg:[background-repeat:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/dc01df469357.jpg\")" }} data-ditto-id="style-div-2" height="394" title="MIT Advanced Vehicle Technology Study (MIT-AVT)" width="700" />
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-play">
                    {"See "}
                    <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-div-505" data-component="link" href="https://arxiv.org/abs/1711.06976">
                      arXiv paper
                    </a>
                    {" or the "}
                    <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-span-1188" data-component="link" href="https://ieeexplore.ieee.org/document/8751968">
                      IEEE Access published version
                    </a>
                    {" for details on methods of data collection, processing, and study design. If you find this work useful in your own research. See its reference on "}
                    <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-div-506" data-component="link" href={"https://scholar.google.com/scholar?hl=en&as_sdt=0%2C22&q=%22MIT+Advanced+Vehicle+Technology+Study%3A+Large-Scale+Naturalistic+Driving+Study+of+Driver+Behavior+and+Interaction+With+Automation%22&btnG="}>
                      Google Scholar
                    </a>
                    .
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-time-slider">
                    <strong className="box-content inline font-bold" data-ditto-id="style-span-1652">
                      Contact:
                    </strong>
                    {" This study (and data collection) is ongoing. If you have interest in this study please visit the "}
                    <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-span-1189" data-component="link" href="https://agelab.mit.edu/avt">
                      current study website
                    </a>
                    {" and contact "}
                    <span className="box-content inline" data-ditto-id="style-span-1645" id="eeb-426222-391535">
                      avt-questions@mit.edu
                    </span>
                    {" if you have any questions. "}
                    <em className="box-content inline italic" data-ditto-id="style-span-3">
                      Please note that this is not a way to get in contact with me (Lex). I am no longer actively involved with this work.
                    </em>
                  </p>
                  {" "}
                  <p className="box-content block mb-6">
                    We have instrumented Tesla Model S and Model X vehicles, Volvo S90 vehicles, Range Rover Evoque, and Cadillac CT6 vehicles for both long-term (over a year per driver) and medium term (one month per driver) naturalistic driving data collection. Furthermore, we are continually developing new methods for analysis of the massive-scale dataset collected from the instrumented vehicle fleet. The recorded data streams include IMU, GPS, CAN messages, and high-definition video streams of the driver face, the driver cabin, the forward roadway, and the instrument cluster (on select vehicles). The study is on-going and growing:
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-span-1646">
                    <img className="box-content w-240 h-[35.1875rem] inline min-w-240 max-w-full -mx-32.5 rounded-[3px] overflow-clip aspect-[auto_1842/1080] max-md:w-[20.4375rem] max-md:h-48 max-lg:min-w-0 max-lg:mx-0 md:max-lg:w-175 md:max-lg:h-102.5" data-ditto-id="style-div-3" data-component="image" alt="" height="1080" sizes="(max-width: 1842px) 100vw, 1842px" src="/assets/cloned/images/1660656af618.png" srcSet="/assets/cloned/images/1660656af618.png 1842w, /assets/cloned/images/1bc2d1b0c155.png 300w, /assets/cloned/images/c68a6d24dec7.png 768w, /assets/cloned/images/ca8a61eb50f9.png 1024w, /assets/cloned/images/677840e6b54d.png 624w" width="1842" />
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-mute">
                    The backbone of a successful naturalistic driving study is the hardware and low-level software that performs the data collection. In the MIT-AVT study, that role is served by a system named RIDER (Real-time Intelligent Driving Environment Recording system). The following video describes the system:
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-volume-slider">
                    <iframe className="box-content w-175 h-98.5 inline max-w-full mb-6 overflow-clip [background-size:100%_100%] bg-no-repeat max-md:w-[20.4375rem] max-lg:[background-size:initial] max-lg:[background-repeat:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/392e953dbaf4.jpg\")" }} data-ditto-id="style-span-4" height="394" title="MIT-AVT: Data Collection Device (for Large-Scale Semi-Autonomous Driving)" width="700" />
                  </p>
                  {" "}
                  <p className="box-content block mb-6">
                    Building on the robust, reliable, and flexible hardware architecture of RIDER is a vast software framework that handles the recording of raw sensory data and takes that data through many steps across thousands of GPU-enabled compute cores to the extracted knowledge and insights about human behavior in the context of autonomous vehicle technologies. The following figure of the pipeline shows the journey from raw timestamped sensor data to actionable knowledge. The high-level steps are (1) data cleaning and synchronization, (2) automated or semi-automated data annotation, context interpretation, and knowledge extraction, and (3) aggregate analysis and visualization.
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-div-587">
                    <img className="box-content w-240 h-[50.9375rem] inline min-w-240 max-w-full -mx-32.5 rounded-[3px] overflow-clip max-md:w-[20.4375rem] max-md:h-69.5 max-lg:min-w-0 max-lg:mx-0 md:max-lg:w-175 md:max-lg:h-148.5" data-ditto-id="style-p-4" data-component="image" src="/assets/cloned/images/d719fc5893c4.png" />
                  </p>
                  {" "}
                  <h2 className="box-content block clear-both my-6 text-lg font-bold leading-[1.8125rem]" data-ditto-id="style-link-4" data-component="heading">
                    Acknowledgement
                  </h2>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-link-5">
                    The authors would like to thank MIT colleagues and the broader driving and artificial intelligence research community for their valuable feedback and discussions throughout the development and on-going operation of this study.
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-p-5">
                    They would also like to thank the many vehicle owners who have provided and continue to provide valuable insights (via email or in-person discussion) about their experiences interacting with these systems. Lastly, they would like to thank the annotation teams at MIT and Touchstone Evaluations for their help in continually evolving a state-of-the-art framework for annotation and discovering new essential elements necessary for understanding human behavior in the context of advanced vehicle technologies.
                  </p>
                  {" "}
                  <p className="box-content block mb-6" data-ditto-id="style-link-6">
                    Support for this work was provided by the Advanced Vehicle Technology (AVT) consortium at MIT. The views and conclusions being expressed are those of the authors, and have not been sponsored, approved, or necessarily endorsed by members of the consortium. All authors listed as affiliated with MIT contributed to the work only during their time at MIT as employees or visiting graduate students.
                  </p>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              <div className="box-content block" data-ditto-id="style-link-7" id="comments" />
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
