import "./ditto.css";
import ListRow from "./components/list-row";
import MediaCard from "./components/media-card";
import MediaTile from "./components/media-tile";
import Logo from "./components/logo";
import MediaTile2 from "./components/media-tile2";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/seminarangebot", label: "Seminarangebot" },
    { href: "/kundenprojekte", label: "Kundenprojekte" },
    { href: "/managed-training-services", label: "Training Services" },
    { href: "/weiterbildung-mit-integrata-cegos", label: "Mehr erfahren" },
    { href: "/digitales-lernen", label: "Digitales Lernen" },
    { href: "/blog", label: "Blog" }
];
const MediaCard_data = [
    { srcSet: "/assets/cloned/images/d8e4be442e0d.webp 500w, /assets/cloned/images/bdcc0d31a7f4.webp 320w", imgSrc: "/assets/cloned/images/56f6703187fe.png", title: "Projektmanagement und Scrum Schulungen in Düsseldorf", description: "Wer in NRW Projekte verantwortet, profitiert von einer fundierten Zertifizierung. In Düsseldorf bieten wir die international anerkannten Programme PMP, PRINCE2, Scrum Master und Product Owner – durchgeführt von erfahrenen Trainerinnen und Trainern mit Praxisbezug zur Region.", kind: "button", label: "Mehr unter Projektmanagement" },
    { srcSet: "/assets/cloned/images/7e922765e82b.webp 500w, /assets/cloned/images/91766d7236e3.webp 320w", imgSrc: "/assets/cloned/images/83c89dc6a1e8.png", title: "Rhetorik Seminar und Präsentationstraining Düsseldorf", description: "Überzeugend auftreten vor Vorständen, Investoren oder dem eigenen Team. Unsere Rhetorik- und Präsentationsseminare in Düsseldorf trainieren Auftritt, Argumentation und Sprache. Im Trainingszentrum Düsseldorf stehen dafür moderne Räume mit der Ausstattung für Videoaufzeichnungen bereit, sodass Sie sich selbst beobachten und gezielt weiterentwickeln können. Verhandlungsführung gehört ebenfalls zu unserem Trainingsprogramm in Düsseldorf.", kind: "link", label: "Mehr unter Business Skills und Kommunikation" },
    { srcSet: "/assets/cloned/images/54a5f91dce39.webp 500w, /assets/cloned/images/5646c437ecc5.webp 320w", imgSrc: "/assets/cloned/images/c08e746d9a9a.png", title: "IT-Schulungen, Excel und Künstliche Intelligenz in Düsseldorf", description: "Der IT-Standort Düsseldorf wächst und mit ihm die Nachfrage nach qualifizierter Weiterbildung. Wir bieten Schulungen zu Cyber Security, Cloud Computing, Software Engineering und Microsoft Azure. Besonders nachgefragt: Unser Excel Kurs in Düsseldorf für alle Erfahrungsstufen sowie Trainings rund um Künstliche Intelligenz und Data Science. Jeder Trainingsplatz im Düsseldorfer Zentrum ist mit einem eigenen PC ausgestattet.", kind: "link", label: "Mehr unter Künstliche Intelligenz, IT-Trainings und SAP" },
    { srcSet: "/assets/cloned/images/536906fca861.webp 500w, /assets/cloned/images/bb9c3b4835eb.webp 320w", imgSrc: "/assets/cloned/images/5e1764b88090.png", title: "Soft Skills, Kommunikation und Führungskräfteseminar Düsseldorf", description: "Konfliktmanagement, Selbstführung, lösungsorientierte Kommunikation und Leadership-Kompetenz – im Düsseldorfer Trainingszentrum entwickeln Sie die persönliche Wirksamkeit, die in dynamischen Wirtschaftsstrukturen entscheidend ist. Das Führungskräfteseminar Düsseldorf richtet sich sowohl an Nachwuchsführungskräfte als auch an erfahrene Manager:innen.", kind: "link", label: "Mehr unter Soziale Kompetenz, Kommunikation und Management & Leadership" }
];
const MediaTile_data = [
    { srcSet: "/assets/cloned/images/23ad70631146.webp 60w", imgSrc: "/assets/cloned/images/7db61b4140a0.png", description: "  Kostenfreies WLAN mit Glasfaseranbindung für alle Teilnehmer:innen." },
    { srcSet: "/assets/cloned/images/2a7c74b1f39f.webp 60w", imgSrc: "/assets/cloned/images/ce4dabf28b21.png", description: "  Sehr gute ÖPNV-Anbindung sowie Parkmöglichkeiten in den umliegenden Straßen rund um die Grafenberger Allee." },
    { srcSet: "/assets/cloned/images/94b15de94f86.webp 60w", imgSrc: "/assets/cloned/images/59633a93c1ad.png", description: "  Klimatisierung in allen Räumen sowie eine kostenlose Versorgung mit Getränken, frischem Obst, Süßigkeiten in den Pausen und einem Mittagessen (optional)." },
    { srcSet: "/assets/cloned/images/2bc6af3c66d3.webp 60w", imgSrc: "/assets/cloned/images/d0006d70313b.png", description: "  Helle Seminarräume mit einem eigenen PC pro Teilnehmer:in." }
];
const Logo_data = [
    { kind: "image", alt: "IT-Schulung", imgSrc: "/assets/cloned/images/89c09bf072a6.webp" },
    { alt: "IT-Schulung", imgSrc: "/assets/cloned/images/89c09bf072a6.webp" },
    { kind: "image", alt: "Standard Hybrid Schulung", imgSrc: "/assets/cloned/images/95b98aa18f1d.webp" },
    { alt: "Standard Hybrid Schulung", imgSrc: "/assets/cloned/images/95b98aa18f1d.webp" }
];
const MediaTile2_data = [
    { ariaLabel: "LinkedIn", href: "https://www.linkedin.com/company/cegos-integrata/", viewBox: "0 0 20 20", icon: <>
            <path fillRule="evenodd" clipRule="evenodd" d="M4.81395 3.15325C4.81395 4.19084 4.02391 5.03053 2.78844 5.03053C1.6011 5.03053 0.811063 4.19084 0.835513 3.15325C0.811063 2.06524 1.60108 1.25 2.8121 1.25C4.0239 1.25 4.79026 2.06524 4.81395 3.15325ZM0.934844 18.5993V6.51355H4.69093V18.5986H0.934844V18.5993Z" />
            <path fillRule="evenodd" clipRule="evenodd" d="M7.70187 10.3698C7.70187 8.86234 7.6522 7.5772 7.60254 6.5144H10.865L11.0385 8.17011H11.1126C11.6069 7.40376 12.8424 6.24316 14.8442 6.24316C17.3152 6.24316 19.1688 7.87442 19.1688 11.4318V18.6002H15.4127V11.9025C15.4127 10.3446 14.8695 9.28256 13.5102 9.28256C12.4719 9.28256 11.8545 9.99925 11.6077 10.6907C11.5084 10.9383 11.4595 11.2836 11.4595 11.6305V18.6002H7.70339V10.3698H7.70187Z" />
            </>, label: "Linkedin" },
    { ariaLabel: "Facebook", href: "https://www.facebook.com/cegosintegrata", viewBox: "0 0 13 22", icon: <>
            <path d="M8.04142 12.6272V21H4.19527V12.6272H1V9.23225H4.19527V7.99704C4.19527 3.41124 6.11095 1 10.1642 1C11.4068 1 11.7175 1.1997 12.3979 1.36243V4.72041C11.6361 4.58728 11.4216 4.51331 10.6302 4.51331C9.69083 4.51331 9.18787 4.77959 8.72929 5.30473C8.27071 5.82988 8.04142 6.73965 8.04142 8.04142V9.23965H12.3979L11.2293 12.6346H8.04142V12.6272Z" />
            </>, label: "Facebook" },
    { ariaLabel: "YouTube", href: "https://www.youtube.com/@CegosIntegrata", viewBox: "0 0 24 24", role: "img", icon: <>
            <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
            </>, label: "YouTube" }
];
const ListRow2_data = [
    { label: "Management & Leadership" },
    { label: "Kommunikation" },
    { label: "Projektmanagement" },
    { label: "Künstliche Intelligenz" },
    { label: "Software Engineering" },
    { label: "Programmiersprachen" },
    { label: "Microsoft Azure" }
];
const ListRow3_data = [
    { href: "/seminarangebot", label: "Offene Seminare" },
    { href: "/seminarangebot/agilitaet-scrum", label: "Inhouse Seminare" },
    { href: "/seminarangebot/agilitaet-scrum", label: "Digital Learning" },
    { href: "/managed-training-services", label: "Managed Training Services" },
    { href: "/internationale-loesungen", label: "Internationale Lösungen" },
    { href: "/zertifizierungen", label: "Zertifizierungen" },
    { href: "/standorte/duesseldorf", label: "Raumvermietung" }
];
const ListRow3_data2 = [
    { href: "/das-unternehmen", label: "Das Unternehmen" },
    { href: "/das-unternehmen/pressebereich", label: "Presse" },
    { href: "/das-unternehmen/jobs-karriere", label: "Karriere" },
    { href: "/standorte", label: "Trainingszentren" },
    { href: "https://www.cegos.com/en", label: "Cegos Group" }
];
const ListRow3_data3 = [
    { href: "/blog", label: "Blog" },
    { href: "/kontakt/newsletter", label: "Newsletter" },
    { href: "/weiterbildung-mit-integrata-cegos/702010-wie-wir-lernen", label: "Downloads" },
    { href: "/weiterbildung-mit-integrata-cegos/702010-wie-wir-lernen", label: "Garantietermine" },
    { href: "/haeufig-gestellte-fragen-faq", label: "Häufig gestellte Fragen (FAQ)" }
];
const ListRow4_data = [
    { href: "/disclaimer", label: "Disclaimer" },
    { href: "/allgemeine-geschaeftsbedingungen", label: "AGB" },
    { href: "/impressum", label: "Impressum" },
    { href: "/datenschutz", label: "Datenschutz" }
];
const ListRow_meta: string[][] = [
    ["style-kundenbereich", "style-i-2", "n34"],
    ["style-li", "style-link", "n37"],
    ["style-i", "style-span", "n40"],
    ["style-ul", "style-19", "style-399"],
    ["style-7", "style-20", "style-400"],
    ["n47", "style-21", "style-401"]
];
const MediaCard_meta: string[][] = [
    ["style-li-5", "style-p-99", "style-strong-35", "style-br-20", "style-p-106", "style-p-25", "style-strong-42", "style-br-3", "style-br-48", "style-link-12"],
    ["style-p-120", "style-strong-11", "style-br-49", "style-p-26", "style-strong-31", "style-br-16", "style-p-100", "style-heading-3", "style-div-14", "style-heading-7"],
    ["style-ul-8", "style-div-15", "style-link-32", "style-div-16", "style-picture-2", "style-source-3", "style-image-5", "style-div-17", "style-div-11", "style-p-121"],
    ["style-br-17", "style-p-101", "style-p-27", "style-p-102", "style-p-28", "style-p-103", "style-p-88", "style-strong-32", "style-br-44", "style-p-29"]
];
const MediaTile_meta: string[][] = [
    ["style-p-109", "style-p-82", "style-strong-36", "style-br-38"],
    ["style-p-110", "style-ol-2", "style-li-3", "style-li-2"],
    ["style-p-3", "style-strong-46", "style-br-39", "style-p-9"],
    ["style-strong", "style-br", "style-link-20", "style-p-132"]
];
const Logo_meta: string[][] = [
    ["style-p-12", "style-p-61", "style-strong-5"],
    ["style-br-53", "style-p-13", "style-p-113"],
    ["style-strong-37", "style-br-40", "style-p-62"],
    ["style-p-14", "style-strong-22", "style-br-5"]
];
const MediaTile2_meta: string[][] = [
    ["style-strong-21", "style-strong-44", "style-link-23", "style-footer-2", "style-section-4"],
    ["style-div-39", "style-div-12", "style-div-47", "style-link-24", "style-heading-30"],
    ["style-image-6", "style-div-57", "style-heading-8", "style-ul-19", "style-div-18"]
];
const ListRow2_meta: string[][] = [
    ["style-ul-27", "style-link-26"],
    ["style-footer", "style-section"],
    ["style-div-13", "style-heading-28"],
    ["style-ul-2", "style-link-2"],
    ["style-heading", "style-image-11"],
    ["style-div-19", "style-div-48"],
    ["style-heading-9", "style-ul-14"]
];
const ListRow3_meta: string[][] = [
    ["style-div", "style-span-6"],
    ["style-p-2", "style-link-34"],
    ["style-div-2", "style-heading-19"],
    ["style-ul-3", "style-heading-15"],
    ["style-ul-4", "style-source-5"],
    ["style-image-4", "style-div-59"],
    ["style-heading-11", "style-ul-13"]
];
const ListRow3_meta2: string[][] = [
    ["style-div-3", "style-heading-16"],
    ["style-ul-5", "style-picture-3"],
    ["style-source", "style-image-8"],
    ["style-div-4", "style-heading-17"],
    ["style-ul-6", "style-p-130"]
];
const ListRow3_meta3: string[][] = [
    ["style-ul-16", "style-span-18"],
    ["style-section-2", "style-div-22"],
    ["style-div-5", "style-div-23"],
    ["style-link-29", "style-image-9"],
    ["style-span-3", "style-span-7"]
];
const ListRow4_meta: string[][] = [
    ["style-link-30", "style-div-26"],
    ["style-div-7", "style-div-27"],
    ["style-span-20", "style-section-5"],
    ["style-div-40", "style-div-28"]
];
const ListRow_styles = [
    { className: "before:w-41.5" },
    { className: "before:w-40.5" },
    { className: "before:w-41" },
    { className: "before:w-36.5" },
    { className: "before:w-40" },
    { className: "before:w-[7.0625rem]", className2: "py-3 px-4 rounded-[25px] text-background bg-foreground" }
];
const MediaCard_styles = [
    { className: "max-md:h-[45.0375rem]" },
    { className: "max-md:h-[45.0375rem]" },
    { className: "max-md:h-[45.125rem]" },
    { className: "max-md:h-[45.125rem]" }
];
const Logo_styles = [
    { className: "box-content w-[42.125rem] h-[18.425rem] block absolute top-0 left-0 opacity-0", className2: "box-content inline", className3: "box-content w-full h-[18.4375rem] block max-w-full rounded-[10px] overflow-clip object-cover align-bottom max-md:h-31.5 md:max-lg:h-[17.0625rem] 2xl:h-76.5" },
    { className: "hidden max-md:box-content max-md:h-[7.85rem] max-md:block max-md:absolute max-md:inset-x-0 max-md:z-1 2xl:box-content 2xl:h-[19.1125rem] 2xl:block 2xl:absolute 2xl:inset-x-0 2xl:z-1", className2: "hidden max-md:box-content max-md:inline 2xl:box-content 2xl:inline", className3: "hidden max-md:box-content max-md:w-full max-md:h-31.5 max-md:block max-md:max-w-full max-md:rounded-[10px] max-md:overflow-clip max-md:object-cover max-md:align-bottom 2xl:box-content 2xl:w-full 2xl:h-76.5 2xl:block 2xl:max-w-full 2xl:rounded-[10px] 2xl:overflow-clip 2xl:object-cover 2xl:align-bottom" },
    { className: "box-content w-[42.125rem] h-[18.425rem] block absolute top-0 left-0 opacity-0", className2: "box-content inline", className3: "box-content w-full h-[18.4375rem] block max-w-full rounded-[10px] overflow-clip object-cover align-bottom max-md:h-31.5 md:max-lg:h-[17.0625rem] 2xl:h-76.5" },
    { className: "hidden md:max-lg:box-content md:max-lg:w-[27.3rem] md:max-lg:h-[17.0625rem] md:max-lg:block md:max-lg:absolute md:max-lg:z-1", className2: "hidden md:max-lg:box-content md:max-lg:inline", className3: "hidden md:max-lg:box-content md:max-lg:w-full md:max-lg:h-[17.0625rem] md:max-lg:block md:max-lg:max-w-full md:max-lg:rounded-[10px] md:max-lg:overflow-clip md:max-lg:object-cover md:max-lg:align-bottom" }
];
const MediaTile2_styles = [
    { className: "w-auto" },
    { className: "w-[1.5625rem]" },
    { className: "w-auto" }
];
const ListRow2_styles = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];
const ListRow3_styles = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];
const ListRow3_styles2 = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];
const ListRow3_styles3 = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];

export default function Page() {
  return (
    <>
      <a className="box-content w-px h-px block absolute top-0 left-0 z-9999 -m-px overflow-hidden text-primary whitespace-nowrap text-nowrap cursor-pointer" data-ditto-id="style-a" href="#main-content">
        Skip to main content
      </a>
      <div className="box-content block">
        <header className="block relative z-10 text-background bg-background max-lg:hidden" id="header">
          <div className="box-content flex relative max-w-360 pt-5 pb-10 justify-center items-end 2xl:mx-60">
            <div className="box-content w-312.5 block relative pt-2.5 pl-7.5 flex-1 2xl:w-352.5" data-ditto-id="style-div-34">
              <div className="box-content block">
                <a className="box-content block text-primary cursor-pointer" data-ditto-id="style-link-3" data-component="link" href="/">
                  <img className="box-content w-35 h-[4.5625rem] inline max-w-55 max-h-[4.6875rem] mr-[0.9375rem] overflow-clip align-bottom" data-component="image" alt="Logo Integrata Cegos" src="/assets/cloned/images/150c5c7b6f7f.png" />
                  <span className="box-content w-[9.9375rem] h-[2.1rem] border-l border-solid border-l-foreground block absolute top-[6.5px] left-65 mt-2 pl-5 text-foreground [font-family:Ryker,_sans-serif] leading-[1.0625rem]" data-ditto-id="style-span-17">
                    {"Ihr Business Partner für "}
                    <br className="box-content inline" data-ditto-id="style-br-56" />
                    {" Performance Learning"}
                  </span>
                </a>
              </div>
            </div>
            <ul className="box-content w-163.5 h-[2.4375rem] flex absolute top-5 right-7.5 min-w-0 items-center leading-[0.75rem] [list-style-type:none] list-outside max-lg:hidden">
              <li className="box-content w-50 block relative min-w-50 mr-5 pr-7.5 rounded-[40px] text-foreground bg-surface max-lg:invisible">
                <form className="box-content block max-lg:invisible">
                  <div className="box-content block relative max-lg:invisible">
                    <input className="w-full h-9 inline-block p-2.5 overflow-clip leading-4 cursor-pointer max-lg:invisible" data-ditto-id="style-input" data-component="input" name="q" placeholder="Suchbegriff eingeben" />
                    <button className="w-[2.1875rem] h-[2.1875rem] block absolute top-4.5 p-2.5 rounded-[40px] align-middle leading-4 text-center bg-foreground transform-[matrix(1,0,0,1,0,-17.5)] cursor-pointer max-lg:invisible" data-ditto-id="style-suchen" data-component="button" aria-label="Suchen" type="submit" value="Suchen" />
                  </div>
                </form>
              </li>
              <li className="box-content block relative mr-5 py-2.5 pl-2.5 text-foreground max-lg:invisible" data-ditto-id="style-li-8">
                <a className="box-content flex items-center text-background cursor-pointer max-lg:invisible" data-ditto-id="style-kontaktieren-sie-uns" data-component="link" aria-label="Kontaktieren Sie uns" href="/kontakt">
                  <i className="box-content w-5.5 h-[1.1875rem] block italic max-lg:invisible" style={{ backgroundImage: "url(\"/assets/cloned/images/78293a8fa23e.webp\")" }} />
                  <span className="box-content block pl-2.5 text-foreground font-semibold leading-[1.0625rem] max-lg:invisible">
                    Kontaktieren Sie uns
                  </span>
                </a>
              </li>
              <li className="box-content flex relative mr-5 p-2.5 max-lg:invisible" id="accountWrapper">
                <a className="box-content flex items-center cursor-pointer max-lg:invisible" data-ditto-id="style-kundenbereich-2" data-component="link" aria-label="Kundenbereich" href="/kundenbereich" rel="nofollow">
                  <i className="box-content w-[1.1875rem] h-[1.1875rem] block italic max-lg:invisible" style={{ backgroundImage: "url(\"/assets/cloned/images/2d3468a7a88d.webp\")" }} />
                  <span className="box-content block pl-2.5 text-foreground font-semibold leading-[1.0625rem] max-lg:invisible">
                    Kundenbereich
                  </span>
                </a>
              </li>
              <li className="box-content w-10 flex relative pt-2.5 pb-1.5 rounded-[50%] bg-surface max-lg:invisible" data-ditto-id="style-li-6">
                <a className="box-content block text-primary cursor-pointer max-lg:invisible" data-ditto-id="style-link-4" data-component="link" href="https://www.cegos-integrata.de/kundenbereich/warenkorb">
                  <i className="box-content w-[1.3125rem] h-[1.3125rem] block ml-[0.5625rem] italic bg-no-repeat max-lg:invisible" style={{ backgroundImage: "url(\"/assets/cloned/images/954c72e70482.webp\")" }} />
                  <i className="box-content w-5 h-[1.0625rem] block absolute -top-[0.3125rem] -right-2 pt-[0.1875rem] rounded-[50%] text-background [font-family:Ryker,_sans-serif] text-center bg-primary max-lg:invisible" data-ditto-id="style-i-3">
                    <span className="box-content inline leading-[1.0625rem] max-lg:invisible">
                      0
                    </span>
                  </i>
                </a>
              </li>
            </ul>
            <nav className="box-content h-[2.5625rem] block absolute top-25 inset-x-0 min-w-0 max-lg:hidden" data-component="nav">
              <ul className="box-content flex justify-end leading-[1.3125rem] [list-style-type:none] list-outside max-md:hidden">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} styles={ListRow_styles[i]} />)}
                <li className="box-content w-0 h-[2.5625rem] flex items-center max-md:hidden" />
              </ul>
            </nav>
          </div>
        </header>
        <header className="h-17.5 block fixed inset-x-0 z-10 opacity-0 text-background bg-background transform-[matrix(1,0,0,1,0,-70)] max-lg:z-9 max-lg:transform-[none] max-lg:opacity-[initial]" data-ditto-id="style-header">
          <div className="box-content h-full flex relative items-center" data-ditto-id="style-div-32">
            <div className="box-content w-[2.4375rem] h-[2.5625rem] border-r border-solid border-r-foreground flex top-1/2 right-[2.1875rem] mx-auto pr-[0.3125rem] justify-end items-end transform-[none] max-lg:block max-lg:absolute max-lg:top-[2.1875rem] max-md:left-[18.8125rem] max-lg:min-w-0 max-lg:transform-[matrix(1,0,0,1,0,-20.5)] max-lg:border-r-[0] max-lg:border-initial max-lg:border-r-[initial] max-lg:right-auto max-lg:mx-0 max-lg:pr-0 max-lg:[justify-content:initial] max-lg:[align-items:initial] md:max-lg:left-173.5">
              <button className="w-[2.4375rem] h-[2.5625rem] block relative rounded-xs align-middle text-foreground leading-4 text-center cursor-pointer max-lg:inline-block max-md:leading-[0.9375rem]" data-ditto-id="style-navigation-anzeigen-ausblenden" data-component="button" aria-label="Navigation anzeigen/ausblenden" type="button">
                <span className="box-content w-[1.8125rem] h-[0.1875rem] block absolute top-[0.5625rem] left-[0.3125rem] rounded-sm leading-[1.0625rem] bg-foreground max-lg:leading-[inherit]" data-ditto-id="style-span-10" />
                <span className="box-content w-[1.8125rem] h-[0.1875rem] block absolute top-[1.1875rem] left-[0.3125rem] rounded-sm leading-[1.0625rem] bg-foreground max-lg:leading-[inherit] after:content-[''] after:block after:absolute after:inset-0 after:w-[1.8125rem] after:h-[0.1875rem] after:bg-foreground after:rounded-tl-sm" />
                <span className="box-content w-[1.8125rem] h-[0.1875rem] block absolute top-[1.8125rem] right-[0.3125rem] rounded-sm leading-[1.0625rem] bg-foreground max-lg:leading-[inherit]" />
              </button>
            </div>
            <div className="box-content w-[28%] flex relative p-7.5 items-center max-md:w-[56.5%] max-lg:block max-md:pl-5 max-lg:flex-1 max-md:py-0 max-md:pr-0 max-lg:[align-items:initial] md:max-lg:w-[78.5%] md:max-lg:p-0 2xl:w-[62.5%] 2xl:justify-start 2xl:grow" data-ditto-id="style-div-33">
              <a className="box-content h-[2.8125rem] block text-primary cursor-pointer max-lg:h-auto" data-component="link" href="/">
                <img className="box-content w-[5.4375rem] h-[2.8125rem] inline max-w-35 max-h-[2.8125rem] overflow-clip align-bottom" data-component="image" alt="Logo Integrata Cegos" src="/assets/cloned/images/150c5c7b6f7f.png" />
              </a>
            </div>
            <ul className="box-content w-163.5 h-[2.4375rem] flex absolute top-5 left-149 min-w-0 items-center leading-[0.75rem] [list-style-type:none] list-outside max-lg:hidden 2xl:right-7.5 2xl:static 2xl:left-auto">
              <li className="box-content w-50 block relative min-w-50 mr-5 pr-7.5 rounded-[40px] text-foreground bg-surface max-lg:invisible">
                <form className="box-content block max-lg:invisible">
                  <div className="box-content block relative max-lg:invisible">
                    <input className="w-full h-9 inline-block p-2.5 overflow-clip leading-4 cursor-pointer max-lg:invisible" data-ditto-id="style-input-2" data-component="input" name="q" placeholder="Suchbegriff eingeben" type="search" />
                    <button className="w-[2.1875rem] h-[2.1875rem] block absolute top-4.5 p-2.5 rounded-[40px] align-middle leading-4 text-center bg-foreground transform-[matrix(1,0,0,1,0,-17.5)] cursor-pointer max-lg:invisible" data-ditto-id="style-suchen-2" data-component="button" aria-label="Suchen" type="submit" value="Suchen" />
                  </div>
                </form>
              </li>
              <li className="box-content block relative mr-5 py-2.5 pl-2.5 text-foreground max-lg:invisible">
                <a className="box-content flex items-center text-background cursor-pointer max-lg:invisible" data-component="link" aria-label="Kontaktieren Sie uns" href="/kontakt">
                  <i className="box-content w-5.5 h-[1.1875rem] block italic max-lg:invisible" style={{ backgroundImage: "url(\"/assets/cloned/images/78293a8fa23e.webp\")" }} />
                  <span className="box-content block pl-2.5 text-foreground font-semibold leading-[1.0625rem] max-lg:invisible">
                    Kontaktieren Sie uns
                  </span>
                </a>
              </li>
              <li className="box-content flex relative mr-5 p-2.5 max-lg:invisible" id="accountWrapper">
                <a className="box-content flex items-center cursor-pointer max-lg:invisible" data-component="link" aria-label="Kundenbereich" href="https://www.cegos-integrata.de/kundenbereich/einloggen?redirect=https%3A%2F%2Fwww.cegos-integrata.de%2Fstandorte%2Fduesseldorf" rel="nofollow">
                  <i className="box-content w-[1.1875rem] h-[1.1875rem] block italic max-lg:invisible" style={{ backgroundImage: "url(\"/assets/cloned/images/2d3468a7a88d.webp\")" }} />
                  <span className="box-content block pl-2.5 text-foreground font-semibold leading-[1.0625rem] max-lg:invisible">
                    Kundenbereich
                  </span>
                </a>
              </li>
              <li className="box-content w-10 flex relative pt-2.5 pb-1.5 rounded-[50%] bg-surface max-lg:invisible" data-ditto-id="style-li-7">
                <a className="box-content block text-primary cursor-pointer max-lg:invisible" data-ditto-id="style-link-38" data-component="link" href="https://www.cegos-integrata.de/kundenbereich/warenkorb">
                  <i className="box-content w-[1.3125rem] h-[1.3125rem] block ml-[0.5625rem] italic bg-no-repeat max-lg:invisible" style={{ backgroundImage: "url(\"/assets/cloned/images/954c72e70482.webp\")" }} />
                  <i className="box-content w-5 h-[1.0625rem] block absolute -top-[0.3125rem] -right-2 pt-[0.1875rem] rounded-[50%] text-background [font-family:Ryker,_sans-serif] text-center bg-primary max-lg:invisible">
                    <span className="box-content inline leading-[1.0625rem] max-lg:invisible">
                      0
                    </span>
                  </i>
                </a>
              </li>
            </ul>
            <ul className="box-content hidden float-right min-w-0 mt-1 mr-25.5 items-center leading-[1.3125rem] [list-style-type:none] list-outside max-lg:flex max-lg:leading-[1.25rem]">
              <li className="box-content inline-block relative pr-2.5 align-top max-lg:block">
                …
              </li>
              <li className="box-content inline-block relative pr-2.5 max-lg:block" />
              <li className="box-content inline-block relative pr-2.5 max-lg:block max-lg:pl-2.5" />
              <li className="box-content inline-block relative max-lg:block">
                <a className="box-content block text-foreground cursor-pointer max-lg:h-9" aria-label="Meine Wunschliste" href="https://www.cegos-integrata.de/kundenbereich/warenkorb">
                  <i className="box-content inline italic before:content-[''] before:text-foreground before:text-2xl before:leading-9 2xl:before:hidden" />
                  <i className="h-[0.9375rem] block absolute -top-0.5 -right-2 min-w-[0.9375rem] px-0.5 rounded-[100%] text-background text-[0.8125rem] leading-[0.9375rem] text-center bg-primary max-lg:w-[0.9375rem]">
                    <span className="box-content inline-block pl-px leading-[1rem] max-lg:h-0 max-lg:leading-[inherit]" />
                  </i>
                </a>
              </li>
            </ul>
          </div>
          <div className="box-content h-[0.3125rem] block fixed inset-x-0 bg-background" />
        </header>
        <nav className="box-content block" data-component="nav">
          <nav className="hidden max-md:box-content max-md:block" />
        </nav>
        <main className="box-content block relative bg-background max-lg:pt-[4.6875rem]" id="main-content">
          <div className="box-content block overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif]">
            <div className="block px-[57.5px] bg-surface max-lg:px-2.5 2xl:px-[377.5px]">
              <p className="block py-2.5 text-xs leading-[1.0625rem] max-md:text-[0.6875rem] max-md:leading-4" data-ditto-id="style-p-135">
                {"Sie sind hier: "}
                <a className="inline text-muted-foreground cursor-pointer" data-ditto-id="style-link-5" data-component="link" href="/" title="Startseite">
                  Startseite
                </a>
                {" > "}
                <a className="inline text-muted-foreground cursor-pointer" data-ditto-id="style-span-4" data-component="link" href="/standorte">
                  Standorte
                </a>
                {" > "}
                <span className="inline font-semibold" data-ditto-id="style-div-58">
                  Seminare in Düsseldorf – Trainingszentrum Cegos Integrata
                </span>
              </p>
            </div>
            <div className="block relative mb-5 overflow-hidden bg-accent bg-contain [background-position:100%_0px] bg-no-repeat w-full" style={{ backgroundImage: "url(\"/assets/cloned/images/02a4b344ab7d.webp\")" }}>
              <h1 className="inline-flex py-12.5 px-[57.5px] items-center text-background [font-family:Ryker,_sans-serif,_sans-serif] text-[3.125rem] font-medium leading-[3.625rem] max-md:py-[31.3px] max-lg:px-2.5 max-md:text-[1.9375rem] max-md:leading-9 md:max-lg:py-[2.525rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.875rem] 2xl:px-[377.5px]" data-component="heading">
                {" Seminare in Düsseldorf – Trainingszentrum Cegos Integrata "}
              </h1>
            </div>
          </div>
          <section className="box-content block py-10 px-[4.9rem] max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0">
            <div className="box-content flex mb-20 justify-between items-start gap-5 max-lg:flex-col max-lg:[justify-content:initial] max-lg:[align-items:initial]" data-ditto-id="style-figure">
              <div className="box-content flex flex-col flex-1 max-lg:grow-[initial] max-lg:basis-[initial]" data-ditto-id="style-picture">
                <div className="box-content block min-w-0 overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif]" data-ditto-id="style-source-2">
                  <div className="grid rounded-[10px] overflow-hidden grid-cols-2 max-md:grid-cols-1" data-ditto-id="style-image-2">
                    <div className="block p-12.5 bg-surface max-md:p-[31.3px] max-md:rounded-tl-[10px] max-md:rounded-tr-[10px]" data-ditto-id="style-heading-14">
                      <p className="block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p">
                        {"Weiterbildungen in Düsseldorf für Fach- und Führungskräfte bei Cegos Integrata: Im "}
                        <strong className="inline font-bold" data-ditto-id="style-agb-oc">
                          Trainingszentrum Düsseldorf
                        </strong>
                        {" trainieren Sie zu Projektmanagement, Excel, Rhetorik, IT, Künstlicher Intelligenz und mehr – wahlweise als Präsenz vor Ort oder Live Online."}
                      </p>
                      <a className="border border-solid border-clr-0 inline-flex py-[0.5625rem] px-4.5 rounded-[40px] justify-center items-center text-background font-semibold leading-[1.125rem] bg-foreground cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-heading-5" data-component="button" href="https://www.cegos-integrata.de/standorte/duesseldorf/calendar-duesseldorf">
                        Seminarkalender Düsseldorf ansehen
                      </a>
                    </div>
                    <div className="block relative" data-ditto-id="style-p-112">
                      <picture className="inline" data-ditto-id="style-strong-16">
                        <source className="inline" data-ditto-id="style-br-12" sizes="auto" srcSet="/assets/cloned/images/8f3ef4e11fa7.webp 1920w, /assets/cloned/images/f3914c5cd2ce.webp 1920w, /assets/cloned/images/2008d55540c3.webp 1600w, /assets/cloned/images/b7d7d475da89.webp 1366w, /assets/cloned/images/8a50861007fb.webp 1024w, /assets/cloned/images/cc9d29c5de6a.webp 768w, /assets/cloned/images/fbc610d676b8.webp 640w, /assets/cloned/images/bec111082272.webp 320w" type="image/webp" />
                        <img className="w-full h-[26.1875rem] inline max-w-full rounded-[10px] overflow-clip object-cover aspect-[auto_1920/2560] align-bottom max-md:h-[27.9375rem] max-md:rounded-tl-[initial] max-md:rounded-tr-[initial] md:max-lg:h-[30.3125rem] 2xl:h-99.5" data-ditto-id="style-p-39" data-component="image" height="2560" sizes="auto" src="/assets/cloned/images/45b944b88c4e.jpg" srcSet="/assets/cloned/images/45b944b88c4e.jpg 1920w, /assets/cloned/images/2ef447b38a18.jpg 1920w, /assets/cloned/images/34e7f9c8d187.jpg 1600w, /assets/cloned/images/efc999fe967e.jpg 1366w, /assets/cloned/images/eb4bc083f150.jpg 1024w, /assets/cloned/images/9333a9b59dd0.jpg 768w, /assets/cloned/images/5d3a4344783a.jpg 640w, /assets/cloned/images/feb90fb50813.jpg 320w" width="1920" />
                      </picture>
                    </div>
                  </div>
                </div>
              </div>
              <div className="box-content flex flex-col flex-1 max-lg:grow-[initial] max-lg:basis-[initial]" data-ditto-id="style-p-24">
                <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-strong-19" data-component="heading">
                  <strong className="box-content inline font-black" data-ditto-id="style-br-13">
                    Cegos Integrata Düsseldorf – Ihr Trainingszentrum
                  </strong>
                </h2>
                <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-40">
                  {"Unser "}
                  <strong className="box-content inline font-bold" data-ditto-id="style-p-60">
                    {"Trainingszentrum "}
                  </strong>
                  liegt im Bürokomplex Global Gate an der Grafenberger Allee 293, gut erreichbar aus dem gesamten Rhein-Ruhr-Gebiet. Die Straßenbahnlinie 709 bringt Sie in rund 10 Minuten vom Hauptbahnhof direkt vor die Tür: Die Haltestelle Schlüterstraße/Arbeitsagentur liegt unmittelbar gegenüber dem Eingang. Auch aus dem Ruhrgebiet, Köln oder den niederländischen Grenzregionen sind Sie schnell vor Ort.
                </p>
                <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-link-6">
                  {"Mit über vier Jahrzehnten Erfahrung im Performance Learning und "}
                  <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-p-33" data-component="link" href="/weiterbildung-mit-integrata-cegos/702010-wie-wir-lernen">
                    mehrfacher Auszeichnung
                  </a>
                  {" gehört Cegos Integrata zu den etablierten Weiterbildungsanbietern im DACH-Raum."}
                </p>
                <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-128">
                  {"📍 "}
                  <strong className="box-content inline font-bold" data-ditto-id="style-strong-23">
                    <strong className="box-content inline font-black" data-ditto-id="style-br-47">
                      {"Cegos "}
                    </strong>
                    Integrata GmbH
                  </strong>
                  , Global Gate, Grafenberger Allee 293, 40237 Düsseldorf
                  <br className="box-content inline" data-ditto-id="style-br-31" />
                  <br className="box-content inline" data-ditto-id="style-p-122" />
                  <strong className="box-content inline font-bold" data-ditto-id="interaction-p">
                    Seminarmanagement und -service
                  </strong>
                  <br className="box-content inline" data-ditto-id="style-p-56" />
                  ☎️ Tel: +49 711 225574 - 0
                  <br className="box-content inline" data-ditto-id="style-link-33" />
                  {"📧 "}
                  <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-link-7" data-component="link" href="mailto:seminarmanagement@cegos.de">
                    seminarmanagement@cegos.de
                  </a>
                </p>
              </div>
            </div>
            <div className="box-content block overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif]" data-ditto-id="style-p-5">
              <div className="flex mb-25 rounded-[10px] overflow-hidden bg-surface w-full max-md:flex-col" data-ditto-id="style-p-97">
                <div className="block p-5 self-center flex-1 [font-family:Ryker,_sans-serif] text-base font-medium leading-[1.4375rem] max-md:text-sm max-md:leading-[1.3125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.375rem]" data-ditto-id="style-strong-10">
                  <p className="block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-95">
                    <strong className="inline font-bold" data-ditto-id="style-strong-43">
                      Sie planen ein Seminar in Düsseldorf?
                    </strong>
                    <br className="inline" data-ditto-id="style-br-51" />
                    {" Wir beraten Sie gerne persönlich und unterstützen Sie dabei, das passende Training für Ihre Ziele, Ihr Team und das gewünschte Format zu finden."}
                  </p>
                </div>
                <div className="block p-5 self-center" data-ditto-id="style-p-98">
                  <a className="border border-solid border-clr-0 inline-flex py-[0.5625rem] px-4.5 rounded-[40px] justify-center items-center text-background font-semibold leading-[1.125rem] bg-foreground cursor-pointer whitespace-nowrap max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-p-96" data-component="button" href="/kontakt">
                    Jetzt Beratung anfragen
                  </a>
                </div>
              </div>
            </div>
          </section>
          <section className="box-content block py-10 px-[4.9rem] text-background bg-color-015 bg-contain bg-no-repeat max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" style={{ backgroundImage: "url(\"/assets/cloned/images/7a1852550d1b.webp\")" }} data-ditto-id="style-strong-30">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-br-14" data-component="heading">
              Direkt zu den Inhalten
            </h2>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-p-6" data-component="link" href="#Seminarangebot">
              Seminarangebote in Düsseldorf auf einen Blick
            </a>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-link-8" data-component="button" href="#Inhouse">
              Inhouse-Trainings in Düsseldorf
            </a>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-link-9" data-component="link" href="#Vorteile">
              Ihre Vorteile an unserem Trainingszentrum in Düsseldorf
            </a>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-link-10" data-component="button" href="#Ausstattung">
              Service und Ausstattung
            </a>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-link-11" data-component="button" href="#Anreise">
              Anfahrt
            </a>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-br-11" data-component="button" href="#FAQ">
              FAQs
            </a>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle text-foreground font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-p-23" data-component="button" href="#Kontakt">
              Kontakt
            </a>
          </section>
          <section className="box-content block py-10 px-[4.9rem] max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-p-87" id="Seminarangebot">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-strong-47" data-component="heading">
              <strong className="box-content inline font-black" data-ditto-id="style-br-15">
                Seminarangebote in Düsseldorf auf einen Blick
              </strong>
            </h2>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-7">
              Im Trainingszentrum Düsseldorf finden Sie unser vollständiges Portfolio vor Ort: agile und klassische Methoden, Microsoft-Office-Anwendungen, Rhetorik und Kommunikation, IT-Trainings sowie Schulungen rund um Künstliche Intelligenz. Die meisten Seminare lassen sich alternativ auch im Live-Online-Format buchen.
            </p>
            <a className="box-content border border-solid border-foreground inline-block m-2.5 py-[0.5625rem] px-4.5 rounded-[40px] align-middle font-semibold leading-[1.125rem] text-center bg-background cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-ol" data-component="button" href="https://www.cegos-integrata.de/standorte/duesseldorf/calendar-duesseldorf">
              Seminarkalender Düsseldorf ansehen
            </a>
            <section className="box-content grid py-10 gap-5 grid-cols-2 after:content-[''] after:table after:w-[34.475rem] after:h-0 max-md:after:w-[157.5px] md:max-lg:after:w-88.5 2xl:after:w-[572.5px]" data-ditto-id="style-li-4">
              {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} styles={MediaCard_styles[i]} />)}
            </section>
          </section>
          <section className="box-content grid py-10 px-[4.9rem] gap-5 text-background bg-color-015 bg-contain [background-position:100%_0px] bg-no-repeat grid-cols-2 max-lg:px-5 max-lg:grid-cols-1 2xl:px-[377.5px] after:content-[''] after:table after:w-[34.475rem] after:h-0 max-md:after:w-[20.9375rem] md:max-lg:after:w-182 2xl:after:w-[572.5px]" style={{ backgroundImage: "url(\"/assets/cloned/images/f85547667ccd.webp\")" }} data-ditto-id="style-p-107" id="Inhouse">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-strong-12" data-component="heading">
              Inhouse-Trainings in Düsseldorf
            </h2>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-123">
              {"Sie haben Ihr Wunschseminar gefunden? Fragen Sie dieses gerne auch als Inhouse-Training für Ihr Team an: individuell auf Ihre Ziele, Anforderungen und den Kenntnisstand Ihrer Mitarbeitenden abgestimmt. Online, bei Ihnen im Unternehmen oder in unserem Trainingszentrum in Düsseldorf. "}
              <a className="box-content inline cursor-pointer" data-ditto-id="style-strong-13" data-component="link" href="https://www.cegos-integrata.de/persoenliche-und-berufliche-entwicklung/inhouse-seminare">
                <mark className="box-content inline text-color-013" data-ditto-id="style-link-13">
                  Mehr zu Inhouse-Seminaren
                </mark>
              </a>
            </p>
          </section>
          <section className="box-content block py-10 px-[4.9rem] max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-agb-dl" id="Vorteile">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-hr-2" data-component="heading">
              Ihre Vorteile an unserem Trainingszentrum in Düsseldorf
            </h2>
            <div className="box-content block overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif]" data-ditto-id="style-p-30">
              <div className="grid my-12.5 gap-7.5 grid-cols-3 max-md:my-[31.3px] max-md:grid-cols-1 md:max-lg:my-[2.525rem]" data-ditto-id="style-heading-6">
                <div className="flex rounded-[10px] flex-col justify-between overflow-hidden text-center bg-surface" data-ditto-id="style-p-8">
                  <div className="block" data-ditto-id="style-strong-33">
                    <div className="block overflow-hidden aspect-video" data-ditto-id="style-br-45">
                      <picture className="inline" data-ditto-id="style-br-18">
                        <source className="inline" data-ditto-id="style-p-108" sizes="auto" srcSet="/assets/cloned/images/5b2bf3ccea70.webp 2048w, /assets/cloned/images/3e32762c1b4a.webp 1920w, /assets/cloned/images/ba1476eee650.webp 1600w, /assets/cloned/images/1b53a2cc1a62.webp 1366w, /assets/cloned/images/7e526283d6fd.webp 1024w, /assets/cloned/images/cfac75e45f77.webp 768w, /assets/cloned/images/cb55ce63c093.webp 640w, /assets/cloned/images/3e04661bdb10.webp 320w" type="image/webp" />
                        <img className="w-full block max-w-full overflow-clip object-cover aspect-[auto_640/360] align-bottom h-full" data-ditto-id="style-strong-14" data-component="image" height="360" sizes="auto" src="/assets/cloned/images/261d3f56fb4a.jpg" srcSet="/assets/cloned/images/261d3f56fb4a.jpg 2048w, /assets/cloned/images/f9d58be4ef55.jpg 1920w, /assets/cloned/images/04035a47f830.jpg 1600w, /assets/cloned/images/c0bfc75985f2.jpg 1366w, /assets/cloned/images/76bc514d535c.jpg 1024w, /assets/cloned/images/7b64e4855388.jpg 768w, /assets/cloned/images/a67885f67523.jpg 640w, /assets/cloned/images/c45cd925ae91.jpg 320w" width="640" />
                      </picture>
                    </div>
                    <div className="block pt-5 px-5 max-md:pt-[16.3px] max-md:px-[16.3px] md:max-lg:pt-[1.125rem] md:max-lg:px-[1.125rem]" data-ditto-id="style-br-36">
                      <h3 className="block mb-2.5 text-xl font-bold leading-[1.5625rem] max-md:text-base max-md:leading-[1.25rem] md:max-lg:text-lg md:max-lg:leading-[1.4375rem]" data-ditto-id="style-p-31" data-component="heading">
                        Moderne Seminarräume mit professioneller Ausstattung
                      </h3>
                      <p className="block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-strong-28">
                        Unsere Seminaräume in Düsseldorf sind technisch hochwertig ausgestattet und auf professionelle Seminare und Veranstaltungen ausgerichtet. Moderne Medientechnik unterstützt den Lernprozess und ermöglicht effizientes Arbeiten. Ob Workshop oder Schulung in großem oder kleinem Umfang – unsere Räume passen wir gerne flexibel an die Anforderungen der jeweiligen Schulung an. Unser Highlight in Düsseldorf: unser Premium Hybridraum, besonders ideal für interaktive Soft-Skill-, Führungs- und Workshopformate
                      </p>
                    </div>
                  </div>
                </div>
                <div className="flex rounded-[10px] flex-col justify-between overflow-hidden text-center bg-surface" data-ditto-id="style-br-19">
                  <div className="block" data-ditto-id="style-p-104">
                    <div className="block overflow-hidden aspect-video" data-ditto-id="style-link-14">
                      <picture className="inline" data-ditto-id="style-p-78">
                        <source className="inline" data-ditto-id="style-p-79" sizes="auto" srcSet="/assets/cloned/images/bbc3095e7ee6.webp 1094w, /assets/cloned/images/b2fc61260367.webp 1024w, /assets/cloned/images/9c2fe7b12e73.webp 768w, /assets/cloned/images/f6f63192b0e5.webp 640w, /assets/cloned/images/5d26040cb4e8.webp 320w" type="image/webp" />
                        <img className="w-full block max-w-full overflow-clip object-cover aspect-[auto_640/360] align-bottom h-full" data-ditto-id="style-strong-41" data-component="image" height="360" sizes="auto" src="/assets/cloned/images/0e5e1fa5f10b.jpg" srcSet="/assets/cloned/images/0e5e1fa5f10b.jpg 1094w, /assets/cloned/images/53282bb1ec3d.jpg 1024w, /assets/cloned/images/1bca0c380b8c.jpg 768w, /assets/cloned/images/840f26e0193e.jpg 640w, /assets/cloned/images/a2b4ff1fbed6.jpg 320w" width="640" />
                      </picture>
                    </div>
                    <div className="block pt-5 px-5 max-md:pt-[16.3px] max-md:px-[16.3px] md:max-lg:pt-[1.125rem] md:max-lg:px-[1.125rem]" data-ditto-id="style-br-46">
                      <h3 className="block mb-2.5 text-xl font-bold leading-[1.5625rem] max-md:text-base max-md:leading-[1.25rem] md:max-lg:text-lg md:max-lg:leading-[1.4375rem]" data-ditto-id="style-p-81" data-component="heading">
                        Über 60 Jahre Erfahrung in der Weiterbildung
                      </h3>
                      <p className="block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-80">
                        Als erfahrener und etablierter Weiterbildungsanbieter mit mehr als 60 Jahren Expertise in der beruflichen Weiterbildung wissen wir, worauf es ankommt, damit Lernen zum Erfolg wird. Von der optimalen Raumgestaltung bis zur modernen Infrastruktur bietet unser modernes Trainingszentrum Düsseldorf ideale Voraussetzungen für professionelle Schulungen und den Austausch zwischen Teilnehmenden und Trainer:innen.
                      </p>
                    </div>
                  </div>
                  <div className="block pb-5 px-5 max-md:pb-[16.3px] max-md:px-[16.3px] md:max-lg:mt-[29.1px] md:max-lg:pb-[1.125rem] md:max-lg:px-[1.125rem]" data-ditto-id="style-link-15">
                    <a className="border border-solid border-clr-0 inline-flex py-[0.5625rem] px-4.5 rounded-[40px] justify-center items-center text-background font-semibold leading-[1.125rem] bg-foreground cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-p-126" data-component="button" href="/weiterbildung-mit-integrata-cegos/702010-wie-wir-lernen">
                      Weitere Gute Gründe für Cegos Integrata
                    </a>
                  </div>
                </div>
                <div className="flex rounded-[10px] flex-col justify-between overflow-hidden text-center bg-surface" data-ditto-id="style-strong-34">
                  <div className="block" data-ditto-id="style-br-54">
                    <div className="block overflow-hidden aspect-video" data-ditto-id="style-p-105">
                      <picture className="inline" data-ditto-id="style-br-50">
                        <source className="inline" data-ditto-id="style-strong-15" sizes="auto" srcSet="/assets/cloned/images/8f3ef4e11fa7.webp 1920w, /assets/cloned/images/f3914c5cd2ce.webp 1920w, /assets/cloned/images/2008d55540c3.webp 1600w, /assets/cloned/images/b7d7d475da89.webp 1366w, /assets/cloned/images/8a50861007fb.webp 1024w, /assets/cloned/images/cc9d29c5de6a.webp 768w, /assets/cloned/images/fbc610d676b8.webp 640w, /assets/cloned/images/bec111082272.webp 320w" type="image/webp" />
                        <img className="w-full block max-w-full overflow-clip object-cover aspect-[auto_640/360] align-bottom h-full" data-ditto-id="style-br-37" data-component="image" height="360" sizes="auto" src="/assets/cloned/images/45b944b88c4e.jpg" srcSet="/assets/cloned/images/45b944b88c4e.jpg 1920w, /assets/cloned/images/2ef447b38a18.jpg 1920w, /assets/cloned/images/34e7f9c8d187.jpg 1600w, /assets/cloned/images/efc999fe967e.jpg 1366w, /assets/cloned/images/eb4bc083f150.jpg 1024w, /assets/cloned/images/9333a9b59dd0.jpg 768w, /assets/cloned/images/5d3a4344783a.jpg 640w, /assets/cloned/images/feb90fb50813.jpg 320w" width="640" />
                      </picture>
                    </div>
                    <div className="block pt-5 px-5 max-md:pt-[16.3px] max-md:px-[16.3px] md:max-lg:pt-[1.125rem] md:max-lg:px-[1.125rem]" data-ditto-id="style-p-32">
                      <h3 className="block mb-2.5 text-xl font-bold leading-[1.5625rem] max-md:text-base max-md:leading-[1.25rem] md:max-lg:text-lg md:max-lg:leading-[1.4375rem]" data-ditto-id="style-link-16" data-component="heading">
                        Zentrale Lage mit guter Erreichbarkeit
                      </h3>
                      <p className="block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-link-17">
                        Unser Standort in Düsseldorf ist zentral gelegen und bequem mit dem Auto sowie mit öffentlichen Verkehrsmitteln erreichbar. Das erleichtert Ihnen die Organisation und sorgt für eine angenehme Anreise Ihrer Teilnehmer:innen.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className="box-content block py-10 px-[4.9rem] text-background bg-color-015 bg-contain [background-position:100%_0px] bg-no-repeat max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" style={{ backgroundImage: "url(\"/assets/cloned/images/f85547667ccd.webp\")" }} data-ditto-id="style-link-18" id="Ausstattung">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-link-19" data-component="heading">
              Service und Ausstattung im Trainingszentrum Düsseldorf
            </h2>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-br-4">
              Konzentriertes Lernen braucht eine passende Umgebung. Im Trainingszentrum Düsseldorf erwartet Sie eine optimale Lernumgebung in ruhiger Lage, dazu gehört:
            </p>
            {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} />)}
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-strong-2">
              <picture className="box-content w-7.5 inline" data-ditto-id="style-br-2">
                <source className="box-content inline" data-ditto-id="style-p-4" sizes="(min-width:60px) 60px" srcSet="/assets/cloned/images/81fdec2e466a.webp 60w" type="image/webp" />
                <img className="box-content w-7.5 h-7.5 inline max-w-full rounded-[10px] overflow-clip align-bottom" data-ditto-id="style-br-55" data-component="image" src="/assets/cloned/images/b8a7fc809b29.png" />
              </picture>
              {" Für externe Trainer:innen und Veranstalter besteht zudem die Möglichkeit, einzelne Räume zu mieten. Details und Konditionen auf der Seite "}
              <a className="box-content inline cursor-pointer" data-ditto-id="style-p-83" data-component="link" href="/standorte/duesseldorf">
                <mark className="box-content inline text-color-013" data-ditto-id="style-strong-45">
                  Raumvermietung
                </mark>
              </a>
              .
            </p>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-br-28">
              <br className="box-content inline" data-ditto-id="style-p-127" />
            </p>
            <section className="box-content w-[42.125rem] block relative max-w-full mr-[224.7px] ml-[14.0375rem] overflow-hidden aspect-[16/7] bg-surface max-md:w-[12.5625rem] max-md:mx-[4.1875rem] max-lg:aspect-[8/5] md:max-lg:w-[27.3rem] md:max-lg:mx-[9.1rem] 2xl:w-[43.6875rem] 2xl:mx-[14.5625rem] after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-p-57" aria-label="Bildergalerie">
              <div className="box-content h-full block" data-ditto-id="style-p-10">
                <div className="box-content w-[42.125rem] h-[18.425rem] block absolute opacity-[0.171363] max-lg:opacity-0 2xl:opacity-0" data-ditto-id="style-p-58">
                  <picture className="box-content inline" data-ditto-id="style-strong-3">
                    <img className="box-content w-full h-[18.4375rem] block max-w-full rounded-[10px] overflow-clip object-cover align-bottom max-md:h-31.5 md:max-lg:h-[17.0625rem] 2xl:h-76.5" data-ditto-id="style-br-29" data-component="image" alt="Premium Hybrid Schulung" src="/assets/cloned/images/3e32762c1b4a.webp" />
                  </picture>
                </div>
                <div className="box-content w-[42.125rem] h-[18.425rem] block absolute z-1 opacity-[0.828637] max-lg:hidden 2xl:hidden" data-ditto-id="style-p-11">
                  <picture className="box-content inline max-lg:hidden 2xl:hidden" data-ditto-id="style-p-129">
                    <source className="box-content inline max-lg:hidden 2xl:hidden" data-ditto-id="style-strong-4" srcSet="/assets/cloned/images/a75d851feb50.webp 2048w, /assets/cloned/images/d27710d43c22.webp 1920w, /assets/cloned/images/02a99192c654.webp 1600w, /assets/cloned/images/cb908a6c7bcf.webp 1366w, /assets/cloned/images/c693bb93ba0f.webp 1024w, /assets/cloned/images/58dd7f396c63.webp 768w, /assets/cloned/images/8809c010e25d.webp 640w, /assets/cloned/images/41da17ffd51c.webp 320w" type="image/webp" />
                    <img className="box-content w-full h-[18.4375rem] block max-w-full rounded-[10px] overflow-clip object-cover align-bottom max-lg:hidden 2xl:hidden" data-ditto-id="style-br-52" data-component="image" alt="Theorie im Seminar" src="/assets/cloned/images/21d24add1133.jpg" />
                  </picture>
                </div>
                {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
              </div>
              <button className="w-10.5 h-10.5 block absolute top-[clamp(62.8px,_50%,_calc(100%_-_62.8px))] left-4 z-2 py-px px-1.5 rounded-[50%] text-clr-22 text-2xl leading-6 text-center bg-clr-23 transform-[matrix(1,0,0,1,0,-21)] cursor-pointer max-lg:w-9 max-lg:h-9 max-lg:left-2.5 max-lg:text-xl max-lg:leading-5 max-lg:transform-[matrix(1,0,0,1,0,-18)]" data-ditto-id="style-p-111" data-component="button" aria-label="Vorheriges Bild anzeigen" type="button">
                {" ❮ "}
              </button>
              <button className="w-10.5 h-10.5 block absolute top-[clamp(62.8px,_50%,_calc(100%_-_62.8px))] right-4 z-2 py-px px-1.5 rounded-[50%] text-clr-22 text-2xl leading-6 text-center bg-clr-23 transform-[matrix(1,0,0,1,0,-21)] cursor-pointer max-lg:w-9 max-lg:h-9 max-lg:right-2.5 max-lg:text-xl max-lg:leading-5 max-lg:transform-[matrix(1,0,0,1,0,-18)]" data-ditto-id="style-strong-6" data-component="button" aria-label="Nächstes Bild anzeigen" type="button">
                {" ❯ "}
              </button>
              <div className="box-content w-16 h-2.5 flex absolute bottom-4 left-[clamp(100.5px,_50%,_calc(100%_-_100.5px))] z-2 gap-2 transform-[matrix(1,0,0,1,-32,0)] max-lg:bottom-2.5" data-ditto-id="style-br-30" aria-label="Slider Navigation">
                <button className="w-2.5 h-2.5 block rounded-[50%] text-color-001 leading-4 text-center bg-surface-4 cursor-pointer max-md:leading-[0.9375rem]" data-ditto-id="style-p-15" data-component="button" aria-label="Bild 1 anzeigen" type="button" />
                <button className="w-2.5 h-2.5 block rounded-[50%] text-color-001 leading-4 text-center bg-background transform-[matrix(1.15,0,0,1.15,0,0)] origin-[5px_5px] cursor-pointer max-lg:hidden 2xl:hidden" data-ditto-id="style-p-89" data-component="button" aria-label="Bild 2 anzeigen" type="button" />
                <button className="w-2.5 h-2.5 block rounded-[50%] text-color-001 leading-4 text-center bg-surface-4 cursor-pointer max-md:leading-[0.9375rem]" data-ditto-id="style-p-16" data-component="button" aria-label="Bild 3 anzeigen" type="button" />
                <button className="hidden max-md:w-2.5 max-md:h-2.5 max-md:block max-md:rounded-[50%] max-md:text-color-001 max-md:leading-[0.9375rem] max-md:text-center max-md:bg-background max-md:transform-[matrix(1.15,0,0,1.15,0,0)] max-md:origin-[5px_5px] max-md:cursor-pointer 2xl:w-2.5 2xl:h-2.5 2xl:block 2xl:rounded-[50%] 2xl:text-color-001 2xl:leading-4 2xl:text-center 2xl:bg-background 2xl:transform-[matrix(1.15,0,0,1.15,0,0)] 2xl:origin-[5px_5px] 2xl:cursor-pointer" data-ditto-id="style-strong-24" aria-label="Bild 3 anzeigen" type="button" />
                <button className="w-2.5 h-2.5 block rounded-[50%] text-color-001 leading-4 text-center bg-surface-4 cursor-pointer max-md:leading-[0.9375rem]" data-ditto-id="style-br-6" data-component="button" aria-label="Bild 4 anzeigen" type="button" />
                <button className="hidden md:max-lg:w-2.5 md:max-lg:h-2.5 md:max-lg:block md:max-lg:rounded-[50%] md:max-lg:text-color-001 md:max-lg:leading-4 md:max-lg:text-center md:max-lg:bg-background md:max-lg:transform-[matrix(1.15,0,0,1.15,0,0)] md:max-lg:origin-[5px_5px] md:max-lg:cursor-pointer" data-ditto-id="style-p-59" aria-label="Bild 4 anzeigen" type="button" />
              </div>
            </section>
          </section>
          <section className="box-content block py-10 px-[4.9rem] max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-p-17" id="Anreise">
            <figure className="box-content w-41 block float-right ml-[1.325rem] pl-12.5 text-sm leading-[1.3125rem] max-md:w-[9.5625rem] max-md:ml-[1.225rem] max-lg:[font-size:inherit] max-lg:leading-[inherit] md:max-lg:ml-[20.3px] 2xl:w-43.5 2xl:ml-[22.3px] 2xl:text-[0.9375rem] 2xl:leading-[1.375rem]" data-ditto-id="style-p-84">
              <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-p-90" data-component="link" href="https://static.integrata-cegos.de/wp-content/uploads/2024/08/01085344/2024_08_01_Cegos-Integrata_Standort-Duesseldorf_QR-Code.png">
                <picture className="box-content w-37.5 inline" data-ditto-id="style-p-85">
                  <source className="box-content inline" data-ditto-id="style-p-86" sizes="auto" srcSet="/assets/cloned/images/4ee0ecc57faf.webp 500w, /assets/cloned/images/b27a8dc9336f.webp 320w" type="image/webp" />
                  <img className="box-content w-37.5 inline max-w-full rounded-[10px] overflow-clip aspect-[auto_500/500] align-bottom h-auto" data-ditto-id="style-p-18" data-component="image" alt="Ein QR-Code des Cegos Integrata Standorts Düsseldorf, der Google Maps öffnet." height="500" sizes="auto" src="/assets/cloned/images/5643f900054a.png" srcSet="/assets/cloned/images/5643f900054a.png 500w, /assets/cloned/images/0729b3372926.png 320w" width="500" />
                </picture>
              </a>
              <figcaption className="box-content block" data-ditto-id="style-p-63">
                QRCode für Googlemaps
                <br className="box-content inline" data-ditto-id="style-strong-7" />
                <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-br-32" data-component="link" href="https://www.google.de/maps/place/Grafenberger+Allee+293,+40237+D%C3%BCsseldorf/@51.2353887,6.8179061,686m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b8c96321a158b5:0x2f06e5ae4443e4b2!8m2!3d51.2353854!4d6.820481!16s%2Fg%2F11bw3xvk8g?entry=ttu" rel="noreferrer noopener" target="_blank">
                  Karte öffnen
                </a>
              </figcaption>
            </figure>
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-br-7" data-component="heading">
              Anreise zum Trainingszentrum Düsseldorf
            </h2>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-64">
              {"Das Trainingszentrum Düsseldorf befindet sich in der "}
              <strong className="box-content inline font-bold" data-ditto-id="style-strong-8">
                Grafenberger Allee 293, 40237 Düsseldorf
              </strong>
              {" und ist sowohl mit dem Auto als auch bequem mit öffentlichen Verkehrsmitteln oder vom Flughafen aus erreichbar."}
            </p>
            <h3 className="box-content block mb-2.5 text-xl font-bold leading-[1.5625rem] max-lg:text-base max-lg:leading-5" data-ditto-id="style-br-21" data-component="heading">
              Anreise mit dem Auto und Parken in Düsseldorf
            </h3>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-19">
              {"Nutzen Sie bitte die "}
              <strong className="box-content inline font-bold" data-ditto-id="style-strong-17">
                kostenfreien Parkmöglichkeiten in den umliegenden Straßen
              </strong>
              {" rund um das Trainingszentrum."}
            </p>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-br-22">
              <strong className="box-content inline font-bold" data-ditto-id="style-p-34">
                Bitte beachten Sie:
              </strong>
            </p>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-35">
              {"Die Düsseldorfer Innenstadt ist "}
              <strong className="box-content inline font-bold" data-ditto-id="style-p-20">
                Umweltzone
              </strong>
              {". Für die Durchfahrt benötigen Fahrzeuge eine gültige Umweltplakette. Diese erhalten Sie unter anderem bei den Niederlassungen von "}
              <strong className="box-content inline font-bold" data-ditto-id="style-strong-38">
                TÜV
              </strong>
              {", "}
              <strong className="box-content inline font-bold" data-ditto-id="style-link-21">
                DEKRA
              </strong>
              {" sowie bei den Automobilclubs."}
            </p>
            <h3 className="box-content block mb-2.5 text-xl font-bold leading-[1.5625rem] max-lg:text-base max-lg:leading-5" data-ditto-id="style-agb-is" data-component="heading">
              Anreise mit Bahn und Straßenbahn zum Trainingszentrum Düsseldorf
            </h3>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-hr">
              {"Vom "}
              <strong className="box-content inline font-bold" data-ditto-id="style-p-65">
                Düsseldorfer Hauptbahnhof
              </strong>
              {" erreichen Sie das Trainingszentrum mit dem Taxi in etwa 15 Minuten. Alternativ fahren Sie mit der Straßenbahnlinie 709 Richtung Grafenberg bis zur Haltestelle Schlüterstraße/Arbeitsagentur. Die Fahrt dauert rund 12 Minuten. Von der Haltestelle aus gelangen Sie nach etwa 2 Gehminuten zur Grafenberger Allee 293. Das Trainingszentrum befindet sich direkt gegenüber der Haltestelle. Weitere Informationen zu Fahrplänen und Verbindungen finden Sie beim "}
              <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-heading-4" data-component="link" href="https://www.vrr.de/de/" rel="noreferrer noopener" target="_blank">
                Verkehrsverbund Rhein-Ruhr (VRR)
              </a>
              .
            </p>
            <h3 className="box-content block mb-2.5 text-xl font-bold leading-[1.5625rem] max-lg:text-base max-lg:leading-5" data-ditto-id="style-p-66" data-component="heading">
              Anreise vom Flughafen Düsseldorf zum Trainingszentrum
            </h3>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-strong-9">
              {"Vom "}
              <strong className="box-content inline font-bold" data-ditto-id="style-br-33">
                Flughafen Düsseldorf
              </strong>
              {" erreichen Sie das Trainingszentrum mit dem Taxi in etwa 20 Minuten. Mit öffentlichen Verkehrsmitteln fahren Sie zunächst mit der S-Bahnlinie S1 oder S11 in Richtung Düsseldorf Hauptbahnhof. Die Fahrt dauert rund 17 Minuten. Anschließend steigen Sie in die Straßenbahnlinie 709 Richtung Grafenberg um und fahren bis zur Haltestelle Schlüterstraße/Arbeitsagentur. Von dort sind es nur etwa 2 Gehminuten bis zum Trainingszentrum in der Grafenberger Allee 293, das sich direkt gegenüber der Haltestelle befindet. Weitere Informationen zur Anreise finden Sie auf der "}
              <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-p-117" data-component="link" href="https://www.dus.com/" rel="noreferrer noopener" target="_blank">
                Website des Flughafens Düsseldorf
              </a>
              .
            </p>
            <div className="box-content block overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif]" data-ditto-id="style-p-67">
              <div className="grid rounded-[10px] overflow-hidden grid-cols-2 max-md:grid-cols-1" data-ditto-id="style-p-118">
                <div className="block p-12.5 bg-surface max-md:p-[31.3px] max-md:rounded-tl-[10px] max-md:rounded-tr-[10px]" data-ditto-id="style-p-41">
                  <h2 className="block my-7.5 [font-family:Ryker,_sans-serif,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-strong-18" data-component="heading">
                    Aktuelle Seminartermine in Düsseldorf – Garantietermine und Verfügbarkeit
                  </h2>
                  <p className="block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-br-8">
                    {"Eine aktuelle Übersicht aller Weiterbildungen am Standort Düsseldorf finden Sie in unserem Seminarkalender. Viele Termine sind als "}
                    <a className="inline text-primary cursor-pointer" data-ditto-id="style-p-114" data-component="link" href="/weiterbildung-mit-integrata-cegos/702010-wie-wir-lernen">
                      Garantietermine
                    </a>
                    {" ausgeschrieben, was bedeutet, das Seminar findet auch bei nur einem Teilnehmenden statt. Je nach Thema wechseln sich Präsenztermine in Düsseldorf mit Live-Online-Formaten ab; Sie wählen das Format, das zu Ihrer Arbeitsweise passt."}
                  </p>
                  <a className="border border-solid border-clr-0 inline-flex py-[0.5625rem] px-4.5 rounded-[40px] justify-center items-center text-background font-semibold leading-[1.125rem] bg-foreground cursor-pointer max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-p-68" data-component="link" href="https://www.cegos-integrata.de/standorte/duesseldorf/calendar-duesseldorf">
                    Alle Seminartermine in Düsseldorf ansehen
                  </a>
                </div>
                <div className="block relative" data-ditto-id="style-p-42">
                  <picture className="inline" data-ditto-id="style-p-36">
                    <source className="inline" data-ditto-id="style-p-37" srcSet="/assets/cloned/images/11f5edc80346.webp 1919w, /assets/cloned/images/322475d7ea1d.webp 1600w, /assets/cloned/images/a2d92271cfb6.webp 1366w, /assets/cloned/images/c9adb928ada8.webp 1024w, /assets/cloned/images/036f09ea2899.webp 768w, /assets/cloned/images/02b123b0921d.webp 640w, /assets/cloned/images/60d1293978fc.webp 320w" type="image/webp" />
                    <img className="w-full h-[25.5625rem] inline max-w-full rounded-[10px] overflow-clip object-cover align-bottom max-md:h-[13.9375rem] max-md:rounded-tl-[initial] max-md:rounded-tr-[initial] md:max-lg:h-[35.4375rem]" data-ditto-id="style-p-21" data-component="image" src="/assets/cloned/images/ec30f0b171e6.jpg" />
                  </picture>
                </div>
              </div>
            </div>
          </section>
          <section className="box-content block py-10 px-[4.9rem] text-background bg-color-015 bg-contain bg-no-repeat max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" style={{ backgroundImage: "url(\"/assets/cloned/images/469dfcc984ef.webp\")" }} data-ditto-id="style-strong-25" id="FAQ">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-br-9" data-component="heading">
              Häufige Fragen zu Seminaren in Düsseldorf(FAQ)
            </h2>
            <details className="box-content block" data-ditto-id="style-p-38">
              <summary className="box-content list-item list-inside" data-ditto-id="style-p-22">
                <h2 className="box-content inline [font-family:Ryker,_sans-serif] text-xl font-bold leading-[1.8125rem]" data-ditto-id="style-strong-26" data-component="heading">
                  Welche Themen werden vor Ort im Trainingszentrum Düsseldorf angeboten?
                </h2>
              </summary>
              {" Das Portfolio in Düsseldorf umfasst vier große Themenfelder: klassisches und agiles Projektmanagement, Rhetorik und Präsentation, IT-Schulungen samt Excel- und KI-Trainings sowie das gesamte Spektrum an Soft-Skills- und Leadership-Themen."}
            </details>
            <br className="box-content inline" data-ditto-id="style-br-10" />
            <details className="box-content block" data-ditto-id="style-p-69">
              <summary className="box-content list-item list-inside" data-ditto-id="style-p-115">
                <h2 className="box-content inline [font-family:Ryker,_sans-serif] text-xl font-bold leading-[1.8125rem]" data-ditto-id="style-p-70" data-component="heading">
                  Gibt es Parkmöglichkeiten am Cegos Trainingszentrum Düsseldorf?
                </h2>
              </summary>
              {" Parken ist kostenfrei in den umliegenden Straßen rund um die Grafenberger Allee möglich."}
            </details>
            <br className="box-content inline" data-ditto-id="style-p-116" />
            <details className="box-content block" data-ditto-id="style-p-43">
              <summary className="box-content list-item list-inside" data-ditto-id="style-strong-39">
                <h2 className="box-content inline [font-family:Ryker,_sans-serif] text-xl font-bold leading-[1.8125rem]" data-ditto-id="style-br-23" data-component="heading">
                  Kann ich Seminarräume im Trainingszentrum Düsseldorf mieten?
                </h2>
              </summary>
              {" Ja. Externe Trainer:innen, Coaches und Unternehmen können einzelne Räume oder das gesamte Trainingszentrum für Workshops, Off-Sites oder eigene Schulungen buchen. Informationen, Ausstattung und Konditionen finden Sie auf unserer Seite zur "}
              <span className="box-content inline text-clr-24" data-ditto-id="style-br-34">
                <a className="box-content inline text-color-031 cursor-pointer" data-ditto-id="style-p-44" data-component="link" href="/standorte/duesseldorf">
                  Raumvermietung
                </a>
              </span>
              .
            </details>
            <br className="box-content inline" data-ditto-id="style-p-71" />
            <details className="box-content block" data-ditto-id="style-strong-20">
              <summary className="box-content list-item list-inside" data-ditto-id="style-br-35">
                <h2 className="box-content inline [font-family:Ryker,_sans-serif] text-xl font-bold leading-[1.8125rem]" data-ditto-id="style-p-45" data-component="heading">
                  Bietet Cegos Integrata auch Live-Online-Seminare aus Düsseldorf an?
                </h2>
              </summary>
              {" Ja – ein Großteil unserer Seminare ist auch im Live-Online-Format buchbar. Eine vollständige Übersicht finden Sie unter "}
              <a className="box-content inline cursor-pointer" data-ditto-id="style-p-72" data-component="link" href="/seminarangebot">
                <span className="box-content inline text-color-031" data-ditto-id="style-p-46">
                  Seminarangebot
                </span>
              </a>
              {" und "}
              <a className="box-content inline cursor-pointer" data-ditto-id="style-p-73" data-component="link" href="/digitales-lernen/online-seminare">
                <span className="box-content inline text-color-031" data-ditto-id="style-p-47">
                  Online-Seminare
                </span>
              </a>
              .
            </details>
          </section>
          <section className="box-content block py-10 px-[4.9rem] max-lg:px-5 2xl:px-[377.5px] after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-p-91" id="Kontakt">
            <h2 className="box-content block my-7.5 [font-family:Ryker,_sans-serif] text-2xl font-bold leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-p-125" data-component="heading">
              Trainingszentrum Düsseldorf– Kontakt
            </h2>
            <h3 className="box-content block mb-2.5 text-xl font-bold leading-[1.5625rem] max-lg:text-base max-lg:leading-5" data-ditto-id="style-p-136" data-component="heading">
              <strong className="box-content inline font-black" data-ditto-id="style-strong-40">
                Cegos Integrata GmbH
              </strong>
            </h3>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-br-24">
              <strong className="box-content inline font-bold" data-ditto-id="style-p-74">
                Trainingszentrum Düsseldorf
                <br className="box-content inline" data-ditto-id="style-p-48" />
                {"Global Gate "}
              </strong>
              <br className="box-content inline" data-ditto-id="style-p-92" />
              <strong className="box-content inline font-bold" data-ditto-id="style-p-49">
                Grafenberger Allee 293
              </strong>
              <br className="box-content inline" data-ditto-id="style-p-93" />
              <strong className="box-content inline font-bold" data-ditto-id="style-p-50">
                40237 Düsseldorf
              </strong>
            </p>
            <p className="box-content block mb-5 max-md:mb-[16.3px] md:max-lg:mb-[1.125rem]" data-ditto-id="style-p-75">
              <strong className="box-content inline font-bold" data-ditto-id="style-p-51">
                Seminarmanagement und -service
              </strong>
              <br className="box-content inline" data-ditto-id="style-p-76" />
              Tel: +49 711 225574 - 0
              <br className="box-content inline" data-ditto-id="style-p-52" />
              <a className="box-content inline text-primary cursor-pointer" data-ditto-id="style-strong-27" data-component="link" href="mailto:seminarmanagement@cegos.de">
                seminarmanagement@cegos.de
              </a>
            </p>
            <div className="box-content block overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif]" data-ditto-id="style-br-25">
              <a className="flex relative rounded-[10px] justify-center items-center text-primary bg-surface cursor-pointer h-[7.8125rem] w-full max-md:overflow-hidden max-md:h-auto" data-ditto-id="style-p-77" data-component="link" href="/kontakt" target="_self">
                <div className="h-full block absolute top-0 left-0 min-w-0 rounded-tl-[10px] rounded-bl-[10px] bg-contain bg-no-repeat pointer-events-none w-[15.5rem] max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/images/1cf93b7ec097.webp\")" }} data-ditto-id="style-p-119" />
                <div className="h-full block absolute top-0 right-0 min-w-0 rounded-tr-[10px] rounded-br-[10px] bg-contain bg-no-repeat pointer-events-none w-[15.5rem] max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/images/590d03d74cc0.webp\")" }} data-ditto-id="style-p-134" />
                <div className="block relative z-1 px-25 text-center w-full max-md:px-5" data-ditto-id="style-strong-29">
                  <span className="block text-foreground [font-family:Ryker,_sans-serif] text-2xl leading-[2.1875rem] max-md:text-[1.0625rem] max-md:leading-[1.5625rem] md:max-lg:text-[1.3125rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-br-26">
                    Wir beraten Sie gerne!
                  </span>
                  <span className="border border-solid border-clr-0 inline-flex mt-4 py-[0.5625rem] px-4.5 rounded-[40px] justify-center items-center text-background font-semibold leading-[1.125rem] bg-foreground max-md:leading-[1rem] md:max-lg:leading-[1.0625rem]" data-ditto-id="style-p-133">
                    {"Nehmen Sie Kontakt zu uns auf "}
                  </span>
                </div>
              </a>
            </div>
          </section>
        </main>
        <footer className="box-content block overflow-x-hidden overflow-y-auto [font-family:Raleway,_sans-serif,_sans-serif] text-xs leading-4 w-full" data-ditto-id="style-p-53" role="complementary">
          <section className="block text-background bg-foreground bg-contain [background-position:100%_0px] bg-no-repeat w-full after:content-[''] after:table after:w-0 after:h-0" style={{ backgroundImage: "url(\"/assets/cloned/images/2e795d11ad63.webp\")" }} data-ditto-id="style-strong-50">
            <div className="block max-w-285 mx-auto py-7.5 px-4" data-ditto-id="style-br-27">
              <div className="grid mb-8 gap-8 grid-cols-2 max-md:grid-cols-1" data-ditto-id="style-br-41">
                <div className="block" data-ditto-id="style-p-54">
                  <a className="inline cursor-pointer" data-ditto-id="style-br-42" data-component="link" href="https://www.cegos-integrata.de/ihre-vorteile/service-fuer-teilnehmer/zertifizierungen">
                    <h4 className="block mb-4 text-base font-bold leading-5 max-md:text-sm max-md:leading-[1.125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.1875rem]" data-ditto-id="style-p-55" data-component="heading">
                      Unsere Zertifizierungen
                    </h4>
                    <img className="w-27 h-27 inline max-w-full rounded-[10px] overflow-clip align-bottom" data-ditto-id="style-br-43" data-component="image" alt="footer certifications" src="/assets/cloned/images/c14fab4c87cc.png" />
                  </a>
                </div>
                <div className="block" data-ditto-id="style-p-124">
                  <h4 className="block mb-4 text-base font-bold leading-5 max-md:text-sm max-md:leading-[1.125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.1875rem]" data-ditto-id="style-p-94" data-component="heading">
                    Folgen Sie uns
                  </h4>
                  <ul className="flex gap-4 leading-4.5 [list-style-type:none] list-outside" data-ditto-id="style-link-22">
                    {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
                  </ul>
                </div>
              </div>
              <div className="grid mb-8 gap-6 grid-cols-4 max-md:grid-cols-1" data-ditto-id="style-link-25">
                <div className="block" data-ditto-id="style-image">
                  <h4 className="block mb-3 text-base font-bold leading-5 max-md:text-sm max-md:leading-[1.125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.1875rem]" data-ditto-id="style-span-2" data-component="heading">
                    Top Themen
                  </h4>
                  <ul className="block leading-4.5 [list-style-type:none] list-outside" data-ditto-id="style-span-5">
                    {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
                  </ul>
                </div>
                <div className="block" data-ditto-id="style-source-4">
                  <h4 className="block mb-3 text-base font-bold leading-5 max-md:text-sm max-md:leading-[1.125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.1875rem]" data-ditto-id="style-image-3" data-component="heading">
                    Unser Angebot
                  </h4>
                  <ul className="block leading-4.5 [list-style-type:none] list-outside" data-ditto-id="style-heading-10">
                    {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
                  </ul>
                </div>
                <div className="block" data-ditto-id="style-ul-9">
                  <h4 className="block mb-3 text-base font-bold leading-5 max-md:text-sm max-md:leading-[1.125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.1875rem]" data-ditto-id="style-link-27" data-component="heading">
                    Über uns
                  </h4>
                  <ul className="block leading-4.5 [list-style-type:none] list-outside" data-ditto-id="style-link-35">
                    {ListRow3_data2.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles2[i]} />)}
                  </ul>
                </div>
                <div className="block" data-ditto-id="style-link-28">
                  <h4 className="block mb-3 text-base font-bold leading-5 max-md:text-sm max-md:leading-[1.125rem] md:max-lg:text-[0.9375rem] md:max-lg:leading-[1.1875rem]" data-ditto-id="style-div-21" data-component="heading">
                    Informationen
                  </h4>
                  <ul className="block leading-4.5 [list-style-type:none] list-outside" data-ditto-id="style-heading-12">
                    {ListRow3_data3.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles3[i]} />)}
                  </ul>
                </div>
              </div>
              <div className="block text-right" data-ditto-id="style-ul-7">
                <span className="inline font-bold" data-ditto-id="style-div-24">
                  Beyond knowledge
                </span>
              </div>
            </div>
          </section>
          <section className="block font-bold bg-background w-full after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-heading-13">
            <div className="block max-w-285 mx-auto py-[0.9375rem] px-4" data-ditto-id="style-ul-11">
              <div className="flex justify-between items-center" data-ditto-id="style-image-7">
                <div className="flex items-center gap-3" data-ditto-id="style-div-6">
                  <a className="h-10 flex items-center gap-2 cursor-pointer" data-ditto-id="style-div-20" data-component="link" href="/">
                    <img className="block max-w-full rounded-[10px] overflow-clip align-bottom w-10 h-10" data-ditto-id="style-heading-2" data-component="image" alt="Cegos" src="/assets/cloned/images/65fa0671b460.webp" />
                    <span className="block" data-ditto-id="style-ul-10">
                      Integrata
                    </span>
                  </a>
                  <span className="block" data-ditto-id="style-icon">
                    © 2026 CEGOS.
                  </span>
                </div>
                <ul className="flex items-center gap-4 leading-4.5 [list-style-type:none] list-outside max-md:flex-col max-md:items-end max-md:gap-1" data-ditto-id="style-div-25">
                  {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} />)}
                </ul>
              </div>
            </div>
          </section>
        </footer>
      </div>
    </>
  );
}
