import "./ditto.css";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import MediaTile from "./components/media-tile";
import Logo from "./components/logo";
import Logo2 from "./components/logo2";
import Logo3 from "./components/logo3";
import Logo4 from "./components/logo4";
import Logo5 from "./components/logo5";
import Logo6 from "./components/logo6";
import Logo7 from "./components/logo7";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { description: "2" },
    { description: "slots left for" },
    { description: "September" }
];
const Tile2_data = [
    { href: "/", description: "Home" },
    { href: "/work", kind: "link", description: "Work" },
    { href: "/pricing", kind: "link", description: "Pricing" },
    { href: "/contact", description: "Get started" }
];
const MediaTile_data = [
    { imgSrc: "/assets/cloned/images/519eaf75b354.jpg", srcSet: "/assets/cloned/images/b6289807f834.jpg 512w, /assets/cloned/images/cca000aa0eb8.jpg 1024w, /assets/cloned/images/519eaf75b354.jpg 1920w", description: "Lovable", height: "1345", imgSrc2: "/assets/cloned/images/519eaf75b354.jpg", srcSet2: "/assets/cloned/images/b6289807f834.jpg 512w, /assets/cloned/images/cca000aa0eb8.jpg 1024w, /assets/cloned/images/519eaf75b354.jpg 1920w", width: "1920" },
    { imgSrc: "/assets/cloned/images/02d028572e2e.jpg", srcSet: "/assets/cloned/images/cec366178da7.jpg 512w, /assets/cloned/images/a35ceef09e14.jpg 1024w, /assets/cloned/images/02d028572e2e.jpg 1920w", description: "Craft", height: "1371", imgSrc2: "/assets/cloned/images/02d028572e2e.jpg", srcSet2: "/assets/cloned/images/cec366178da7.jpg 512w, /assets/cloned/images/a35ceef09e14.jpg 1024w, /assets/cloned/images/02d028572e2e.jpg 1920w", width: "1920" },
    { imgSrc: "/assets/cloned/images/f59402d7eff7.jpg", srcSet: "/assets/cloned/images/5aee86c2fc22.jpg 512w, /assets/cloned/images/84c812beacb1.jpg 1024w, /assets/cloned/images/f59402d7eff7.jpg 1920w", description: "Loti", height: "1345", imgSrc2: "/assets/cloned/images/f59402d7eff7.jpg", srcSet2: "/assets/cloned/images/5aee86c2fc22.jpg 512w, /assets/cloned/images/84c812beacb1.jpg 1024w, /assets/cloned/images/f59402d7eff7.jpg 1920w", width: "1920" },
    { imgSrc: "/assets/cloned/images/bfd8f1c778ba.jpg", srcSet: "/assets/cloned/images/194695e6bad2.jpg 512w, /assets/cloned/images/beaab86e8b7a.jpg 1024w, /assets/cloned/images/bfd8f1c778ba.jpg 1920w", description: "Gist", height: "1346", imgSrc2: "/assets/cloned/images/bfd8f1c778ba.jpg", srcSet2: "/assets/cloned/images/194695e6bad2.jpg 512w, /assets/cloned/images/beaab86e8b7a.jpg 1024w, /assets/cloned/images/bfd8f1c778ba.jpg 1920w", width: "1920" },
    { imgSrc: "/assets/cloned/images/ea17727dfc4f.jpg", srcSet: "/assets/cloned/images/f3db071021c1.jpg 512w, /assets/cloned/images/ea17727dfc4f.jpg 700w", description: "Heron", height: "500", imgSrc2: "/assets/cloned/images/ea17727dfc4f.jpg", srcSet2: "/assets/cloned/images/f3db071021c1.jpg 512w, /assets/cloned/images/ea17727dfc4f.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/71b3693a822d.jpg", srcSet: "/assets/cloned/images/ac68bee93e85.jpg 512w, /assets/cloned/images/9aa147140bd7.jpg 1024w, /assets/cloned/images/71b3693a822d.jpg 1921w", description: "Paper", height: "1346", imgSrc2: "/assets/cloned/images/71b3693a822d.jpg", srcSet2: "/assets/cloned/images/ac68bee93e85.jpg 512w, /assets/cloned/images/9aa147140bd7.jpg 1024w, /assets/cloned/images/71b3693a822d.jpg 1921w", width: "1921" },
    { imgSrc: "/assets/cloned/images/c4b6ba16cbea.jpg", srcSet: "/assets/cloned/images/7046c7b20ee5.jpg 512w, /assets/cloned/images/c4b6ba16cbea.jpg 700w", description: "Titan", height: "500", imgSrc2: "/assets/cloned/images/c4b6ba16cbea.jpg", srcSet2: "/assets/cloned/images/7046c7b20ee5.jpg 512w, /assets/cloned/images/c4b6ba16cbea.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/3cca1c9a4f73.jpg", srcSet: "/assets/cloned/images/083b9f3d6ebb.jpg 512w, /assets/cloned/images/773760323b48.jpg 1024w, /assets/cloned/images/3cca1c9a4f73.jpg 1921w", description: "Frame", height: "1371", imgSrc2: "/assets/cloned/images/3cca1c9a4f73.jpg", srcSet2: "/assets/cloned/images/083b9f3d6ebb.jpg 512w, /assets/cloned/images/773760323b48.jpg 1024w, /assets/cloned/images/3cca1c9a4f73.jpg 1921w", width: "1921" },
    { imgSrc: "/assets/cloned/images/d61fb9cc5fe8.jpg", srcSet: "/assets/cloned/images/b5c36a8900f0.jpg 512w, /assets/cloned/images/5f9c8e5453de.jpg 1024w, /assets/cloned/images/d61fb9cc5fe8.jpg 1921w", description: "Alan", height: "1372", imgSrc2: "/assets/cloned/images/d61fb9cc5fe8.jpg", srcSet2: "/assets/cloned/images/b5c36a8900f0.jpg 512w, /assets/cloned/images/5f9c8e5453de.jpg 1024w, /assets/cloned/images/d61fb9cc5fe8.jpg 1921w", width: "1921" },
    { imgSrc: "/assets/cloned/images/324408e921eb.jpg", srcSet: "/assets/cloned/images/728f9993ddf1.jpg 512w, /assets/cloned/images/324408e921eb.jpg 700w", description: "Vagus", height: "500", imgSrc2: "/assets/cloned/images/324408e921eb.jpg", srcSet2: "/assets/cloned/images/728f9993ddf1.jpg 512w, /assets/cloned/images/324408e921eb.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/0b636f0945c8.jpg", srcSet: "/assets/cloned/images/30e4025f7ef4.jpg 512w, /assets/cloned/images/0b636f0945c8.jpg 700w", description: "Incentiv", height: "500", imgSrc2: "/assets/cloned/images/0b636f0945c8.jpg", srcSet2: "/assets/cloned/images/30e4025f7ef4.jpg 512w, /assets/cloned/images/0b636f0945c8.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/f6a43ca670b3.jpg", srcSet: "/assets/cloned/images/8b67da82d905.jpg 512w, /assets/cloned/images/f6a43ca670b3.jpg 700w", description: "Rebel", height: "500", imgSrc2: "/assets/cloned/images/f6a43ca670b3.jpg", srcSet2: "/assets/cloned/images/8b67da82d905.jpg 512w, /assets/cloned/images/f6a43ca670b3.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/19e4418b7f7f.jpg", srcSet: "/assets/cloned/images/288529cba938.jpg 512w, /assets/cloned/images/19e4418b7f7f.jpg 700w", description: "Longe", height: "500", imgSrc2: "/assets/cloned/images/19e4418b7f7f.jpg", srcSet2: "/assets/cloned/images/288529cba938.jpg 512w, /assets/cloned/images/19e4418b7f7f.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/d8901ebd820f.jpg", srcSet: "/assets/cloned/images/be94c19d4c52.jpg 512w, /assets/cloned/images/d8901ebd820f.jpg 700w", description: "Stellar", height: "500", imgSrc2: "/assets/cloned/images/d8901ebd820f.jpg", srcSet2: "/assets/cloned/images/be94c19d4c52.jpg 512w, /assets/cloned/images/d8901ebd820f.jpg 700w", width: "700" },
    { imgSrc: "/assets/cloned/images/c3aecf23977a.jpg", srcSet: "/assets/cloned/images/1a10b168c16d.jpg 512w, /assets/cloned/images/c3aecf23977a.jpg 700w", description: "SliceSpace", height: "500", imgSrc2: "/assets/cloned/images/c3aecf23977a.jpg", srcSet2: "/assets/cloned/images/1a10b168c16d.jpg 512w, /assets/cloned/images/c3aecf23977a.jpg 700w", width: "700" }
];
const Logo_data = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo2_data = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo2_data2 = [
    {  },
    {  },
    {  }
];
const Logo3_data = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo4_data = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo5_data = [
    { icon: <>
                <use href="#svg3861013906" />
                </>, icon2: <>
                <use href="#svg3861013906" />
                </>, icon3: <>
                <use href="#svg3861013906" />
                </>, icon4: <>
                <use href="#svg3861013906" />
                </>, icon5: <>
                <use href="#svg3861013906" />
                </>, icon6: <>
                <use href="#svg3861013906" />
                </>, icon7: <>
                <use href="#svg3861013906" />
                </>, icon8: <>
                <use href="#svg3861013906" />
                </>, icon9: <>
                <use href="#svg3861013906" />
                </>, icon10: <>
                <use href="#svg3861013906" />
                </>, icon11: <>
                <use href="#svg3861013906" />
                </>, icon12: <>
                <use href="#svg3861013906" />
                </> },
    { icon: <>
                <use href="#svg3038929338" />
                </>, icon2: <>
                <use href="#svg3038929338" />
                </>, icon3: <>
                <use href="#svg3038929338" />
                </>, icon4: <>
                <use href="#svg3038929338" />
                </>, icon5: <>
                <use href="#svg3038929338" />
                </>, icon6: <>
                <use href="#svg3038929338" />
                </>, icon7: <>
                <use href="#svg3038929338" />
                </>, icon8: <>
                <use href="#svg3038929338" />
                </>, icon9: <>
                <use href="#svg3038929338" />
                </>, icon10: <>
                <use href="#svg3038929338" />
                </>, icon11: <>
                <use href="#svg3038929338" />
                </>, icon12: <>
                <use href="#svg3038929338" />
                </> },
    { icon: <>
                <use href="#svg155221230" />
                </>, icon2: <>
                <use href="#svg155221230" />
                </>, icon3: <>
                <use href="#svg155221230" />
                </>, icon4: <>
                <use href="#svg155221230" />
                </>, icon5: <>
                <use href="#svg155221230" />
                </>, icon6: <>
                <use href="#svg155221230" />
                </>, icon7: <>
                <use href="#svg155221230" />
                </>, icon8: <>
                <use href="#svg155221230" />
                </>, icon9: <>
                <use href="#svg155221230" />
                </>, icon10: <>
                <use href="#svg155221230" />
                </>, icon11: <>
                <use href="#svg155221230" />
                </>, icon12: <>
                <use href="#svg155221230" />
                </> },
    { icon: <>
                <use href="#svg2218268641" />
                </>, icon2: <>
                <use href="#svg2218268641" />
                </>, icon3: <>
                <use href="#svg2218268641" />
                </>, icon4: <>
                <use href="#svg2218268641" />
                </>, icon5: <>
                <use href="#svg2218268641" />
                </>, icon6: <>
                <use href="#svg2218268641" />
                </>, icon7: <>
                <use href="#svg2218268641" />
                </>, icon8: <>
                <use href="#svg2218268641" />
                </>, icon9: <>
                <use href="#svg2218268641" />
                </>, icon10: <>
                <use href="#svg2218268641" />
                </>, icon11: <>
                <use href="#svg2218268641" />
                </>, icon12: <>
                <use href="#svg2218268641" />
                </> },
    { icon: <>
                <use href="#svg3950062250" />
                </>, icon2: <>
                <use href="#svg3950062250" />
                </>, icon3: <>
                <use href="#svg3950062250" />
                </>, icon4: <>
                <use href="#svg3950062250" />
                </>, icon5: <>
                <use href="#svg3950062250" />
                </>, icon6: <>
                <use href="#svg3950062250" />
                </>, icon7: <>
                <use href="#svg3950062250" />
                </>, icon8: <>
                <use href="#svg3950062250" />
                </>, icon9: <>
                <use href="#svg3950062250" />
                </>, icon10: <>
                <use href="#svg3950062250" />
                </>, icon11: <>
                <use href="#svg3950062250" />
                </>, icon12: <>
                <use href="#svg3950062250" />
                </> }
];
const Logo4_data2 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo6_data = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo7_data = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo_data2 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo2_data3 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo3_data2 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo4_data3 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo6_data2 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Logo7_data2 = [
    {  },
    {  },
    {  },
    {  }
];
const Logo7_data3 = [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  }
];
const Tile_meta: string[][] = [
    ["n21", "n22"],
    ["n23", "n24"],
    ["n25", "n26"]
];
const Tile2_meta: string[][] = [
    ["n32", "n33", "n34", "n35"],
    ["n36", "n37", "n38", "n39"],
    ["n40", "n41", "n42", "n43"],
    ["n44", "n45", "n46", "n47"]
];
const MediaTile_meta: string[][] = [
    ["n59", "n60", "n61", "n62", "n63", "n64", "n65", "n66", "style-div", "n68", "n69", "style-p", "n71", "n72", "style-overlay", "n74", "style-svg-548646222-1821"],
    ["n76", "n77", "n78", "n79", "n80", "style-textarea", "n82", "n83", "n84", "n85", "n86", "style-div-2", "n88", "n89", "n90", "n91", "n92"],
    ["n93", "n94", "n95", "n96", "n97", "n98", "n99", "n100", "n101", "n102", "n103", "n104", "n105", "n106", "n107", "n108", "n109"],
    ["n110", "n111", "n112", "n113", "n114", "n115", "n116", "n117", "n118", "n119", "n120", "n121", "n122", "n123", "n124", "n125", "n126"],
    ["n127", "n128", "n129", "n130", "n131", "n132", "n133", "n134", "n135", "n136", "n137", "n138", "n139", "n140", "n141", "n142", "n143"],
    ["n144", "n145", "n146", "n147", "n148", "n149", "n150", "n151", "n152", "n153", "n154", "n155", "n156", "n157", "n158", "n159", "n160"],
    ["n161", "n162", "n163", "n164", "n165", "n166", "n167", "n168", "n169", "n170", "n171", "n172", "n173", "n174", "n175", "n176", "n177"],
    ["n178", "n179", "n180", "n181", "n182", "n183", "n184", "n185", "n186", "n187", "n188", "n189", "n190", "n191", "n192", "n193", "n194"],
    ["n195", "n196", "n197", "n198", "n199", "n200", "n201", "n202", "style-div-63", "n204", "n205", "n206", "n207", "n208", "n209", "n210", "n211"],
    ["n212", "n213", "n214", "n215", "n216", "n217", "n218", "n219", "style-div-64", "n221", "n222", "n223", "n224", "style-section-2", "n226", "n227", "n228"],
    ["n229", "style-div-65", "n231", "n232", "n233", "n234", "style-div-66", "n236", "n237", "n238", "n239", "style-div-67", "n241", "n242", "n243", "n244", "style-div-68"],
    ["n246", "n247", "n248", "n249", "style-div-69", "n251", "n252", "n253", "n254", "style-div-70", "n256", "n257", "n258", "n259", "style-div-71", "n261", "n262"],
    ["n263", "n264", "style-p-2", "n266", "n267", "n268", "n269", "style-div-72", "n271", "n272", "n273", "n274", "style-div-73", "n276", "n277", "n278", "n279"],
    ["n280", "style-journey", "n282", "n283", "n284", "n285", "style-div-74", "n287", "n288", "n289", "n290", "style-div-75", "n292", "n293", "n294", "n295", "style-div-76"],
    ["n297", "n298", "n299", "n300", "style-div-77", "n302", "n303", "n304", "n305", "style-div-78", "n307", "n308", "n309", "n310", "style-section-3", "n312", "n313"]
];
const Logo_meta: string[][] = [
    ["style-div-34", "n337", "style-div-81", "n339", "style-li"],
    ["style-div-35", "n342", "n343", "style-img", "style-div-108"],
    ["style-div-36", "n347", "n348", "n349", "style-div-109"],
    ["style-icon-17", "n352", "n353", "n354", "style-535"],
    ["style-226", "n357", "n358", "n359", "style-div-110"],
    ["style-div-37", "n362", "n363", "n364", "style-div-111"],
    ["style-div-38", "n367", "n368", "n369", "style-div-112"],
    ["style-div-39", "n372", "n373", "n374", "style-539"],
    ["style-230", "n377", "n378", "n379", "style-540"],
    ["style-231", "n382", "n383", "n384", "style-541"],
    ["style-232", "n387", "n388", "n389", "style-542"],
    ["style-233", "n392", "n393", "n394", "style-543"]
];
const Logo2_meta: string[][] = [
    ["style-234", "n398", "n399", "n400", "style-411"],
    ["style-div-40", "n403", "n404", "n405", "style-544"],
    ["style-236", "n408", "n409", "n410", "style-545"],
    ["style-237", "n413", "n414", "n415", "style-546"],
    ["style-238", "n418", "n419", "n420", "style-547"],
    ["style-239", "n423", "n424", "n425", "style-548"],
    ["style-240", "n428", "n429", "n430", "style-549"],
    ["style-241", "n433", "n434", "n435", "style-div-113"]
];
const Logo2_meta2: string[][] = [
    ["style-242", "n445", "n446", "style-414", "style-551"],
    ["style-243", "n450", "n451", "style-415", "style-div-114"],
    ["style-div-41", "n455", "n456", "n457", "style-div-115"]
];
const Logo3_meta: string[][] = [
    ["style-br", "n473", "n474", "style-p-3", "style-span"],
    ["style-br-2", "n478", "n479", "style-div-86", "style-555"],
    ["style-248", "n483", "n484", "style-13", "style-556"],
    ["style-249", "n488", "n489", "style-14", "style-557"],
    ["style-250", "n493", "n494", "style-15", "style-558"],
    ["style-251", "n498", "n499", "style-16", "style-559"],
    ["style-252", "n503", "n504", "style-17", "style-560"],
    ["style-253", "n508", "n509", "style-18", "style-561"],
    ["style-254", "n513", "n514", "style-19", "style-562"],
    ["style-255", "n518", "n519", "style-20", "style-563"]
];
const Logo4_meta: string[][] = [
    ["style-256", "n524", "style-21", "n526", "style-564"],
    ["style-257", "n529", "style-22", "style-420", "style-565"],
    ["style-258", "n534", "style-23", "style-421", "style-566"],
    ["style-259", "n539", "style-24", "style-div-87", "style-567"],
    ["style-260", "n544", "n545", "style-25", "style-568"],
    ["style-261", "n549", "n550", "style-26", "style-569"],
    ["style-262", "n554", "n555", "style-27", "style-570"],
    ["style-263", "n559", "n560", "style-28", "style-571"],
    ["style-264", "n564", "n565", "style-29", "style-572"],
    ["style-265", "n569", "n570", "style-div-5", "style-div-116"]
];
const Logo5_meta: string[][] = [
    ["n585", "style-div-42", "n587", "n588", "n589", "style-575", "style-268", "style-423", "style-33", "n594", "style-576", "style-269", "style-424", "style-34", "n599", "style-577", "style-270", "style-425", "style-35", "n604", "style-div-118", "style-div-43", "style-div-88", "n608", "style-icon-2", "style-div-119", "style-div-44", "style-div-89", "n613", "n614", "style-div-120", "style-icon-19", "style-428", "n618", "n619", "style-581", "style-37", "style-429", "n623", "n624", "style-582", "style-38", "style-430", "n628", "n629", "style-583", "style-39", "style-431", "n633", "n634", "style-584", "style-40", "style-432", "n638", "n639", "style-585", "style-41", "style-433", "n643", "n644", "style-586"],
    ["style-42", "style-274", "n648", "n649", "n650", "style-43", "style-275", "style-434", "n654", "n655", "style-44", "style-276", "style-435", "n659", "n660", "style-45", "style-277", "style-436", "n664", "n665", "style-46", "style-div-45", "style-437", "n669", "n670", "style-587", "style-47", "style-438", "n674", "n675", "style-588", "style-48", "style-439", "n679", "n680", "style-589", "style-49", "style-440", "n684", "n685", "style-590", "style-50", "style-441", "n689", "n690", "style-591", "style-51", "style-442", "n694", "n695", "style-592", "style-52", "style-443", "n699", "n700", "style-593", "style-53", "style-444", "n704", "n705", "style-594"],
    ["style-54", "style-279", "n709", "n710", "n711", "style-55", "style-280", "style-445", "n715", "n716", "style-56", "style-div-46", "style-div-90", "n720", "n721", "style-div-121", "style-div-47", "style-icon-27", "n725", "n726", "style-div-122", "style-div-48", "style-icon-3", "n730", "n731", "style-597", "style-284", "style-448", "style-58", "n736", "style-598", "style-285", "style-449", "style-59", "n741", "style-599", "style-286", "style-450", "style-60", "n746", "style-600", "style-287", "style-451", "style-61", "n751", "style-601", "style-288", "style-452", "style-62", "n756", "style-602", "style-289", "style-453", "style-63", "n761", "style-603", "style-290", "style-454", "style-64", "n766", "style-604"],
    ["n768", "style-291", "style-div-8", "n771", "n772", "style-div-123", "style-div-49", "style-icon-4", "n776", "n777", "style-div-124", "style-div-50", "style-icon-5", "n781", "n782", "style-div-125", "style-div-51", "style-div-9", "n786", "n787", "style-608", "style-295", "style-69", "n791", "style-455", "style-609", "style-296", "n795", "style-70", "style-456", "style-610", "style-297", "n800", "style-71", "style-457", "style-611", "style-298", "n805", "style-72", "style-458", "style-612", "style-299", "n810", "style-73", "style-459", "style-613", "style-300", "n815", "style-74", "style-460", "style-614", "style-301", "n820", "style-75", "style-461", "style-615", "style-302", "n825", "style-76", "style-462", "style-616"],
    ["n829", "style-303", "style-77", "style-463", "n833", "style-617", "style-304", "style-78", "n837", "style-464", "style-618", "style-305", "style-79", "n842", "style-465", "style-619", "style-306", "style-80", "n847", "style-466", "style-620", "style-307", "style-81", "n852", "style-467", "style-621", "style-308", "n856", "style-82", "style-468", "style-622", "style-309", "n861", "style-83", "style-469", "style-623", "style-310", "n866", "style-84", "style-470", "style-624", "style-311", "n871", "style-85", "style-471", "style-625", "style-312", "n876", "style-86", "style-472", "style-626", "style-313", "n881", "style-87", "style-473", "style-627", "style-314", "n886", "style-div-10", "style-div-91", "style-div-126"]
];
const Logo4_meta2: string[][] = [
    ["style-317", "style-478", "n910", "n911", "style-93"],
    ["style-318", "style-479", "n915", "n916", "style-631"],
    ["style-94", "style-480", "n920", "n921", "style-632"],
    ["style-95", "style-481", "n925", "n926", "style-633"],
    ["style-96", "style-482", "n930", "n931", "style-634"],
    ["style-97", "style-483", "n935", "n936", "style-635"],
    ["style-98", "style-484", "n940", "n941", "style-636"],
    ["style-99", "style-485", "n945", "n946", "style-637"],
    ["style-100", "style-div-95", "n950", "n951", "style-638"]
];
const Logo6_meta: string[][] = [
    ["style-319", "n955", "n956", "n957", "style-102"],
    ["style-320", "style-487", "n961", "n962", "style-103"],
    ["style-321", "style-488", "n966", "n967", "style-104"],
    ["style-322", "style-489", "n971", "n972", "style-105"],
    ["style-323", "style-490", "n976", "n977", "style-639"],
    ["style-106", "style-491", "n981", "n982", "style-640"],
    ["style-107", "style-492", "n986", "n987", "style-641"],
    ["style-108", "style-493", "n991", "n992", "style-642"],
    ["style-109", "style-494", "n996", "n997", "style-643"],
    ["style-110", "style-495", "n1001", "n1002", "style-644"],
    ["style-111", "style-496", "n1006", "n1007", "style-div-129"],
    ["style-div-15", "n1010", "n1011", "n1012", "style-div-130"]
];
const Logo7_meta: string[][] = [
    ["style-div-52", "n1016", "style-icon-28", "n1018", "style-114"],
    ["style-325", "n1021", "n1022", "style-498", "style-115"],
    ["style-326", "n1026", "n1027", "style-499", "style-116"],
    ["style-327", "n1031", "n1032", "style-500", "style-117"],
    ["style-div-53", "n1036", "n1037", "style-div-96", "style-div-131"],
    ["style-icon-7", "n1041", "n1042", "style-div-97", "style-div-132"],
    ["style-icon-8", "n1046", "n1047", "style-div-98", "style-div-133"],
    ["style-div-54", "n1051", "n1052", "style-504", "style-650"],
    ["style-330", "n1056", "style-120", "style-505", "style-651"],
    ["style-331", "n1061", "style-121", "style-506", "style-652"],
    ["style-332", "n1066", "style-122", "style-507", "style-653"],
    ["style-333", "n1071", "style-123", "style-508", "style-654"]
];
const Logo_meta2: string[][] = [
    ["style-334", "style-124", "style-509", "n1079", "style-div-134"],
    ["style-div-55", "style-div-17", "n1083", "style-icon-29", "style-div-135"],
    ["style-div-56", "style-div-18", "n1088", "n1089", "style-div-136"],
    ["style-icon-22", "style-127", "n1093", "n1094", "style-658"],
    ["style-338", "style-128", "n1098", "n1099", "style-659"],
    ["style-339", "n1102", "style-129", "n1104", "style-660"],
    ["style-340", "n1107", "style-130", "n1109", "style-661"],
    ["style-341", "n1112", "style-131", "n1114", "style-662"],
    ["style-342", "n1117", "style-132", "n1119", "style-663"],
    ["style-343", "n1122", "style-div-19", "n1124", "style-div-137"]
];
const Logo2_meta3: string[][] = [
    ["style-344", "n1140", "style-514", "n1142", "style-137"],
    ["style-345", "n1145", "n1146", "style-515", "style-138"],
    ["style-346", "n1150", "n1151", "style-516", "style-139"],
    ["style-347", "n1155", "n1156", "style-517", "style-140"],
    ["style-div-57", "n1160", "n1161", "style-518", "style-666"],
    ["style-141", "n1165", "n1166", "style-519", "style-667"],
    ["style-142", "n1170", "n1171", "style-520", "style-668"],
    ["style-143", "n1175", "n1176", "style-521", "style-669"],
    ["style-144", "n1180", "n1181", "style-522", "style-670"],
    ["style-145", "n1185", "n1186", "style-523", "style-div-138"],
    ["style-div-21", "n1190", "n1191", "n1192", "style-div-139"],
    ["style-icon-11", "n1195", "n1196", "n1197", "style-div-140"]
];
const Logo3_meta2: string[][] = [
    ["style-350", "n1213", "style-151", "style-525", "style-674"],
    ["style-351", "n1218", "style-152", "style-div-103", "style-675"],
    ["style-352", "n1223", "n1224", "style-153", "style-676"],
    ["style-353", "n1228", "n1229", "style-154", "style-677"],
    ["style-354", "n1233", "n1234", "style-155", "style-678"],
    ["style-355", "n1238", "n1239", "style-156", "style-679"],
    ["style-356", "n1243", "n1244", "style-157", "style-680"],
    ["style-357", "n1248", "n1249", "style-158", "style-681"],
    ["style-358", "n1253", "n1254", "style-159", "style-682"],
    ["style-359", "n1258", "n1259", "style-160", "style-683"]
];
const Logo4_meta3: string[][] = [
    ["style-360", "n1264", "style-161", "n1266", "style-684"],
    ["style-361", "n1269", "style-162", "style-div-104", "style-div-141"],
    ["style-div-58", "n1274", "n1275", "style-div-105", "style-icon-31"],
    ["style-div-59", "n1279", "n1280", "style-div-106", "style-icon-12"],
    ["style-div-60", "n1284", "n1285", "style-530", "style-div-142"],
    ["style-div-25", "n1289", "n1290", "n1291", "style-div-143"],
    ["style-icon-13", "n1294", "n1295", "n1296", "style-689"],
    ["style-166", "n1299", "n1300", "n1301", "style-690"],
    ["style-167", "n1304", "n1305", "n1306", "style-div-144"]
];
const Logo6_meta2: string[][] = [
    ["style-367", "n1327", "style-172", "n1329", "style-svg-templates"],
    ["style-svg-548646222-1821-3", "n1332", "style-svg10648649387", "n1334", "style-svg2218268641"],
    ["style-svg1370478740", "n1337", "style-svg449212879", "n1339", "style-svg3038929338"],
    ["style-svg9105935482", "n1342", "style-svg1836501473", "n1344", "style-div-146"],
    ["style-div-61", "n1347", "n1348", "style-icon-14", "style-div-147"],
    ["style-div-62", "n1352", "n1353", "n1354", "style-div-148"],
    ["style-icon-26", "n1357", "n1358", "n1359", "style-700"],
    ["style-177", "n1362", "n1363", "n1364", "style-701"],
    ["style-178", "n1367", "n1368", "n1369", "style-702"],
    ["style-179", "n1372", "n1373", "n1374", "style-703"],
    ["style-180", "n1377", "n1378", "n1379", "style-704"],
    ["style-181", "n1382", "n1383", "n1384", "style-705"]
];
const Logo7_meta2: string[][] = [
    ["style-374", "n1388", "n1389", "n1390", "style-183"],
    ["style-375", "n1393", "n1394", "n1395", "style-184"],
    ["style-376", "n1398", "n1399", "n1400", "style-185"],
    ["style-377", "n1403", "n1404", "n1405", "style-div-31"]
];
const Logo7_meta3: string[][] = [
    ["style-378", "n1415", "n1416", "style-188", "n1418"],
    ["style-379", "n1420", "n1421", "style-189", "n1423"],
    ["style-380", "n1425", "n1426", "style-190", "n1428"],
    ["style-381", "n1430", "n1431", "style-191", "n1433"],
    ["style-382", "n1435", "n1436", "style-192", "n1438"],
    ["style-383", "n1440", "n1441", "style-193", "n1443"],
    ["style-384", "n1445", "n1446", "style-svg-548646222-1821-2", "n1448"]
];
const Tile_styles = [
    { className: "w-1.5" },
    { className: "w-[3.3375rem] max-lg:w-[48.3px]" },
    { className: "w-[3.3125rem]" }
];
const Tile2_styles = [
    { className: "hidden max-lg:w-[9.3625rem] max-lg:block max-lg:relative max-lg:shrink-0", className2: "hidden max-lg:flex max-lg:relative max-lg:justify-center max-lg:items-center max-lg:content-center max-lg:gap-2.5 max-lg:text-primary after:w-[9.3625rem] after:h-17 2xl:after:hidden", className3: "hidden max-lg:w-[6.8625rem] max-lg:flex max-lg:relative max-lg:flex-col max-lg:justify-start max-lg:shrink-0 max-lg:whitespace-pre max-lg:text-nowrap", className4: "hidden max-lg:block max-lg:text-color-001 max-lg:[font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] max-lg:text-left" },
    { className: "w-21.5 block relative shrink-0 max-lg:w-[8.175rem] max-lg:order-[1]", className2: "h-12 flex relative py-3 px-6 rounded-[50px] justify-center items-center content-center gap-2.5 text-primary cursor-pointer max-lg:rounded-[initial] max-lg:[cursor:inherit] after:rounded-tl-[50px] max-lg:after:rounded-tl-[initial]", className3: "w-9.5 flex relative flex-col justify-start shrink-0 whitespace-pre text-nowrap max-lg:w-[5.675rem]", className4: "block text-color-001 [font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] text-base leading-4 text-left" },
    { className: "w-25 block relative shrink-0 max-lg:w-[10.025rem] max-lg:order-[2]", className2: "h-12 flex relative py-3 px-6 rounded-[50px] justify-center items-center content-center gap-2.5 text-primary cursor-pointer max-lg:rounded-[initial] max-lg:[cursor:inherit] after:rounded-tl-[50px] max-lg:after:rounded-tl-[initial]", className3: "w-13 flex relative flex-col justify-start shrink-0 whitespace-pre text-nowrap max-lg:w-[7.525rem]", className4: "block text-color-001 [font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] text-base leading-4 text-left" },
    { className: "hidden max-lg:w-[14.825rem] max-lg:block max-lg:relative max-lg:shrink-0 max-lg:order-[3]", className2: "hidden max-lg:flex max-lg:relative max-lg:justify-center max-lg:items-center max-lg:content-center max-lg:gap-2.5 max-lg:text-primary after:w-[14.825rem] after:h-17 2xl:after:hidden", className3: "hidden max-lg:w-[12.325rem] max-lg:flex max-lg:relative max-lg:flex-col max-lg:justify-start max-lg:shrink-0 max-lg:whitespace-pre max-lg:text-nowrap", className4: "hidden max-lg:block max-lg:text-color-001 max-lg:[font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] max-lg:text-left" }
];
const MediaTile_styles = [
    { className: "max-md:h-[14.6625rem] md:max-lg:h-[509.7px]", className2: "max-md:h-[14.6875rem] md:max-lg:h-127.5", className3: "max-md:h-[14.6625rem] md:max-lg:h-[509.7px]", className4: "w-[7.35rem]", className5: "w-[4.125rem]", className6: "aspect-[auto_1920/1345]" },
    { className: "max-md:h-[239.1px] md:max-lg:h-[519.7px]", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.1px] md:max-lg:h-[519.7px]", className4: "w-[6.2625rem]", className5: "w-[48.5px]", className6: "aspect-[auto_1920/1371]" },
    { className: "max-md:h-[14.6625rem] md:max-lg:h-[509.7px]", className2: "max-md:h-[14.6875rem] md:max-lg:h-127.5", className3: "max-md:h-[14.6625rem] md:max-lg:h-[509.7px]", className4: "w-[83.5px]", className5: "w-8", className6: "aspect-[auto_1920/1345]" },
    { className: "max-md:h-[234.9px] md:max-lg:h-[510.5px]", className2: "max-md:h-[14.6875rem] md:max-lg:h-127.5", className3: "max-md:h-[234.9px] md:max-lg:h-[510.5px]", className4: "w-[86.5px]", className5: "w-[2.175rem]", className6: "aspect-[auto_1920/1346]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[6.7rem]", className5: "w-[55.5px]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[14.6625rem] md:max-lg:h-[509.7px]", className2: "max-md:h-[14.6875rem] md:max-lg:h-127.5", className3: "max-md:h-[14.6625rem] md:max-lg:h-[509.7px]", className4: "w-[6.2625rem]", className5: "w-[48.5px]", className6: "aspect-[auto_1921/1346]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[5.8875rem]", className5: "w-[42.5px]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[239.1px] md:max-lg:h-[519.7px]", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.1px] md:max-lg:h-[519.7px]", className4: "w-[6.45rem]", className5: "w-[51.5px]", className6: "aspect-[auto_1921/1371]" },
    { className: "max-md:h-[239.1px] md:max-lg:h-[519.7px]", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.1px] md:max-lg:h-[519.7px]", className4: "w-[91.5px]", className5: "w-10", className6: "aspect-[auto_1921/1372]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[6.3875rem]", className5: "w-[50.5px]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[123.3px]", className5: "w-[4.475rem]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[6.2625rem]", className5: "w-[48.5px]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[6.5125rem]", className5: "w-[52.5px]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[7.35rem]", className5: "w-[4.125rem]", className6: "aspect-[auto_700/500]" },
    { className: "max-md:h-[239.3px] md:max-lg:h-130", className2: "max-md:h-[14.9375rem] md:max-lg:h-130", className3: "max-md:h-[239.3px] md:max-lg:h-130", className4: "w-[143.7px]", className5: "w-23", className6: "aspect-[auto_700/500]" }
];

export default function Page() {
  return (
    <>
      <div className="block" id="main">
        <div className="h-1277.5 min-h-screen flex relative flex-col justify-start items-center content-center overflow-hidden bg-background max-md:h-[5052.3px] md:max-lg:h-[9397.7px] 2xl:h-1320">
          <div className="w-320 h-20 block fixed left-[clamp(187.5px,_50%,_calc(100%_-_187.5px))] z-3 min-w-0 shrink-0 transform-[matrix(1,0,0,1,-640,0)] max-md:w-[23.4375rem] max-md:transform-[matrix(1,0,0,1,-187.5,0)] md:max-lg:w-192 md:max-lg:transform-[matrix(1,0,0,1,-384,0)] 2xl:w-480 2xl:transform-[matrix(1,0,0,1,-960,0)]">
            <nav className="h-20 flex relative px-5 justify-center items-center content-center gap-5 overflow-hidden bg-background max-lg:flex-col max-lg:justify-start max-lg:px-0 max-lg:gap-[initial]" data-component="nav">
              <div className="w-full h-12 flex relative justify-center items-center content-center grow shrink-0 basis-0 gap-2.5 max-lg:h-20 max-lg:flex-col max-lg:justify-start max-lg:grow-[initial] max-lg:basis-[initial] max-lg:gap-[initial]">
                <div className="w-full h-full flex relative max-w-350 justify-between items-center content-center grow shrink-0 basis-0 max-lg:px-5 max-lg:max-w-none max-lg:grow-[initial] max-lg:basis-[initial] 2xl:w-[74.5%]" data-ditto-id="style-button">
                  <a className="w-[6.0625rem] h-[1.8125rem] block relative shrink-0 aspect-[3.34483/1] cursor-pointer" data-component="link" aria-hidden="true" href="/">
                    <div className="block aspect-[3.34483/1]">
                      <svg className="w-auto h-[1.8125rem] block overflow-hidden" data-ditto-id="style-div-3" data-component="image" height="100%" viewBox="0 0 97 29" width="100%" preserveAspectRatio="none" fill="currentColor">
                        <use href="#svg-548646222_1821" />
                      </svg>
                    </div>
                  </a>
                  <div className="w-50 h-12 flex relative justify-center items-center content-center shrink-0 gap-2.5 max-lg:w-[237.3px] max-lg:justify-end max-lg:gap-4" data-ditto-id="style-image">
                    <div className="block relative shrink-0">
                      <a className="h-12 flex relative py-1.5 pr-4 pl-1.5 rounded-[50px] justify-start items-center content-center gap-2 text-primary bg-background cursor-pointer max-lg:[cursor:inherit] after:content-[''] after:block after:absolute after:inset-0 after:h-12 after:rounded-tl-[50px]" data-component="link" href="/contact">
                        <div className="w-9 h-9 flex relative rounded-[50px] justify-center items-center content-center shrink-0 gap-2.5 bg-surface">
                          <div className="w-4 h-[1.0625rem] block relative shrink-0" aria-hidden="true">
                            <div className="h-full block">
                              <svg className="w-4 h-[1.0625rem] block overflow-hidden" data-ditto-id="style-div-4" data-component="icon" fill="currentColor">
                                <use href="#svg12505226328" />
                              </svg>
                            </div>
                          </div>
                        </div>
                        <div className="w-3/4 h-full flex relative flex-col justify-center items-center content-center grow shrink-0 basis-0 gap-1 max-lg:w-[71.5%] max-lg:items-start max-lg:content-start max-lg:grow-[initial] max-lg:basis-[initial]" data-ditto-id="style-icon">
                          <div className="w-[8.3125rem] flex relative flex-col justify-start shrink-0 whitespace-pre-wrap [word-break:break-word] [overflow-wrap:break-word] max-lg:w-11 max-lg:whitespace-pre max-lg:text-nowrap">
                            <p className="block text-color-001 [font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] text-base leading-4 text-left">
                              Reserve your spot
                            </p>
                          </div>
                          <div className="w-full flex relative justify-start items-center content-center shrink-0 gap-0.5">
                            {Tile_data.map((d, i) => <Tile key={i} d={d} styles={Tile_styles[i]} />)}
                          </div>
                        </div>
                      </a>
                    </div>
                    <div className="hidden max-lg:w-11 max-lg:h-11 max-lg:block max-lg:relative max-lg:shrink-0 max-lg:overflow-hidden max-lg:cursor-pointer">
                      <div className="hidden max-lg:w-5 max-lg:h-0.5 max-lg:block max-lg:absolute max-lg:top-[26.5px] max-lg:left-3 max-lg:shrink-0 max-lg:overflow-hidden max-lg:bg-muted-foreground" />
                      <div className="hidden max-lg:w-5 max-lg:h-0.5 max-lg:block max-lg:absolute max-lg:top-[15.5px] max-lg:left-3 max-lg:shrink-0 max-lg:overflow-hidden max-lg:bg-muted-foreground" />
                    </div>
                  </div>
                </div>
                <div className="w-69 h-12 min-h-12 flex absolute top-6 left-155 min-w-69 justify-center items-center content-center shrink-0 gap-2.5 transform-[matrix(1,0,0,1,-138,-24)] max-md:w-[23.4375rem] max-md:h-[40.6rem] max-lg:relative max-lg:inset-0 max-lg:transform-[none] max-lg:min-h-0 max-lg:min-w-0 md:max-lg:w-192 md:max-lg:h-[51.2rem] 2xl:left-235">
                  <div className="w-46.5 h-12 flex absolute top-6 left-34.5 z-1 min-w-0 justify-center items-center content-center shrink-0 transform-[matrix(1,0,0,1,-93,-24)] max-md:w-[23.4375rem] max-lg:h-68 max-lg:relative max-lg:inset-0 max-lg:px-5 max-lg:flex-col max-lg:flex-1 max-lg:transform-[none] md:max-lg:w-192">
                    {Tile2_data.map((d, i) => <Tile2 key={i} d={d} styles={Tile2_styles[i]} />)}
                  </div>
                </div>
              </div>
            </nav>
          </div>
          <div className="w-full flex relative z-2 mb-200 flex-col justify-start items-center content-center shrink-0 bg-background max-md:mb-203 md:max-lg:mb-256 2xl:mb-270">
            <section className="w-full flex relative justify-center items-center content-center shrink-0 gap-12.5 overflow-hidden bg-background">
              <div className="w-full max-w-360 flex relative pt-50 pb-25 px-5 flex-col justify-center items-center content-center grow shrink-0 basis-0 gap-2.5 overflow-hidden max-lg:pt-45 max-lg:pb-12.5">
                <div className="w-310 flex relative flex-col justify-start items-start content-start shrink-0 gap-7.5 overflow-hidden max-md:w-[20.9375rem] max-lg:gap-10 md:max-lg:w-182 2xl:w-350">
                  <div className="w-310 flex relative flex-col justify-start shrink-0 overflow-hidden whitespace-pre-wrap [word-break:break-word] [overflow-wrap:break-word] max-md:w-[20.9375rem] md:max-lg:w-182 2xl:w-350">
                    <h1 className="block text-color-001 [font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] text-[6.875rem] leading-27.5 tracking-[-4.4px] text-left max-lg:text-[3.125rem] max-lg:leading-[3.4375rem] max-lg:tracking-[-1.5px]" data-component="heading">
                      Sprints done in just two weeks
                    </h1>
                  </div>
                </div>
              </div>
            </section>
            <section className="w-full flex relative z-2 justify-center items-center content-center shrink-0 gap-25 overflow-hidden bg-background">
              <div className="w-full max-w-360 flex relative pb-12.5 px-5 flex-col justify-center items-center content-center grow shrink-0 basis-0 gap-2.5 overflow-hidden">
                <section className="w-full flex relative justify-start items-start content-start shrink-0 gap-12.5 overflow-hidden max-lg:flex-col">
                  <div className="w-310 flex relative flex-col justify-start items-start content-start grow shrink-0 basis-0 gap-7.5 overflow-hidden max-md:w-[20.9375rem] max-lg:grow-[initial] max-lg:basis-[initial] md:max-lg:w-182 2xl:w-350">
                    <div className="w-310 grid relative justify-center shrink-0 gap-5 [grid-auto-rows:minmax(0px,_1fr)] grid-cols-2 max-md:w-[20.9375rem] max-lg:flex max-lg:flex-col max-lg:justify-start max-lg:items-start max-lg:content-start max-lg:grid-cols-[repeat(2,_minmax(200px,_1fr))] md:max-lg:w-182 2xl:w-350">
                      {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
                    </div>
                  </div>
                </section>
              </div>
            </section>
          </div>
          <div className="h-full block fixed top-0 inset-x-0 z-1 min-w-0 shrink-0">
            <section className="h-full flex relative flex-col justify-center items-center content-center overflow-hidden bg-color-001">
              <div className="w-full h-full block relative z-2 shrink-0 max-lg:flex-1" data-ditto-id="style-image-3">
                <section className="h-full min-h-screen flex relative max-h-200 justify-center items-center content-center gap-25 overflow-hidden bg-color-001 max-md:max-h-203 md:max-lg:max-h-256 2xl:max-h-270">
                  <div className="w-full flex relative z-2 max-w-360 pt-50 pb-20 px-5 flex-col justify-center items-center content-center self-stretch grow shrink-0 basis-0 gap-10 overflow-hidden max-lg:pb-12.5 max-lg:max-w-none 2xl:w-3/4">
                    <a className="w-5/6 flex relative py-4 pr-9 pl-4 rounded-[999px] justify-start items-center content-center shrink-0 gap-6 text-primary bg-color-001 cursor-pointer max-lg:w-full max-lg:pt-5 max-lg:pb-7.5 max-lg:px-5 max-lg:rounded-[80px] max-lg:flex-col max-lg:gap-7.5 2xl:w-[74%] after:content-[''] after:block after:absolute after:inset-0 after:rounded-tl-[999px] max-lg:after:rounded-tl-[80px]" data-ditto-id="style-div-33" data-component="link" href="/contact">
                      <div className="w-37.5 flex relative rounded-full justify-center items-center content-center shrink-0 gap-2.5 aspect-square bg-accent max-lg:w-50 max-lg:shadow-[var(--accent)_0px_0px_80px_0px]">
                        <div className="w-17.5 h-18.5 block relative shrink-0" aria-hidden="true">
                          <div className="h-full block">
                            <svg className="w-17.5 h-18.5 block overflow-hidden" data-ditto-id="style-div-107" data-component="image" fill="currentColor">
                              <use href="#svg10648649387" />
                            </svg>
                          </div>
                        </div>
                      </div>
                      <div className="w-[809.9px] flex relative pb-1 flex-col justify-center items-start content-start shrink-0 max-lg:w-[16.25rem]">
                        <div className="w-[809.9px] flex relative flex-col justify-start shrink-0 whitespace-pre text-nowrap max-lg:w-[16.25rem]">
                          <p className="block text-color-002 [font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] text-[4.375rem] leading-17.5 tracking-[-2.45px] text-left max-lg:text-[2.5rem] max-lg:leading-10 max-lg:tracking-[-0.4px] max-lg:text-center">
                            Sprint past the competition
                            <br className="hidden max-lg:inline" />
                          </p>
                        </div>
                      </div>
                    </a>
                    <div className="w-134.5 h-10 flex relative z-1 opacity-0 flex-col justify-center items-center content-center shrink-0 gap-2.5 max-lg:w-[14.1875rem] max-lg:opacity-[initial]" data-ditto-id="style-div-79">
                      <div className="w-134.5 flex relative flex-col justify-start shrink-0 whitespace-pre text-nowrap max-lg:w-[14.1875rem]">
                        <p className="block text-color-002 [font-family:'Suisse_Int'l_Regular',_'Suisse_Int'l_Regular_Placeholder',_sans-serif] text-2xl leading-[2.125rem] text-left max-lg:text-color-001 max-lg:text-base max-lg:leading-[1.4375rem] max-lg:text-center">
                          Zero to full brand in two weeks. Let’s get to work.
                          <span className="hidden max-lg:inline max-lg:text-color-002">
                            Zero to full brand in two weeks.
                            <br className="hidden max-lg:inline" />
                            Let’s get to work.
                          </span>
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="h-200 flex absolute top-0 inset-x-0 z-1 opacity-0 min-w-0 justify-center items-center content-center shrink-0 gap-12.5 overflow-hidden bg-color-001" data-ditto-id="style-div-80">
                    <div className="basis-0 shrink-0 h-full flex relative justify-between items-center content-center grow">
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        {Logo_data.map((d, i) => <Logo key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0" data-ditto-id="style-div-82">
                        {Logo2_data.map((d, i) => <Logo2 key={i} d={d} />)}
                        <div className="w-5 h-5 block relative shrink-0" data-ditto-id="style-div-83">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 6">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" name="Glyph 6">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block" data-ditto-id="style-div-84">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg1836501473" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {Logo2_data2.map((d, i) => <Logo2 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-section">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-link" data-component="icon" fill="currentColor">
                                  <use href="#svg3950062250" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 h-5 block relative shrink-0">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 6">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" data-ditto-id="style-image-2" name="Glyph 6">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block" data-ditto-id="style-div-85">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg1836501473" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {Logo3_data.map((d, i) => <Logo3 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        {Logo4_data.map((d, i) => <Logo4 key={i} d={d} />)}
                        <div className="w-5 h-5 block relative shrink-0">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 6">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" data-ditto-id="style-div-6" name="Glyph 6">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg1836501473" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-18">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" data-ditto-id="style-div-7">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-div-117" data-component="icon" fill="currentColor">
                                  <use href="#svg449212879" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      {Logo5_data.map((d, i) => <Logo5 key={i} d={d} />)}
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-20">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" data-ditto-id="style-div-11">
                            <div className="w-5 h-full block absolute top-0 shrink-0" data-ditto-id="style-div-92" aria-hidden="true">
                              <div className="h-full block">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-div-127" data-component="icon" fill="currentColor">
                                  <use href="#svg449212879" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-21">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" data-ditto-id="style-div-12">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block" data-ditto-id="style-div-93">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-div-128" data-component="icon" fill="currentColor">
                                  <use href="#svg449212879" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 h-5 block relative shrink-0">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5" data-ditto-id="style-div-13">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 5">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" data-ditto-id="style-div-94" name="Glyph 5">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block">
                                    <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-icon-6" data-component="icon" fill="currentColor">
                                      <use href="#svg473936616" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {Logo4_data2.map((d, i) => <Logo4 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0" data-ditto-id="style-div-14">
                        {Logo6_data.map((d, i) => <Logo6 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0" data-ditto-id="style-div-16">
                        {Logo7_data.map((d, i) => <Logo7 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        {Logo_data2.map((d, i) => <Logo key={i} d={d} />)}
                        <div className="w-5 h-5 block relative shrink-0" data-ditto-id="style-div-99">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" data-ditto-id="style-icon-9" name="Glyph 4">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" name="Glyph 4">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block" data-ditto-id="style-div-100">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg2804029" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-10">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block" data-ditto-id="style-div-101">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-icon-30" data-component="icon" fill="currentColor">
                                  <use href="#svg155221230" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0" data-ditto-id="style-div-20">
                        {Logo2_data3.map((d, i) => <Logo2 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0" data-ditto-id="style-div-22">
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-23">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-div-23" data-component="icon" fill="currentColor">
                                  <use href="#svg3950062250" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 h-5 block relative shrink-0">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 4">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" name="Glyph 4">
                                <div className="w-5 h-full block absolute top-0 shrink-0" data-ditto-id="style-div-24" aria-hidden="true">
                                  <div className="h-full block" data-ditto-id="style-div-102">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg2804029" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {Logo3_data2.map((d, i) => <Logo3 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        {Logo4_data3.map((d, i) => <Logo4 key={i} d={d} />)}
                        <div className="w-5 h-5 block relative shrink-0" data-ditto-id="style-div-26">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 3">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" name="Glyph 3">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block" data-ditto-id="style-div-27">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg3134395121" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-24">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block" data-ditto-id="style-div-28">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-div-145" data-component="icon" fill="currentColor">
                                  <use href="#svg449212879" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="w-5 block relative shrink-0 aspect-square" data-ditto-id="style-icon-25">
                          <div className="w-5 h-5 block relative overflow-hidden cursor-pointer">
                            <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                              <div className="h-full block" data-ditto-id="style-div-29">
                                <svg className="w-5 h-5 block overflow-hidden" data-ditto-id="style-icon-32" data-component="icon" fill="currentColor">
                                  <use href="#svg449212879" />
                                </svg>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0">
                        {Logo6_data2.map((d, i) => <Logo6 key={i} d={d} />)}
                      </div>
                      <div className="h-full flex relative flex-col justify-around items-center content-center shrink-0" data-ditto-id="style-div-30">
                        {Logo7_data2.map((d, i) => <Logo7 key={i} d={d} />)}
                        <div className="w-5 h-5 block relative shrink-0">
                          <div className="w-5 h-5 flex relative min-w-5 flex-col justify-center items-center content-center gap-2.5">
                            <div className="w-5 h-full block absolute top-0 left-0 z-1 min-w-0 shrink-0 aspect-square" name="Glyph 2">
                              <div className="w-5 h-5 block relative overflow-hidden cursor-pointer" name="Glyph 2">
                                <div className="w-5 h-full block absolute top-0 shrink-0" aria-hidden="true">
                                  <div className="h-full block" data-ditto-id="style-div-32">
                                    <svg className="w-5 h-5 block overflow-hidden" data-component="icon" fill="currentColor">
                                      <use href="#svg3670745582" />
                                    </svg>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {Logo7_data3.map((d, i) => <Logo7 key={i} d={d} />)}
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </section>
          </div>
        </div>
        <div className="block" id="overlay" />
      </div>
      {" "}
      <div className="w-0 h-0 block absolute top-200 left-0 z-0 overflow-hidden" aria-hidden="true" id="svg-templates">
        <svg className="w-[6.0625rem] h-[1.8125rem] inline overflow-hidden" data-component="image" fill="none" height="29" id="svg-548646222_1821" width="97">
          <path fillRule="evenodd" clipRule="evenodd" d="M0 .826V22.7h3.365v-8.872h5.751c4.13 0 7.189-1.896 7.189-6.485S13.245.826 9.116.826H0Zm8.963 10.095H3.365V3.732h5.598c2.54 0 3.824 1.132 3.824 3.61 0 2.447-1.285 3.58-3.824 3.58Zm21.74-9.85h-3.395v3.242h3.395V1.071Zm-.183 6.026h-2.998v15.601h2.998v-15.6Zm25.562 11.564c0 2.661 1.988 4.466 5.109 4.466 2.539 0 4.313-1.01 5.353-2.631h.061c.153 1.774.98 2.356 2.447 2.356.49 0 1.01-.062 1.53-.184v-1.835c-.183.03-.275.03-.367.03-.581 0-.734-.581-.734-1.713v-7.158c0-4.038-2.57-5.384-5.782-5.384-4.772 0-6.73 2.355-6.883 5.353h3.06c.152-2.08.978-2.937 3.7-2.937 2.295 0 2.968.949 2.968 2.08 0 1.53-1.499 1.836-3.946 2.295-3.885.765-6.516 1.774-6.516 5.262Zm10.462-2.05c0 2.723-1.988 4.1-4.68 4.1-1.866 0-2.631-.796-2.631-2.265 0-1.62 1.132-2.355 3.885-2.936 1.59-.337 2.937-.673 3.426-1.132v2.233Zm5.546-9.513h2.997v2.967h.062c.795-1.958 2.08-3.335 4.19-3.335.551 0 .98.031 1.438.092v2.876a6.18 6.18 0 0 0-1.01-.092c-2.722 0-4.68 2.05-4.68 5.017v8.076H72.09V7.098Zm15.493 15.447L81.25 7.097h3.274l4.558 11.93h.06l4.314-11.93h3.12l-6.148 15.968c-1.53 3.855-3.029 5.109-5.445 5.109-.674 0-1.132-.061-1.928-.214v-2.448c.52.062.796.092 1.285.092 1.224 0 2.6-.612 3.243-3.059Zm-54.645.153V7.097h2.998v1.958h.06c.827-1.193 2.265-2.417 4.62-2.417 2.172 0 3.487.979 4.13 2.723h.061c1.132-1.5 2.692-2.723 5.109-2.723 3.15 0 4.741 1.897 4.741 5.231v10.83H51.66V12.694c0-2.08-.428-3.487-2.722-3.487-2.233 0-3.64 1.56-3.64 3.915v9.575H42.3V12.695c0-2.08-.429-3.487-2.723-3.487-2.233 0-3.64 1.56-3.64 3.915v9.575h-2.998Zm-15.253-15.6h2.998v2.967h.061c.796-1.958 2.08-3.335 4.191-3.335.551 0 .98.031 1.438.092v2.876a6.18 6.18 0 0 0-1.01-.092c-2.722 0-4.68 2.05-4.68 5.017v8.076h-2.998V7.098Z" fill="#0F0F0F" />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" data-ditto-id="style-svg155221230" id="svg12505226328" viewBox="0 0 16 17" fill="currentColor">
          <path d="M 6.961 16.276 C 6.808 16.28 6.662 16.214 6.563 16.097 C 6.464 15.981 6.423 15.826 6.451 15.676 L 7.251 10.054 L 4.138 10.054 C 3.916 10.054 3.778 9.994 3.727 9.876 C 3.675 9.758 3.708 9.595 3.827 9.387 L 8.895 0.521 C 8.93 0.442 8.993 0.378 9.072 0.343 C 9.147 0.302 9.231 0.279 9.317 0.276 C 9.47 0.272 9.616 0.338 9.716 0.454 C 9.815 0.571 9.856 0.726 9.828 0.876 L 9.028 6.499 L 12.139 6.499 C 12.361 6.499 12.499 6.558 12.549 6.676 C 12.602 6.795 12.569 6.958 12.45 7.166 L 7.384 16.032 C 7.349 16.112 7.286 16.175 7.206 16.21 C 7.131 16.251 7.047 16.273 6.961 16.276 Z" fill={"var(--token-6bdc6b55-5c79-4cab-9c0d-89e3ea8f2369, rgb(15, 15, 15)) /* {\"name\":\"Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg10648649387" viewBox="0 0 70 74" fill="currentColor">
          <path d="M 30.454 70.848 C 29.786 70.864 29.146 70.578 28.713 70.071 C 28.28 69.565 28.1 68.891 28.223 68.237 L 31.723 43.764 L 18.104 43.764 C 17.133 43.764 16.529 43.503 16.306 42.99 C 16.078 42.476 16.223 41.766 16.743 40.861 L 38.916 2.268 C 39.067 1.922 39.343 1.646 39.69 1.493 C 40.02 1.314 40.387 1.215 40.762 1.201 C 41.431 1.185 42.072 1.47 42.506 1.977 C 42.94 2.484 43.12 3.159 42.998 3.813 L 39.498 28.29 L 53.108 28.29 C 54.079 28.29 54.683 28.547 54.902 29.06 C 55.134 29.578 54.989 30.288 54.469 31.193 L 32.305 69.786 C 32.152 70.133 31.874 70.409 31.526 70.561 C 31.196 70.738 30.829 70.836 30.454 70.848 Z" fill={"var(--token-6bdc6b55-5c79-4cab-9c0d-89e3ea8f2369, rgb(15, 15, 15)) /* {\"name\":\"Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg155221230" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 0 L 4 0 L 4 4 L 0 4 Z M 8 0 L 12 0 L 12 4 L 8 4 Z M 16 0 L 20 0 L 20 4 L 16 4 Z M 8 8 L 12 8 L 12 12 L 8 12 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 16 16 L 20 16 L 20 20 L 16 20 Z" fill={"var(--token-bd738c11-846b-448c-ae1a-08a6d0c8b314, rgb(30, 30, 30)) /* {\"name\":\"Off-Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg2218268641" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 8 L 4 8 L 4 12 L 0 12 Z M 0 0 L 4 0 L 4 4 L 0 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z M 8 16 L 12 16 L 12 20 L 8 20 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z" fill={"var(--token-bd738c11-846b-448c-ae1a-08a6d0c8b314, rgb(30, 30, 30)) /* {\"name\":\"Off-Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg1370478740" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 0 L 4 0 L 4 4 L 0 4 Z M 8 0 L 12 0 L 12 4 L 8 4 Z M 16 0 L 20 0 L 20 4 L 16 4 Z M 8 8 L 12 8 L 12 12 L 8 12 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 16 16 L 20 16 L 20 20 L 16 20 Z" fill={"var(--token-ad1dc83c-305c-4ffa-869c-ce3f358c4505, rgb(255, 255, 255)) /* {\"name\":\"White\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg3950062250" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 16 0 L 20 0 L 20 4 L 16 4 Z M 0 0 L 4 0 L 4 4 L 0 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z M 0 16 L 4 16 L 4 20 L 0 20 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z" fill={"var(--token-bd738c11-846b-448c-ae1a-08a6d0c8b314, rgb(30, 30, 30)) /* {\"name\":\"Off-Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg449212879" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 0 L 4 0 L 4 4 L 0 4 Z M 0 16 L 4 16 L 4 20 L 0 20 Z M 16 0 L 20 0 L 20 4 L 16 4 Z M 8 8 L 12 8 L 12 12 L 8 12 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z" fill={"var(--token-bd738c11-846b-448c-ae1a-08a6d0c8b314, rgb(30, 30, 30)) /* {\"name\":\"Off-Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg3861013906" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 8 L 4 8 L 4 12 L 0 12 Z M 8 8 L 12 8 L 12 12 L 8 12 Z M 8 16 L 12 16 L 12 20 L 8 20 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z" fill={"var(--token-bd738c11-846b-448c-ae1a-08a6d0c8b314, rgb(30, 30, 30)) /* {\"name\":\"Off-Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg3038929338" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 16 0 L 20 0 L 20 4 L 16 4 Z M 0 0 L 4 0 L 4 4 L 0 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z M 0 16 L 4 16 L 4 20 L 0 20 Z M 8 8 L 12 8 L 12 12 L 8 12 Z" fill={"var(--token-bd738c11-846b-448c-ae1a-08a6d0c8b314, rgb(30, 30, 30)) /* {\"name\":\"Off-Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden" id="svg9105935482" viewBox="0 0 80 85" fill="currentColor">
          <path d="M 34.805 81.38 C 34.041 81.398 33.31 81.07 32.815 80.487 C 32.321 79.905 32.115 79.131 32.255 78.38 L 36.255 50.27 L 20.69 50.27 C 19.58 50.27 18.89 49.97 18.635 49.38 C 18.375 48.79 18.54 47.975 19.135 46.935 L 44.475 2.605 C 44.648 2.208 44.964 1.89 45.36 1.715 C 45.737 1.51 46.156 1.395 46.585 1.38 C 47.35 1.361 48.082 1.688 48.578 2.271 C 49.074 2.853 49.281 3.628 49.14 4.38 L 45.14 32.495 L 60.695 32.495 C 61.805 32.495 62.495 32.79 62.745 33.38 C 63.01 33.975 62.845 34.79 62.25 35.83 L 36.92 80.16 C 36.746 80.558 36.428 80.876 36.03 81.05 C 35.653 81.253 35.233 81.366 34.805 81.38 Z" fill={"var(--token-6bdc6b55-5c79-4cab-9c0d-89e3ea8f2369, rgb(15, 15, 15)) /* {\"name\":\"Black\"} */"} />
        </svg>
        {" "}
        <svg className="w-0 h-0 inline overflow-hidden md:max-lg:hidden" id="svg3670745582" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 8 L 4 8 L 4 12 L 0 12 Z M 0 0 L 4 0 L 4 4 L 0 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z M 8 16 L 12 16 L 12 20 L 8 20 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z" fill={"var(--token-ad1dc83c-305c-4ffa-869c-ce3f358c4505, rgb(255, 255, 255)) /* {\"name\":\"White\"} */"} />
        </svg>
        <svg className="w-0 h-0 inline overflow-hidden 2xl:hidden" id="svg3134395121" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 16 0 L 20 0 L 20 4 L 16 4 Z M 0 0 L 4 0 L 4 4 L 0 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z M 0 16 L 4 16 L 4 20 L 0 20 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z" fill={"var(--token-ad1dc83c-305c-4ffa-869c-ce3f358c4505, rgb(255, 255, 255)) /* {\"name\":\"White\"} */"} />
        </svg>
        <svg className="w-0 h-0 inline overflow-hidden" data-ditto-id="style-icon-15" id="svg2804029" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 0 L 4 0 L 4 4 L 0 4 Z M 0 16 L 4 16 L 4 20 L 0 20 Z M 16 0 L 20 0 L 20 4 L 16 4 Z M 8 8 L 12 8 L 12 12 L 8 12 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z" fill={"var(--token-ad1dc83c-305c-4ffa-869c-ce3f358c4505, rgb(255, 255, 255)) /* {\"name\":\"White\"} */"} />
        </svg>
        <svg className="w-0 h-0 inline overflow-hidden" id="svg473936616" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 0 8 L 4 8 L 4 12 L 0 12 Z M 8 8 L 12 8 L 12 12 L 8 12 Z M 8 16 L 12 16 L 12 20 L 8 20 Z M 16 8 L 20 8 L 20 12 L 16 12 Z M 8 0 L 12 0 L 12 4 L 8 4 Z" fill={"var(--token-ad1dc83c-305c-4ffa-869c-ce3f358c4505, rgb(255, 255, 255)) /* {\"name\":\"White\"} */"} />
        </svg>
        <svg className="w-0 h-0 inline overflow-hidden" id="svg1836501473" viewBox="0 0 20 20" fill="currentColor">
          <path d="M 16 0 L 20 0 L 20 4 L 16 4 Z M 0 0 L 4 0 L 4 4 L 0 4 Z M 16 16 L 20 16 L 20 20 L 16 20 Z M 0 16 L 4 16 L 4 20 L 0 20 Z M 8 8 L 12 8 L 12 12 L 8 12 Z" fill={"var(--token-ad1dc83c-305c-4ffa-869c-ce3f358c4505, rgb(255, 255, 255)) /* {\"name\":\"White\"} */"} />
        </svg>
      </div>
      {" "}
    </>
  );
}
