import "./ditto.css";
import NavLink from "./components/nav-link";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import CardLink from "./components/card-link";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "https://jens.marketing/leistungen", label: "Beratung" },
    { href: "/workshops", label: "Workshops" },
    { href: "/buehne", label: "Vorträge" },
    { href: "https://jens.marketing/tools", label: "Tools" },
    { href: "/blog", label: "Blog" },
    { href: "https://jens.marketing/ueber-jens-polomski", label: "Über" },
    { href: "https://jens.marketing/kontakt", label: "Kontakt" }
];
const Tile_data = [
    { href: "/", label: "Start" },
    { href: "/blog", label: "Blog" },
    { href: "/blog", label: "KI-Marketing" }
];
const ListRow_data = [
    { text: "Geschichten, Gedichte, Songtexte schreiben oder umformulieren lassen (basierend auf echten Dingen)" },
    { text: "Jede fachliche Frage beantworten lassen" },
    { text: "Programmiercode erstellen" },
    { text: "Komplexe Themen besprechen und mit jeder Frage auf bisherige Inhalte eingehen" },
    { text: "Prompts für KI-Bilder generieren" },
    { text: "Was dir sonst noch so einfällt …" }
];
const ListRow2_data = [
    { href: "#was-ist-chatgpt", label: "Was ist ChatGPT?" },
    { href: "#chatgpt-nachfrage-erobert-das-internet", label: "ChatGPT Nachfrage erobert das Internet" },
    { href: "#was-kann-chatgpt", label: "Was kann ChatGPT?" },
    { href: "#beispiele-für-chatgpt", label: "Beispiele für ChatGPT" },
    { href: "#chatgpt-beispiele-zum-selbst-ausprobieren", label: "ChatGPT Beispiele zum selbst ausprobieren" },
    { href: "#chatgpt-selbst-ausprobieren", label: "ChatGPT selbst ausprobieren" }
];
const ListRow3_data = [
    { href: "/blog", label: "Alle Beiträge" },
    { href: "https://jens.marketing/tools", label: "Tool-Verzeichnis" },
    { href: "/ki-newsletter", label: "KI-Newsletter" },
    { href: "https://jens.marketing/ueber-jens-polomski", label: "Über Jens" }
];
const CardLink_data = [
    { href: "/die-besten-ki-coding-tools", title: "Die 17 besten KI zum Programmieren 2026 (auch kostenlos)", label: "Die besten KI-Tools zum Programmieren 2026 im Vergleich: 17 Tools von Claude Code über Cursor, GitHub Copilot und OpenAI Codex bis Cline, Aider und Lovable — beste KI insgesamt, beste kostenlose & Open-Source-Optionen, mit Preisen, Free-Tiers und Use-Cases." },
    { href: "https://jens.marketing/tools-ki-texte", title: "KI-Texte schreiben 2026: 16 Tools kostenlos & im Vergleich", label: "Die besten KI-Text-Generatoren 2026 im Vergleich: 16 Tools mit aktuellen Preisen, Free-Versionen, DSGVO-Status und meiner Top-3 aus über 3 Jahren Praxis." },
    { href: "/die-besten-ki-bild-generatoren", title: "Die 22 besten KI-Bild-Generatoren 2026: kostenlos & im Vergleich", label: "Die besten KI-Bild-Generatoren 2026 im Vergleich: 22 Tools von Midjourney V8.1 über GPT Image 2, Google Nano Banana und Flux.2 bis Ideogram 4, Recraft V4.1 und Seedream – mit aktuellen Preisen, Free-Tiers, Image-to-Image und Use-Cases." }
];
const NavLink_meta: string[][] = [
    ["style-10"],
    ["style-11"],
    ["style-14"],
    ["style-1"],
    ["style-4"],
    ["style-5"],
    ["style-suche-ffnen"]
];
const Tile_meta: string[][] = [
    ["n24", "style-section", "style-link-18"],
    ["n27", "style-span", "n29"],
    ["n30", "style-heading", "style-p-103"]
];
const ListRow_meta: string[][] = [
    ["style-9-regeln-f-r-den-ki-einsatz-im-berblick"],
    ["style-p"],
    ["style-section-13"],
    ["style-div-50"],
    ["style-p-69"],
    ["style-div-51"]
];
const ListRow2_meta: string[][] = [
    ["style-strong-18", "style-tile-muster-erstellen"],
    ["style-p-71", "style-strong-3"],
    ["style-p-21", "style-p-23"],
    ["style-strong-13", "style-p-27"],
    ["style-tag-8-developer-tools-f-r-ki-l-sungen", "style-ul-4"],
    ["style-schritt-f-r-schritt-so-setzt-du-tile-ein", "style-section-14"]
];
const ListRow3_meta: string[][] = [
    ["style-strong-14", "style-p-66", "style-strong-36"],
    ["style-prefer-suffix-parameter-automatisieren", "style-p-29", "style-strong-17"],
    ["style-p-33", "style-p-70", "style-p-84"],
    ["style-ul-14", "style-p-80", "style-1-suffix-einsetzen"]
];
const CardLink_meta: string[][] = [
    ["style-warum-ist-prefer-wichtig", "style-p-31", "style-strong-19", "style-p-77", "style-strong-38", "style-fazit-schnellere-arbeitsprozesse-in-midjourney", "style-p-37"],
    ["style-p-85", "style-tag-11-desktop-apps-chatgpt-als-assistent-auf-dein", "style-ul-8", "style-div-73", "style-div-78", "style-image-5", "style-div-70"],
    ["style-div-27", "style-author-bio-heading", "style-p-34", "style-div-72", "style-button-10", "style-icon-17", "style-p-7"]
];
const ListRow_styles = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];
const ListRow2_styles = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];
const ListRow3_styles = [
    { className: "mb-2" },
    { className: "mb-2" },
    { className: "mb-2" },
    {  }
];
const CardLink_styles = [
    { className: "md:max-lg:mt-6" },
    { className: "md:max-lg:mt-6" },
    {  }
];

export default function Page() {
  return (
    <>
      <div className="block fixed inset-x-0 z-20 min-w-0 bg-border h-0.5" aria-hidden="true" />
      <header className="w-full h-22 flex sticky top-0 z-40 py-6 px-14 items-center gap-9 bg-primary max-md:h-18 max-md:py-4 max-md:px-6 max-md:gap-6">
        <a className="h-[25.5px] block text-color-002 text-[1.0625rem] font-semibold leading-[1.625rem] tracking-[-0.17px] cursor-pointer" data-component="link" href="/">
          jens
          <span className="inline text-color-004">
            .
          </span>
          marketing
        </a>
        <div className="block flex-1" />
        <nav className="flex gap-7 text-color-001 text-sm leading-5 max-lg:hidden" data-ditto-id="style-nav" data-component="nav">
          {NavLink_data.map((d, i) => <NavLink key={i} d={d} />)}
        </nav>
        <button className="border border-solid border-color-003 flex rounded-full justify-center items-center text-color-002 text-center cursor-default h-10 w-10" data-ditto-id="style-suche-ffnen-2" data-component="button" aria-label="Suche öffnen" type="button">
          <svg className="w-auto h-4 block overflow-hidden align-middle" data-ditto-id="style-icon-30" data-component="icon" aria-hidden="true" fill="none" height="16" stroke="currentColor" viewBox="0 0 16 16" width="16" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="7" cy="7" r="5" />
            <path d="M11 11l3 3" />
          </svg>
        </button>
        <a className="block py-2.5 px-4.5 rounded-full text-primary text-sm font-medium leading-5 bg-color-002 cursor-pointer max-lg:hidden" data-ditto-id="style-link" data-component="link" href="/ki-newsletter">
          Newsletter abonnieren
        </a>
        <button className="border border-solid border-color-003 hidden min-w-0 rounded-full justify-center items-center text-color-002 text-center cursor-default h-10 w-10 max-lg:flex" aria-controls="mobile-nav" aria-expanded="false" aria-label="Menü öffnen" type="button">
          <svg className="w-auto h-4.5 block overflow-hidden align-middle" aria-hidden="true" fill="none" height="18" stroke="currentColor" viewBox="0 0 24 24" width="18" strokeWidth="2" strokeLinecap="round">
            <line x1="4" y1="7" x2="20" y2="7" />
            <line x1="4" y1="12" x2="20" y2="12" />
            <line x1="4" y1="17" x2="20" y2="17" />
          </svg>
        </button>
      </header>
      <main className="block flex-1 bg-background">
        <article className="block max-w-275 mx-auto px-14 max-md:px-6">
          <header className="w-full max-w-180 block pt-12 pb-10">
            <div className="block mb-7">
              <nav className="flex items-center gap-2 text-muted-foreground [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.54px] uppercase" data-component="nav" aria-label="Breadcrumb">
                {Tile_data.map((d, i) => <Tile key={i} d={d} />)}
                <span className="flex items-center gap-2" data-ditto-id="style-span-9">
                  <span className="block" aria-current="page">
                    ChatGPT – der wohl mächtigste KI-Chatbot
                  </span>
                </span>
              </nav>
            </div>
            <div className="flex mb-6 flex-wrap items-center gap-2.5">
              <span className="flex py-1.5 px-3.5 rounded-full items-center gap-2 text-color-002 [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.54px] uppercase bg-primary">
                <span className="block rounded-full bg-accent h-1.5 w-1.5" />
                KI-Marketing
              </span>
              <span className="border border-solid border-border block py-1 px-3 rounded-full text-muted-foreground [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.54px] uppercase">
                Blog
              </span>
            </div>
            <h1 className="block text-[3.5rem] font-medium leading-[3.6875rem] tracking-[-1.68px]" data-component="heading">
              ChatGPT – der wohl mächtigste KI-Chatbot
            </h1>
            <div className="border-t border-solid border-t-border flex mt-7 pt-5 flex-wrap items-center gap-y-2 gap-x-6 text-muted-foreground [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-xs leading-4.5 tracking-[1.68px] uppercase" data-ditto-id="style-div-54">
              <a className="block cursor-pointer" data-ditto-id="style-link-2" data-component="link" href="https://jens.marketing/ueber-jens-polomski">
                Jens Polomski
              </a>
              <span className="block" data-ditto-id="style-span-3" aria-hidden="true">
                ·
              </span>
              <time className="block" data-ditto-id="style-time" dateTime="2022-12-03T00:00:00.000Z">
                3. Dezember 2022
              </time>
              <span className="block" aria-hidden="true">
                ·
              </span>
              <span className="block" data-ditto-id="style-span-12">
                4 min
              </span>
            </div>
          </header>
          <section className="w-full max-w-180 block pb-12">
            <div className="border-l-4 border-solid border-l-accent block p-8 rounded-[20px] overflow-hidden bg-surface shadow-[var(--clr-0)_0px_0px_0px_0px,var(--clr-0)_0px_0px_0px_0px,var(--clr-0)_0px_0px_0px_0px,var(--clr-0)_0px_0px_0px_0px,var(--clr-2)_0px_1px_0px_0px]" data-ditto-id="style-div-57">
              <div className="block mb-3 text-accent [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase">
                Worum es geht
              </div>
              <p className="block text-xl font-light leading-7.5">
                📖 Inhaltsverzeichnis Was ist ChatGPT? ChatGPT basiert auf GPT-3.5, einem Sprachmodell, das mithilfe von Deep Learning menschenähnlichen Text erzeugt. Während das ältere GPT-3-Modell nur Textaufforderungen ...
              </p>
              <div className="border-t border-solid border-t-border flex mt-6 pt-5 flex-wrap items-center gap-y-3 gap-x-6 text-muted-foreground [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.54px] uppercase" data-ditto-id="style-div-90">
                <span className="block">
                  {"Kategorie · "}
                  <span className="inline text-primary font-semibold">
                    KI-Marketing
                  </span>
                </span>
                <span className="block" aria-hidden="true">
                  ·
                </span>
                <span className="block" data-ditto-id="style-span-10">
                  {"Veröffentlicht · "}
                  <span className="inline text-primary font-semibold" data-ditto-id="style-span-13">
                    2022
                  </span>
                </span>
              </div>
            </div>
          </section>
          <div className="grid pb-20 gap-12 grid-cols-[720px_1fr] max-lg:grid-cols-1">
            <div className="w-180 block min-w-0 max-md:w-[20.4375rem] md:max-lg:w-164" data-ditto-id="style-div-91">
              <div className="block mb-6 text-primary [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase">
                Im Detail
              </div>
              <div className="block text-[1.0625rem] font-light leading-[1.6875rem]">
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-ditto-id="style-p-104" data-component="heading" id="-inhaltsverzeichnis">
                  📖 Inhaltsverzeichnis
                </h3>
                {" "}
                <h2 className="block mt-12 mb-4 text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-ltm-2-mini-ein-quantensprung-in-der-ki" data-component="heading" id="was-ist-chatgpt">
                  Was ist ChatGPT?
                </h2>
                {" "}
                <p className="block my-5">
                  <a className="inline text-primary underline cursor-pointer" data-component="link" href="https://openai.com/blog/chatgpt/">
                    <strong className="inline text-foreground font-medium">
                      ChatGPT
                    </strong>
                  </a>
                  {" wurde 2022 auf Basis von GPT-3.5 gestartet und nutzt heute moderne Modelle aus der GPT-5-Familie (Stand 2026 das Flaggschiff "}
                  <strong className="inline font-medium" data-ditto-id="style-p-65">
                    GPT-5.5
                  </strong>
                  {"). Sprachmodelle wie diese erzeugen mithilfe von Deep Learning menschenähnlichen Text. Während die früheren GPT-3-Modelle nur Textaufforderungen aufnahmen und versuchten, diese mit eigenem generierten Text fortzusetzen, ist ChatGPT viel schlauer. Es ist viel besser in der Lage, "}
                  <strong className="inline font-medium">
                    detaillierte
                  </strong>
                  {" "}
                  <strong className="inline font-medium">
                    Texte
                  </strong>
                  {" "}
                  <strong className="inline font-medium" data-ditto-id="style-p-55">
                    zu generieren
                  </strong>
                  {" und kann sogar Gedichte verfassen. Eine weitere "}
                  <strong className="inline font-medium" data-ditto-id="style-kontextfenster-und-ihre-bedeutung">
                    einzigartige
                  </strong>
                  {" "}
                  <strong className="inline font-medium" data-ditto-id="style-strong-40">
                    Eigenschaft
                  </strong>
                  {" ist das Gedächtnis. "}
                  <strong className="inline font-medium">
                    Der Bot kann sich an frühere Kommentare in einer Unterhaltung erinnern
                  </strong>
                  {" und sie dem Benutzer wiedergeben. Neben Antworten auf sehr viele Fragen kannst du mit ChatGPT z.B. Code schreiben, Probleme lösen, Texte schreiben, Ideen bekommen und noch so viel mehr …"}
                </p>
                {" "}
                <p className="block my-5">
                  Die Nutzung von ChatGPT ist in den letzten Wochen quasi explodiert und bereits nach dem Start hat ChatGPT in nur fünf Tagen über eine Millionen User erreicht und nicht nur zahlreiche Updates erfahren sondern auch die kostenpflichtige Variante (ChatGPT Plus) vorgestellt.
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-wohin-f-hrt-die-reise">
                  {"Obwohl die Technologie noch sehr neu ist, gibt es bereits erste Tools, die durch das neue Modell von OpenAI enstanden sind. Aber nicht nur "}
                  <a className="inline text-primary underline cursor-pointer" data-component="link" href="/chatgpt-tools">
                    ChatGPT-Tools
                  </a>
                  {" gibt es neuerdings, auch eine "}
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-p-61" data-component="link" href="https://jens.marketing/zapier-openai/">
                    Zapier Integration für OpenAI (also GPT und DALL-E)
                  </a>
                  {" wurde veröffentlicht."}
                </p>
                {" "}
                <p className="block my-5">
                  {"Neben der puren Version von ChatGPT gibt es mittlerweile "}
                  <strong className="inline font-medium">
                    Apps in ChatGPT
                  </strong>
                  {" (früher als \"Plugins\" eingeführt und 2025 zu Apps + Connectors weiterentwickelt), die ChatGPT noch viel mächtiger machen und mit anderen Anbietern verbinden."}
                </p>
                {" "}
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-component="heading" id="chatgpt-über-sich-selbst">
                  ChatGPT über sich selbst
                </h3>
                {" "}
                <p className="block my-5">
                  Fragt man ChatGPT „
                  <strong className="inline font-medium" data-ditto-id="style-div-88">
                    Was bist du
                  </strong>
                  “ bekommt man übrigens folgende Antwort:
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-image-6">
                  <em className="inline italic" data-ditto-id="style-div-61">
                    Ich bin Assistant, ein großes Sprachmodell, das von OpenAI trainiert wurde. Mein Hauptzweck ist es, Menschen dabei zu helfen, Fragen zu beantworten und Informationen zu liefern, sowie Gespräche zu führen. Ist es etwas Bestimmtes, das du wissen möchtest? Lass mich dir gerne weiterhelfen.
                  </em>
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-div-49">
                  Auf Nachfrage erzählt ChatGPT sogar etwas mehr über die genaue Funktionsweise:
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-author-bio-heading-3">
                  <em className="inline italic" data-ditto-id="style-p-45">
                    Gerne. Als großes Sprachmodell bin ich dafür ausgelegt, menschenähnliche Konversationen zu führen und auf Fragen zu antworten. Dazu verwende ich eine Kombination aus maschinellem Lernen und natürlicher Sprachverarbeitung, um die Anfragen und Anweisungen, die ich erhalte, zu verstehen und darauf zu reagieren. Meine Antworten basieren auf den Informationen, die mir zur Verfügung stehen, und ich tue mein Bestes, um präzise und hilfreiche Antworten zu liefern. Wenn du irgendwelche Fragen zu meiner Funktionsweise hast, zögere bitte nicht, sie mir zu stellen. Ich werde mein Bestes tun, um dir zu helfen.
                  </em>
                </p>
                {" "}
                <h2 className="block mt-12 mb-4 text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-div-24" data-component="heading" id="chatgpt-nachfrage-erobert-das-internet">
                  ChatGPT Nachfrage erobert das Internet
                </h2>
                {" "}
                <p className="block my-5" data-ditto-id="style-button">
                  <img className="w-125 h-125 block max-w-full overflow-clip align-middle max-md:w-[20.4375rem] max-md:h-[20.4375rem]" data-ditto-id="style-icon" data-component="image" alt="chatgpt-nachfrage" src="/assets/cloned/images/26d08f5264e4.jpg" title="chatgpt-nachfrage" />
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-button-2">
                  {"ChatGPT ging so schnell viral wie kaum ein anderes Tool oder Technologie. "}
                  <strong className="inline font-medium" data-ditto-id="style-link-3">
                    OpenAI meldete, dass ChatGPT in nur 5 Tagen 1 Million Nutzer erreicht hat
                  </strong>
                  . Die Suchanfragen nach ChatGPT stiegen in die Höhe und übertrafen die Suchanfragen nach „lensa“, einer anderen KI-App, die diese Woche Wellen schlug.
                </p>
                {" "}
                <h2 className="block mt-12 mb-4 text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-icon-2" data-component="heading" id="was-kann-chatgpt">
                  Was kann ChatGPT?
                </h2>
                {" "}
                <p className="block my-5" data-ditto-id="style-aside-6">
                  ChatGPT kann Fragen auf die unterschiedlichsten Fragen geben, Probleme lösen, Programmiercode erstellen und korrigieren, Texte umschreiben und übersetzen, Songtexte, Gedichte oder andre kreative Texte schreiben und noch so viel mehr.
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-inhaltsverzeichnis-3">
                  Irgendwie fühlt sich ChatGPT fast wie die „bessere Google Suche“ an. Es kann aber auch neue Inhalte erstellen, vorhandene Inhalte (wie z.B. Songtexte) für dich anpassen oder sogar für dich programmieren.
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-div-71">
                  Außerdem kann der Chatbot auf alle Aspekte von vorherigen Antworten eingehen. Du musst also nicht jede neue Frage komplett formulieren.
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-ol-4">
                  {"Noch kann ChatGPT leider nur Text generieren und eignet sich noch nicht zum "}
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-p-20" data-component="link" href="/die-besten-ki-bild-generatoren">
                    Erstellen von KI-Bildern
                  </a>
                  {" (dafür gibt es aber zum Glück noch mehr Tools). Wenn hier aber DALL-E und ChatGPT zusammenarbeiten würden, wäre dies eine sehr spannende Kollaboration."}
                </p>
                {" "}
                <h2 className="block mt-12 mb-4 text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-strong" data-component="heading" id="beispiele-für-chatgpt">
                  Beispiele für ChatGPT
                </h2>
                {" "}
                <p className="block my-5" data-ditto-id="style-p-22">
                  {"Natürlich solltest du ChatGPT auch einmal selbst ausprobieren. Hier habe ich jedoch einmal einige faszinierende Beispiele erzeugt und als Screenshot angehängt. Mit den richtigen "}
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-strong-2" data-component="link" href="https://jens.marketing/gpt-3-promts/">
                    ChatGPT Befehlen
                  </a>
                  , kannst du sehr einfach ähnliche Ergebnisse erzielen.
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-strong-12">
                  Einige Beispiele, wobei dir ChatGPT richtig gute Ergebnisse liefert sind:
                </p>
                {" "}
                <ul className="block my-5 pl-5 [list-style-type:disc] list-outside" data-ditto-id="style-repeat-r-mehrfachausgaben-generieren">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} styles={ListRow_styles[i]} />)}
                </ul>
                {" "}
                <h2 className="block mt-12 mb-4 text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-link-4" data-component="heading" id="chatgpt-beispiele-zum-selbst-ausprobieren">
                  ChatGPT Beispiele zum selbst ausprobieren
                </h2>
                {" "}
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-ditto-id="style-span-4" data-component="heading" id="google-ads-überschriften">
                  Google Ads Überschriften
                </h3>
                {" "}
                <p className="block my-5" data-ditto-id="style-icon-3">
                  Schreib mir bitte 10 Google Ads Überschriften, welche eine Reise nach Dublin bewerben
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-link-5">
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-span-5" data-component="link" href="https://jens.marketing/img/wp/2022/12/chat-08.jpg">
                    <img className="w-180 h-[29.9375rem] block max-w-full overflow-clip align-middle max-md:w-[20.4375rem] max-md:h-54.5 md:max-lg:w-164 md:max-lg:h-[27.3125rem]" data-ditto-id="style-icon-4" data-component="image" alt="" src="/assets/cloned/images/a921ee019488.jpg" />
                  </a>
                </p>
                {" "}
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-ditto-id="style-section-6" data-component="heading" id="python-scripte-erstellen">
                  Python Scripte erstellen
                </h3>
                {" "}
                <p className="block my-5" data-ditto-id="style-div-66">
                  Schreib mir ein Python Script, mit dem ich GPT-3 nutzen kann.
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-div-28">
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-badge" data-component="link" href="https://jens.marketing/img/wp/2022/12/chat-07.jpg">
                    <img className="w-[14.5625rem] h-75 block max-w-full overflow-clip align-middle" data-ditto-id="style-ul-3" data-component="image" alt="" src="/assets/cloned/images/cb852f70979d.jpg" />
                  </a>
                </p>
                {" "}
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-ditto-id="style-tag-5-chatgpt-jetzt-nahtlos-integriert-in-apple-ge" data-component="heading" id="das-ende-von-tv-serien">
                  Das Ende von TV-Serien
                </h3>
                {" "}
                <p className="block my-5" data-ditto-id="style-ul">
                  Erzähle mir ein neues Ende von „Friends“
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-beispiel-f-r-generierte-bilder-mit-dem-repeat-para">
                  <img className="w-75 h-[13.3125rem] block max-w-full overflow-clip align-middle" data-ditto-id="style-p-67" data-component="image" alt="" src="/assets/cloned/images/4f80d2dcbc52.jpg" />
                </p>
                {" "}
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-ditto-id="style-p-2" data-component="heading" id="content-themen-finden">
                  Content Themen finden
                </h3>
                {" "}
                <p className="block my-5" data-ditto-id="style-link-14">
                  Welche 10 Blogartikel könnte ich zum Thema LinkedIn schreiben?
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-image">
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-warum-ist-repeat-wichtig" data-component="link" href="https://jens.marketing/img/wp/2022/12/chat-01.jpg">
                    <img className="w-180 h-193.5 block max-w-full overflow-clip align-middle max-md:w-[20.4375rem] max-md:h-88 md:max-lg:w-164 md:max-lg:h-176.5" data-ditto-id="style-p-30" data-component="image" alt="" src="/assets/cloned/images/0926bed84527.jpg" />
                  </a>
                </p>
                {" "}
                <h3 className="block mt-8 mb-3 text-[1.375rem] font-medium leading-[2.1875rem] tracking-[-0.44px]" data-ditto-id="style-strong-37" data-component="heading" id="vorherige-antworten-aufgreifen">
                  Vorherige Antworten aufgreifen
                </h3>
                {" "}
                <p className="block my-5" data-ditto-id="style-p-3">
                  Schreibe mir mehr zu Punkt 2 …
                </p>
                {" "}
                <p className="block my-5" data-ditto-id="style-strong-11">
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-section-8" data-component="link" href="https://jens.marketing/img/wp/2022/12/chat-09.jpg">
                    <img className="w-59.5 h-75 block max-w-full overflow-clip align-middle" data-ditto-id="style-div-30" data-component="image" alt="" src="/assets/cloned/images/b228f138225c.jpg" />
                  </a>
                </p>
                {" "}
                <h2 className="block mt-12 mb-4 text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-p-16" data-component="heading" id="chatgpt-selbst-ausprobieren">
                  ChatGPT selbst ausprobieren
                </h2>
                {" "}
                <p className="block my-5" data-ditto-id="style-b">
                  {"Unter "}
                  <a className="inline text-primary underline cursor-pointer" data-ditto-id="style-button-3" data-component="link" href="https://chatgpt.com/">
                    <strong className="inline text-foreground font-medium" data-ditto-id="style-icon-5">
                      https://chatgpt.com/
                    </strong>
                  </a>
                  {" kannst du ChatGPT gerade komplett kostenlos testen. Die ist aber lediglich eine Vorschau und ist noch nicht in einem finalen Stadium. Trotzdem macht es schon echt viel Spaß und ist erschreckend gut. "}
                  <strong className="inline font-medium" data-ditto-id="style-p-24">
                    Aber Vorsicht: Es macht süchtig!
                  </strong>
                </p>
              </div>
              <aside className="border border-solid border-border block mt-16 p-8 rounded-[20px] bg-surface w-full" data-ditto-id="style-section-7" aria-labelledby="author-bio-heading">
                <div className="flex items-start gap-6" data-ditto-id="style-div-21">
                  <div className="block shrink-0 max-md:hidden" data-ditto-id="style-div-25">
                    <img className="w-full h-22 block max-w-full rounded-full overflow-clip object-cover aspect-[auto_88/88] align-middle text-clr-0" data-ditto-id="style-div-26" data-component="image" alt="Jens Polomski" height="88" sizes="88px" src="/assets/cloned/images/837e30f6082f.jpg" srcSet="/assets/cloned/images/fc76792c580b.jpg 32w, /assets/cloned/images/2525c4142096.jpg 48w, /assets/cloned/images/949ecba2adbf.jpg 64w, /assets/cloned/images/7c82b93777ed.webp 96w, /assets/cloned/images/a9a711056c65.jpg 128w, /assets/cloned/images/dc657895eb3b.jpg 256w, /assets/cloned/images/a5f1263d58f4.jpg 384w, /assets/cloned/images/26c3bc273a2a.jpg 640w, /assets/cloned/images/b7705426f7a5.jpg 750w, /assets/cloned/images/b4297c568cec.jpg 828w, /assets/cloned/images/568b28862f44.jpg 1080w, /assets/cloned/images/45edb6d46403.jpg 1200w, /assets/cloned/images/c2b67a1ba687.jpg 1920w, /assets/cloned/images/758bdfa0584e.jpg 2048w, /assets/cloned/images/837e30f6082f.jpg 3840w" width="88" />
                  </div>
                  <div className="block flex-1" data-ditto-id="style-div-29">
                    <div className="block mb-2 text-primary [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase" data-ditto-id="style-heading-6">
                      Geschrieben von Jens Polomski
                    </div>
                    <h2 className="block text-xl font-medium leading-7.5 tracking-[-0.2px]" data-ditto-id="style-link-15" data-component="heading" id="author-bio-heading">
                      {"KI-Marketing-Berater & Newsletter-Creator. Seit 2009 in Online-Marketing."}
                    </h2>
                    <p className="block mt-3 text-muted-foreground text-[0.9375rem] font-light" data-ditto-id="style-div-22">
                      LinkedIn Top Voice in KI, Mitgründer von snipKI, Co-Host des NewMinds.AI Podcast. Ich helfe Marketing-Teams bei OMR, freenet, MAN, Handelsblatt, Sparkasse, KI-Tools nicht nur auszuprobieren, sondern messbar einzusetzen.
                    </p>
                    <div className="flex mt-5 flex-wrap items-center gap-3" data-ditto-id="style-p-18">
                      <a className="h-[35.5px] flex py-2 px-4 rounded-full items-center gap-2 text-color-002 text-[0.8125rem] font-medium leading-[1.25rem] bg-primary cursor-pointer" data-ditto-id="style-strong-15" data-component="button" href="/ki-newsletter">
                        {"Newsletter abonnieren "}
                        <svg className="w-auto h-3 block overflow-hidden align-middle" data-ditto-id="style-p-32" data-component="icon" aria-hidden="true" fill="none" height="12" stroke="currentColor" viewBox="0 0 16 16" width="12" strokeWidth="1.5" strokeLinecap="square">
                          <path d="M3 8h10M9 4l4 4-4 4" />
                        </svg>
                      </a>
                      <a className="h-[37.5px] border border-solid border-border flex py-2 px-4 rounded-full items-center gap-2 text-[0.8125rem] font-medium leading-[1.25rem] cursor-pointer" data-ditto-id="style-tag-7-projekte-in-chatgpt-organisiere-deine-arbeit" data-component="button" href="https://jens.marketing/leistungen/tool-beratung">
                        Sprechstunde buchen
                      </a>
                      <a className="flex items-center gap-2 text-muted-foreground text-[0.8125rem] font-medium leading-[1.25rem] cursor-pointer" data-ditto-id="style-ul-6" data-component="link" href="https://www.linkedin.com/in/jens-polomski/" rel="noopener noreferrer" target="_blank">
                        <svg className="w-auto h-3.5 block overflow-hidden align-middle" data-ditto-id="style-image-2" data-component="icon" aria-hidden="true" fill="currentColor" height="14" viewBox="0 0 16 16" width="14">
                          <path d="M3.5 4.5a1 1 0 110-2 1 1 0 010 2zM2.5 6h2v8h-2zM6 6h2v1.2c.4-.7 1.2-1.4 2.4-1.4 2 0 2.6 1.3 2.6 3.2V14h-2v-4.4c0-1-.3-1.7-1.3-1.7s-1.7.7-1.7 1.7V14H6z" />
                        </svg>
                        {" Auf LinkedIn folgen"}
                      </a>
                    </div>
                  </div>
                </div>
              </aside>
            </div>
            <aside className="w-55 h-[1020.3px] flex sticky top-24 pr-1 flex-col self-start gap-6 max-lg:hidden" data-ditto-id="style-warum-sind-permutation-prompts-wichtig">
              <nav className="w-54 h-[224.5px] block sticky top-24 max-lg:hidden" data-ditto-id="style-p-25" data-component="nav" aria-label="Inhaltsverzeichnis">
                <div className="block mb-3 text-primary [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase" data-ditto-id="style-strong-16">
                  Auf dieser Seite
                </div>
                <ol className="block [list-style-type:none] list-outside" data-ditto-id="style-p-26">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
                </ol>
              </nav>
              <section className="block p-5 rounded-[20px] text-color-002 bg-primary" data-ditto-id="style-div-67">
                <div className="block mb-3 text-color-004 [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase" data-ditto-id="style-div-23">
                  Mit Jens arbeiten
                </div>
                <p className="block mb-4 text-color-001 text-sm font-light leading-[1.375rem]" data-ditto-id="style-heading-10">
                  Sprechstunde, Workshop oder Keynote — oder das ganze Team über snipKI weiterbilden.
                </p>
                <div className="flex flex-col gap-2" data-ditto-id="style-p-68">
                  <a className="w-44 h-[39.5px] flex py-2.5 px-4 rounded-full justify-between items-center gap-2 text-primary text-[0.8125rem] font-semibold leading-[1.25rem] whitespace-nowrap text-nowrap bg-color-002 cursor-pointer" data-ditto-id="style-button-4" data-component="link" href="https://jens.marketing/leistungen">
                    <span className="block" data-ditto-id="style-icon-6">
                      Leistungen
                    </span>
                    <svg className="w-auto h-3 block overflow-hidden align-middle" data-ditto-id="style-4-best-tige-deine-beschreibung" data-component="icon" aria-hidden="true" fill="none" height="12" stroke="currentColor" viewBox="0 0 16 16" width="12" strokeWidth="1.5" strokeLinecap="square">
                      <path d="M3 8h10M9 4l4 4-4 4" />
                    </svg>
                  </a>
                  <a className="w-44 h-[39.5px] flex py-2.5 px-4 rounded-full justify-between items-center gap-2 text-[0.8125rem] font-semibold leading-[1.25rem] whitespace-nowrap text-nowrap bg-color-008 cursor-pointer" data-ditto-id="style-p-28" data-component="link" href="https://snipki.de/" rel="noopener noreferrer" target="_blank">
                    <span className="block" data-ditto-id="style-p-19">
                      Zu snipKI
                    </span>
                    <svg className="w-auto h-3 block overflow-hidden align-middle" data-ditto-id="style-p-82" data-component="icon" aria-hidden="true" fill="none" height="12" stroke="currentColor" viewBox="0 0 16 16" width="12" strokeWidth="1.5" strokeLinecap="square">
                      <path d="M3 8h10M9 4l4 4-4 4" />
                    </svg>
                  </a>
                </div>
              </section>
              <section className="border border-solid border-border block p-5 rounded-[20px] bg-surface" data-ditto-id="style-tag-9-ein-fest-f-r-entwickler-und-startups">
                <div className="block mb-3 text-primary [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase" data-ditto-id="style-ul-5">
                  Verwandte Bereiche
                </div>
                <div className="block mb-3" data-ditto-id="style-image-4">
                  <span className="inline-flex py-1 px-3 rounded-full items-center gap-2 text-primary [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.625rem] leading-[0.9375rem] tracking-[1.4px] uppercase bg-surface-2" data-ditto-id="style-warum-ist-tile-wichtig" data-component="badge">
                    KI-Marketing
                  </span>
                </div>
                <ul className="block [list-style-type:none] list-outside" data-ditto-id="style-p-17">
                  {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
                </ul>
              </section>
              <section className="border-l-4 border-solid border-l-accent block p-5 rounded-[20px] bg-surface" data-ditto-id="style-p-35">
                <div className="block mb-2 text-accent [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase" data-ditto-id="style-2-erg-nze-deine-bevorzugten-parameter">
                  KI-Newsletter
                </div>
                <p className="block mb-3 text-sm font-light leading-[1.3125rem]" data-ditto-id="style-p-72">
                  {"Wöchentlich eine kompakte E-Mail. Über "}
                  <b className="inline font-medium" data-ditto-id="style-3-erstelle-einen-prompt">
                    45.000
                  </b>
                  {" Marketer:innen lesen mit."}
                </p>
                <a className="h-[39.5px] inline-flex py-2.5 px-3 rounded-full justify-center items-center gap-1.5 text-color-002 text-[0.8125rem] font-semibold leading-[1.25rem] whitespace-nowrap text-nowrap bg-primary cursor-pointer w-full" data-ditto-id="style-p-81" data-component="button" href="/ki-newsletter">
                  Abonnieren
                  <svg className="w-auto h-3 block overflow-hidden align-middle" data-ditto-id="style-p-73" data-component="icon" aria-hidden="true" fill="none" height="12" stroke="currentColor" viewBox="0 0 16 16" width="12" strokeWidth="1.5" strokeLinecap="square">
                    <path d="M3 8h10M9 4l4 4-4 4" />
                  </svg>
                </a>
                <p className="block mt-2 text-muted-foreground [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.625rem] leading-[0.9375rem] tracking-[1.4px] text-center uppercase" data-ditto-id="style-1-rufe-die-einstellungen-auf">
                  Kostenlos · 1-Klick-Kündigung
                </p>
              </section>
            </aside>
          </div>
        </article>
        <section className="border-t border-solid border-t-border border-b border-b-border block py-20 px-14 bg-surface-2 max-md:px-6" data-ditto-id="style-p-36">
          <div className="block max-w-275 mx-auto" data-ditto-id="style-p-74">
            <div className="flex mb-8 justify-between items-baseline" data-ditto-id="style-tag-10-chatgpt-wird-mobil-jetzt-per-telefon-und-wh">
              <div className="block" data-ditto-id="style-ul-7">
                <div className="block mb-2 text-accent [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase" data-ditto-id="style-p-75">
                  Mehr zu diesem Thema
                </div>
                <h2 className="block text-[1.75rem] font-medium leading-10.5 tracking-[-0.56px]" data-ditto-id="style-p-87" data-component="heading">
                  Weiter im KI-Marketing
                </h2>
              </div>
              <a className="block text-primary text-sm font-medium leading-5 cursor-pointer" data-ditto-id="style-link-17" data-component="link" href="/blog">
                Zum Blog →
              </a>
            </div>
            <div className="grid gap-6 grid-cols-3 max-md:grid-cols-1" data-ditto-id="style-image-3">
              {CardLink_data.map((d, i) => <CardLink key={i} d={d} styles={CardLink_styles[i]} />)}
            </div>
          </div>
        </section>
        <section className="block py-16 px-14 text-color-002 bg-primary max-md:px-6" data-ditto-id="style-p-8">
          <div className="flex max-w-275 mx-auto flex-col items-center gap-4 text-center" data-ditto-id="style-strong-6">
            <div className="block text-color-004 [font-family:'IBM_Plex_Mono',_'IBM_Plex_Mono_Fallback',_ui-monospace,_monospace] text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase">
              Mehr Beiträge in deinem Posteingang
            </div>
            <h2 className="block text-[2rem] font-medium leading-[2.3125rem] tracking-[-0.64px]" data-ditto-id="style-ul-2" data-component="heading">
              Wöchentlich filtere ich, was zählt.
            </h2>
            <p className="w-full max-w-130 block text-color-001 font-light" data-ditto-id="style-div-12">
              Über 45.000 Marketer:innen lesen den KI-Newsletter. Kein Hype, keine Affiliate-Kaskade — nur das, was wirklich weiterhilft.
            </p>
            <a className="h-[2.8125rem] flex mt-3 py-3 px-6 rounded-full items-center gap-2 text-primary text-sm font-medium leading-[1.3125rem] bg-color-002 cursor-pointer" data-ditto-id="style-ol-3" data-component="button" href="/ki-newsletter">
              {"Newsletter abonnieren "}
              <svg className="w-auto h-3 block overflow-hidden align-middle" data-ditto-id="style-link-9" data-component="icon" aria-hidden="true" fill="none" height="12" stroke="currentColor" viewBox="0 0 16 16" width="12" strokeWidth="1.5" strokeLinecap="square">
                <path d="M3 8h10M9 4l4 4-4 4" />
              </svg>
            </a>
          </div>
        </section>
      </main>
    </>
  );
}
