import Navbar from "./sections/navbar";
import HeroSection from "./sections/hero-section";
import ConsultingWebsiteExamplesSection from "./sections/consulting-website-examples-section";
import RelatedInspirationCollectionsSection from "./sections/related-inspiration-collections-section";
import LogoCloudSection from "./sections/logo-cloud-section";
import HowToMakeSection from "./sections/how-to-make-section";
import SiteBuilderReportSection from "./sections/site-builder-report-section";
import MediaCard, { type MediaCardData } from "./components/media-card";
import { MediaCard_styles } from "./_styles";

const MediaCard_data: MediaCardData[] = [
    { href: "https://devonstank.com/", title: "\n\t\t\t\t\t1. Devon Stank\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "https://devonstank.com/", alt: "Screenshot of Devon Stank, from the consulting websites collection.", imgSrc: "/assets/cloned/images/2dd09dfb3909.webp", description: "I love this homepage because it is simple and clear— Devon runs a consulting service for Squarespace and that’s immediately obvious. He has decided not to put a picture of himself on the homepage but he has lots of pictures of himself throughout the website." },
    { href: "https://www.samanthaalice.com/", title: "\n\t\t\t\t\t2. Samantha Alice\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "https://www.samanthaalice.com/", alt: "Screenshot of Samantha Alice, from the consulting websites collection.", imgSrc: "/assets/cloned/images/91ba2e76b063.webp", description: "Samantha is an ecommerce consultant with a bright, colorful website. Her main services are administration, creative, Shopify and events. She includes testimonials, links to her social media— LinkedIn and Instagram— and a portfolio of past projects." },
    { href: "https://www.frankienoller.com/", title: "\n\t\t\t\t\t3. Frankie Noller\n\t\t\t\t", href2: "https://wix.pxf.io/c/41544/2097939/25616?subId1=inspiration/consulting_websites", label: "Wix", href3: "https://www.frankienoller.com/", alt: "Screenshot of Frankie Noller, from the consulting websites collection.", imgSrc: "/assets/cloned/images/c79bcc039ac6.webp", description: "Frankie Noller is a fashion consultant who does casting and creative direction. Her website is minimal and straightforward. Her primary marketing tool is a large portfolio that showcases her work." },
    { href: "https://www.frogdesign.com/", title: "\n\t\t\t\t\t4. Frog Design\n\t\t\t\t", href2: "https://www.wqwln8trk.com/2CW6XNM57/TZ3X1FRR/", label: "Wordpress", href3: "https://www.frogdesign.com/", alt: "Screenshot of Frog Design, from the consulting websites collection.", imgSrc: "/assets/cloned/images/975335e521f2.webp", description: "This is how to use video and animation on a homepage! Everything feels vibrant and snappy. A great creative consulting website example." },
    { href: "http://www.christopherboyer.com/", title: "\n\t\t\t\t\t5. Christopher Boyer\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "http://www.christopherboyer.com/", alt: "Screenshot of Christopher Boyer, from the consulting websites collection.", imgSrc: "/assets/cloned/images/2143d24e293f.webp", description: "The website design for Christopher Boyer Consulting feels more like a consulting agency than an individual consultant— the stock photo of a city landscape gives the feel of a consulting website template rather than a custom, bespoke website design. But other than that, I like that he has a clear list of services while also sharing a podcast and blog so that you can get to know how he thinks." },
    { href: "https://www.jansenbordinhao.com/", title: "\n\t\t\t\t\t6. Jansen Bordinhao\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "https://www.jansenbordinhao.com/", alt: "Screenshot of Jansen Bordinhao, from the consulting websites collection.", imgSrc: "/assets/cloned/images/784bf40d2cb8.webp", description: "Jansen Bordinhao is a financial services consultant with a simple and straightforward website design. He also has a blog where he shares his experiences in small business— notably running a short-term rental business." },
    { href: "http://www.dianamassey.com/", title: "\n\t\t\t\t\t7. Dianna Massey\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "http://www.dianamassey.com/", alt: "Screenshot of Dianna Massey, from the consulting websites collection.", imgSrc: "/assets/cloned/images/d11ca7da0e23.webp", description: "Diana is a healthcare consultant. Her website is simple and clean— with great photography. She includes links to social media, a few case studies and list of services. She has experience as a consultant, business coach and startup founder." },
    { href: "https://jere.my/", title: "\n\t\t\t\t\t8. Jeremy Malcolm\n\t\t\t\t", href2: "https://try.carrd.co/r2x1byk2", label: "Carrd", href3: "https://jere.my/", alt: "Screenshot of Jeremy Malcolm, from the consulting websites collection.", imgSrc: "/assets/cloned/images/ff9847152396.webp", description: "This is a great example of a simple, one-page website. Jeremy has a photo, a brief description of his consulting services and links to social media, his resume and an about page." },
    { href: "https://www.kevinsharon.com/", title: "\n\t\t\t\t\t9. Kevin Sharon\n\t\t\t\t", href2: "https://wix.pxf.io/c/41544/2097939/25616?subId1=inspiration/consulting_websites", label: "Wix", href3: "https://www.kevinsharon.com/", alt: "Screenshot of Kevin Sharon, from the consulting websites collection.", imgSrc: "/assets/cloned/images/491fa5371c46.webp", description: "Kevin is a user experience consultant. His website is clear and basic. It includes contact information, a collection of his past projects and a blog that demonstrates his expertise." },
    { href: "https://www.infoset.io/", title: "\n\t\t\t\t\t10. Infoset\n\t\t\t\t", href2: "https://webflow.grsm.io/sbr?sid1=inspiration/consulting_websites", label: "Webflow", href3: "https://www.infoset.io/", alt: "Screenshot of Infoset, from the consulting websites collection.", imgSrc: "/assets/cloned/images/0d1fcd32336d.webp", description: "Infoset has a more interactive homepage than other consultants on this list. It’s a scrolling slider with vertical text for the phone number. Probably not great for UX." },
    { href: "https://www.lucasgroup.com/", title: "\n\t\t\t\t\t11. Lucas Group\n\t\t\t\t", href2: "https://www.wqwln8trk.com/2CW6XNM57/TZ3X1FRR/", label: "Wordpress", href3: "https://www.lucasgroup.com/", alt: "Screenshot of Lucas Group, from the consulting websites collection.", imgSrc: "/assets/cloned/images/3dbf8d6752a2.webp", description: "Lucas Group is an executive recruitment professional service. They fill positions across a wide range of industries— and their header bar helps you mine down into the correct industry— the specificity is great for SEO. This is an example of a corporate consulting website design." },
    { href: "https://denym.com/", title: "\n\t\t\t\t\t12. Denym Bird\n\t\t\t\t", href2: "https://try.carrd.co/r2x1byk2", label: "Carrd", href3: "https://denym.com/", alt: "Screenshot of Denym Bird, from the consulting websites collection.", imgSrc: "/assets/cloned/images/bb3709c53098.webp", description: "There’s nothing too ground-breaking about Denym’s website functionality — it’s simple and straightforward. Even the color is black and white. And that totally works. It’s clear and gets out of the way." },
    { href: "https://www.susandavid.com/", title: "\n\t\t\t\t\t13. Susan David\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "https://www.susandavid.com/", alt: "Screenshot of Susan David, from the consulting websites collection.", imgSrc: "/assets/cloned/images/35d396658855.webp", description: "Susan David is a writer, speaker and consultant. Her website does a great job of promoting her— the homepage shows a list of awards she has won, books she has written and the splash image is from a TED Talk she gave. She is sending an important message to potential clients: I am the real deal!" },
    { href: "https://www.joshkremerconsulting.com/", title: "\n\t\t\t\t\t14. Josh Kremer Consulting\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "https://www.joshkremerconsulting.com/", alt: "Screenshot of Josh Kremer Consulting, from the consulting websites collection.", imgSrc: "/assets/cloned/images/244c81c532cc.webp", description: "Josh is an ecommerce consultant with a minimalist web design. It reads almost like a resume— it’s heavy on copywriting and feels professional. He shares specific services, real pricing and a list of past clients." },
    { href: "https://www.valoppiventures.com/", title: "\n\t\t\t\t\t15. Valoppi Ventures\n\t\t\t\t", href2: "https://squarespace.syuh.net/c/41544/673110/9084?subId1=inspiration/consulting_websites", label: "Squarespace", href3: "https://www.valoppiventures.com/", alt: "Screenshot of Valoppi Ventures, from the consulting websites collection.", imgSrc: "/assets/cloned/images/954fcfa4e69f.webp", description: "Valoppi Ventures is the marketing consulting firm of Patrick Valoppi. Patrick’s face is front and center — which builds trust. His service is marketing strategies for startups." },
    { href: "https://www.mainstreamgs.com/", title: "\n\t\t\t\t\t16. Mainstream GS\n\t\t\t\t", href2: "https://wix.pxf.io/c/41544/2097939/25616?subId1=inspiration/consulting_websites", label: "Wix", href3: "https://www.mainstreamgs.com/", alt: "Screenshot of Mainstream GS, from the consulting websites collection.", imgSrc: "/assets/cloned/images/3982155f2f19.webp", description: "Mainstream GS is an example of a consulting firm website. Instead of an individual consultant on the homepage, they feature airplanes flying in tandem. The website design feels somewhat corporate." },
    { href: "https://www.fieldwork.com/", title: "\n\t\t\t\t\t17. Fieldwork\n\t\t\t\t", href2: "https://www.wqwln8trk.com/2CW6XNM57/TZ3X1FRR/", label: "Wordpress", href3: "https://www.fieldwork.com/", alt: "Screenshot of Fieldwork, from the consulting websites collection.", imgSrc: "/assets/cloned/images/d1bd2f5f3e99.webp", description: "Fieldwork is a market research consulting business. Their Wordpress theme features animations and corporate imagery. It’s clear that this is a professional website targeting corporate clients." },
    { href: "http://naturalinteraction.com/", title: "\n\t\t\t\t\t18. Natural Interaction\n\t\t\t\t", href2: "https://webflow.grsm.io/sbr?sid1=inspiration/consulting_websites", label: "Webflow", href3: "http://naturalinteraction.com/", alt: "Screenshot of Natural Interaction, from the consulting websites collection.", imgSrc: "/assets/cloned/images/69476fbc4b41.webp", description: "Natural Interactive is a user experience consultancy. There website is simple and straightforward with high contrast text." },
    { href: "http://jackdalrymple.com/", title: "\n\t\t\t\t\t19. Jack Dalrymple\n\t\t\t\t", href2: "https://webflow.grsm.io/sbr?sid1=inspiration/consulting_websites", label: "Webflow", href3: "http://jackdalrymple.com/", alt: "Screenshot of Jack Dalrymple, from the consulting websites collection.", imgSrc: "/assets/cloned/images/0541e6d628b7.webp", description: "Jack is a marketing consultant who built his online presence on Webflow. His consulting website reads almost like a resume for potential clients." }
];

export default function Page() {
  return (
    <>
      <Navbar />
      <HeroSection />
      <ConsultingWebsiteExamplesSection />
      {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} styles={MediaCard_styles[i]} />)}
      {" "}
      <div className="box-content w-288 block max-w-400 mx-16 text-left max-md:w-[337.5px] max-md:mx-[1.175rem] md:max-lg:w-[43.2rem] md:max-lg:mx-[2.4rem] 2xl:w-400 2xl:mx-40">
        <div className="box-content block max-w-190 mx-49 max-lg:mx-0 2xl:mx-105" id="introduction">
          <p className="box-content block my-[1.0625rem] font-light leading-[1.6875rem] max-lg:leading-7">
            .
          </p>
          {" "}
        </div>
        {" "}
      </div>
      <RelatedInspirationCollectionsSection />
      <LogoCloudSection />
      <HowToMakeSection />
      <SiteBuilderReportSection />
      {" "}
    </>
  );
}
