import "./ditto.css";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import FeatureCard from "./components/feature-card";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/artikel", label2: "Artikel" },
    { href: "/newsletter", label2: "Newsletter" },
    { href: "/podcast", label: "Synapsensprung – Wo Technologie, Philosophie und Gesellschaft aufeinandertreffen", label2: "Podcast" },
    { href: "/kai-spriestersbach", label2: "Über mich" }
];
const ListRow2_data = [
    { text: "Information Agents,", text2: " die im Hintergrund 24/7 das Web nach nutzerdefinierten Kriterien beobachten und proaktiv Updates liefern — etwa beim Wohnungssuchen oder bei Sneaker-Drops." },
    { text: "Agentic Booking", text2: " für lokale Dienstleistungen: Karaoke-Raum für sechs Personen am Freitagabend mit später Küche? Google sucht Preise und Verfügbarkeit zusammen und führt zur Buchung beim Anbieter. Für Kategorien wie Home Repair, Beauty oder Pet Care ruft Google die Anbieter „on your behalf“ an." },
    { text: "Agentic Coding direkt in der Suche", text2: " über Antigravity und Gemini 3.5 Flash — mit generativer UI, die in Echtzeit zusammengebaut wird." },
    { text: "Mini-Apps in der Suche,", text2: " die als Custom-Tracker oder Dashboard für wiederkehrende Aufgaben dienen." }
];
const FeatureCard_data = [
    { href: "/skimmer-scanner-reader-gibt-es-nicht", title: "Skimmer, Scanner, Reader: Diese drei Lesertypen gibt es nicht", href2: "/skimmer-scanner-reader-gibt-es-nicht", dateTime: "2026-08-10T13:06:09+02:00", date: "10. August 2026" },
    { href: "/llm-readability-diskurs", title: "LLM Readability: Muss ich meinen Content jetzt für Maschinen umschreiben?", href2: "/llm-readability-diskurs", dateTime: "2026-08-08T17:14:24+02:00", date: "8. August 2026" },
    { href: "/arc-agi-3-gpt-5-6-sol-opus-5-messproblem", title: "ARC-AGI-3: „GPT-5.6 Sol schlägt Opus 5“ – nur ist das kein Vergleich, sondern ein Messproblem", href2: "/arc-agi-3-gpt-5-6-sol-opus-5-messproblem", dateTime: "2026-08-06T16:04:11+02:00", date: "6. August 2026" },
    { href: "/narayanan-icml-2026-was-bleibt-zu-tun", title: "0,22 gegen 0,06: Warum KI-Agenten viel schneller klug werden als verlässlich", href2: "/narayanan-icml-2026-was-bleibt-zu-tun", dateTime: "2026-07-28T16:14:50+02:00", date: "28. Juli 2026" }
];
const ListRow_meta: string[][] = [
    ["n24", "style-5", "style-23"],
    ["n27", "style-6", "style-24"],
    ["n30", "style-7", "style-25"],
    ["n33", "style-8", "style-26"]
];
const ListRow2_meta: string[][] = [
    ["style-li-20", "style-link-5"],
    ["style-span-3", "style-li-21"],
    ["style-link-6", "style-span-4"],
    ["style-footer-nav-2", "style-ul-3"]
];
const FeatureCard_meta: string[][] = [
    ["style-link-13", "style-span-7", "style-p-31", "style-div-4", "style-p-155", "style-p-156", "style-link-14"],
    ["style-div-7", "style-p-192", "style-br", "style-em-2", "style-div-43", "style-div-46", "style-beitragsnavigation"],
    ["style-div-53", "style-span-17", "style-link-15", "style-div-58", "style-link-16", "style-span-38", "style-div-39"],
    ["style-div-40", "style-div-5", "style-heading-51", "style-div-54", "style-ul-20", "style-figure-3", "style-image-35"]
];
const ListRow2_styles = [
    { className: "mt-2" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" },
    { className: "mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" }
];

export default function Page() {
  return (
    <>
      <a className="box-content w-px h-px block absolute top-0 left-0 -m-px overflow-hidden text-primary underline [clip-path:inset(50%)] cursor-pointer" data-ditto-id="style-wp-skip-link" href="#wp--skip-link--target" id="wp-skip-link">
        Zum Inhalt springen
      </a>
      <div className="box-content block">
        <header className="box-content border-b border-solid border-b-clr-0 block [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif]">
          <div className="block">
            <div className="block relative px-5">
              <div className="flex max-w-280 mx-auto py-3.5 justify-between items-center gap-5">
                <div className="block leading-0">
                  <a className="box-content h-[51.7px] inline-block text-primary underline cursor-pointer" data-ditto-id="style-link" data-component="link" href="/" rel="home">
                    <img className="box-content w-30 h-13 inline max-w-full overflow-clip aspect-[auto_318/137]" data-ditto-id="style-image" data-component="image" alt="Afaik min" height="137" src="/assets/cloned/svg/d179f89faeae.svg" width="318" />
                  </a>
                </div>
                {" "}
                <div className="flex justify-end items-center">
                  <nav className="box-content flex relative flex-wrap justify-end items-center gap-5 text-[1.0625rem] font-medium leading-[1.8125rem] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:leading-[1.75rem]" data-component="nav" aria-label="Haupnav">
                    <button className="hidden min-w-0 align-middle leading-[1.3125rem] tracking-[normal] text-center cursor-pointer max-md:flex max-md:leading-[1.1875rem]" aria-haspopup="dialog" aria-label="Menü öffnen">
                      <svg className="box-content w-6 h-6 block overflow-hidden pointer-events-none" aria-hidden="true" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" focusable="false" fill="currentColor">
                        <path d="M4 7.5h16v1.5H4z" />
                        <path d="M4 15h16v1.5H4z" />
                      </svg>
                    </button>
                    {" "}
                    <div className="box-content block relative gap-5 max-md:hidden" data-ditto-id="style-modal-1" id="modal-1">
                      <div className="box-content block gap-5">
                        <div className="box-content block relative gap-5">
                          <div className="box-content flex flex-wrap justify-end items-center gap-5" id="modal-1-content">
                            <ul className="flex relative flex-wrap justify-end items-center gap-5 [list-style-type:none] list-outside">
                              <li className="box-content flex relative items-center" data-ditto-id="style-li">
                                <a className="box-content h-[1.8375rem] block z-1 cursor-pointer md:max-lg:h-[1.775rem]" data-ditto-id="style-link-2" data-component="link" href="/ki-beratung" title="Meine KI-Beratungsleistungen im Detail">
                                  <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-span">
                                    Beratung
                                  </span>
                                </a>
                                <button className="w-[0.65rem] h-[0.65rem] block ml-[4.3px] self-center [font-family:Arial] font-normal leading-0 tracking-[normal] text-center cursor-pointer md:max-lg:w-2.5 md:max-lg:h-2.5 md:max-lg:ml-1" data-ditto-id="style-untermen-von-beratung" data-component="button" aria-expanded="false" aria-label="Untermenü von Beratung">
                                  <svg className="box-content w-auto h-2.5 inline-block mt-[1.3px] overflow-hidden" data-ditto-id="style-icon" data-component="icon" aria-hidden="true" fill="none" height="12" viewBox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg" focusable="false">
                                    <path d="M1.50002 4L6.00002 8L10.5 4" strokeWidth="1.5" />
                                  </svg>
                                </button>
                              </li>
                              {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                              <li className="box-content flex relative items-center" data-ditto-id="style-li-2">
                                <a className="box-content h-[1.8375rem] block z-1 cursor-pointer md:max-lg:h-[1.775rem]" data-ditto-id="style-link-3" data-component="link" href="#">
                                  <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-span-2">
                                    Bücher
                                  </span>
                                </a>
                                <button className="w-[0.65rem] h-[0.65rem] block ml-[4.3px] self-center [font-family:Arial] font-normal leading-0 tracking-[normal] text-center cursor-pointer md:max-lg:w-2.5 md:max-lg:h-2.5 md:max-lg:ml-1" data-ditto-id="style-untermen-von-b-cher" data-component="button" aria-expanded="false" aria-label="Untermenü von Bücher">
                                  <svg className="box-content w-auto h-2.5 inline-block mt-[1.3px] overflow-hidden" data-ditto-id="style-icon-2" data-component="icon" aria-hidden="true" fill="none" height="12" viewBox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg" focusable="false">
                                    <path d="M1.50002 4L6.00002 8L10.5 4" strokeWidth="1.5" />
                                  </svg>
                                </button>
                              </li>
                            </ul>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </nav>
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </header>
        {" "}
        <div className="box-content h-[0.1875rem] block fixed top-0 inset-x-0 z-9999 mt-5 pointer-events-none" aria-hidden="true" />
        {" "}
        <main className="block relative mt-[4.8rem] px-5 max-md:mt-10 md:max-lg:mt-[2.875rem] 2xl:mt-20" id="wp--skip-link--target">
          <article className="block relative max-w-180 mx-auto px-10 max-md:px-5 md:max-lg:px-[30.7px]">
            <div className="block max-w-180 mb-4 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[0.8125rem] font-semibold leading-[1.125rem] tracking-[0.52px] uppercase">
              <a className="box-content inline text-primary whitespace-nowrap text-nowrap cursor-pointer" data-ditto-id="style-figure" data-component="link" href="https://www.afaik.de/kategorie/artikel/" rel="tag">
                Artikel
              </a>
            </div>
            {" "}
            <h1 className="block max-w-230 mt-5 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[5.625rem] font-extrabold leading-[5.5rem] tracking-[-5.82px] [word-break:break-word] text-pretty max-md:text-[3.0625rem] max-md:leading-[3rem] max-md:tracking-[-2.68px] md:max-lg:text-[3.625rem] md:max-lg:leading-[3.5rem] md:max-lg:tracking-[-3.74px]" data-component="heading">
              Habe ich mich bei der llms.txt geirrt? Drei Signale, die das Bild verschieben.
            </h1>
            {" "}
            <div className="flex max-w-180 mt-8 items-center gap-3 text-muted-foreground [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[0.9375rem] leading-[1.375rem] max-md:mt-[1.3rem] max-md:items-start md:max-lg:mt-[1.4375rem]" data-ditto-id="style-div-62">
              {" "}
              <div className="block relative" data-ditto-id="style-div-14">
                <div className="block max-w-180 text-[0.9375rem] font-semibold leading-[1.3125rem]" data-ditto-id="style-heading-13">
                  <a className="box-content inline text-foreground font-medium cursor-pointer" data-ditto-id="style-p" data-component="link" href="https://www.afaik.de/author/kaiadmin/" target="_self">
                    Kai Spriestersbach
                  </a>
                </div>
                {" "}
                <div className="flex max-w-180 mt-5 flex-wrap items-center gap-1.5" data-ditto-id="style-form-2">
                  <div className="block text-[0.9375rem] leading-[1.3125rem]" data-ditto-id="style-label">
                    <time className="box-content inline" dateTime="2026-05-27T17:29:43+02:00">
                      27. Mai 2026
                    </time>
                  </div>
                  {" "}
                  <p className="box-content block leading-[1.625rem] text-pretty" data-ditto-id="style-wp-block-search-input-2">
                    ·
                  </p>
                  {" "}
                  <p className="box-content block leading-[1.625rem] text-pretty" data-ditto-id="style-suchen">
                    <span className="box-content inline" data-ditto-id="style-footer">
                      9 Min. Lesezeit
                    </span>
                  </p>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <figure className="box-content block relative max-w-180 mt-19 mb-16 aspect-video max-md:mt-9 max-lg:mb-10 md:max-lg:mt-[2.875rem]" data-ditto-id="style-div-64">
              <img className="w-160 h-90 block max-w-full rounded-[3px] overflow-clip object-cover aspect-[auto_2514/1416] align-bottom max-md:w-[18.4375rem] max-md:h-41.5 md:max-lg:w-[41.1875rem] md:max-lg:h-92.5" data-ditto-id="style-div-21" data-component="image" alt="Screenshot" height="1416" sizes="(max-width: 2514px) 100vw, 2514px" src="/assets/cloned/images/24467f97420f.jpg" srcSet="/assets/cloned/images/24467f97420f.jpg 2514w, /assets/cloned/images/f155ea2497d6.jpg 1024w, /assets/cloned/images/3bc751943436.jpg 2048w, /assets/cloned/images/bc5926703fe6.jpg 768w" width="2514" />
            </figure>
            {" "}
            <div className="box-content flow-root max-w-180 mt-5 [font-family:Georgia,_'Times_New_Roman',_Times,_serif]" data-ditto-id="style-div-44">
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-link-4">
                <strong className="box-content inline font-bold" data-ditto-id="style-image-2">
                  Im Februar habe ich die llms.txt zum Rohrkrepierer erklärt. Drei Monate später muss ich präzisieren: Als GEO-Maßnahme bleibt sie tot. Als Discovery-Datei für agentische Systeme könnte sie genau das werden, was Jeremy Howard ursprünglich im Sinn hatte.
                </strong>
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-div-2">
                {"Wer meinen Februar-Artikel "}
                <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-div-65" data-component="link" href="https://www.afaik.de/die-llms-txt-ist-tot/">
                  „Die llms.txt ist tot“
                </a>
                {" gelesen hat, weiß: Ich habe wenig zimperlich argumentiert. 0,1 Prozent der KI-Bot-Requests in OtterlyAIs 90-Tage-Messung. John Mueller, der die Datei mit dem Keywords-Meta-Tag vergleicht. Vier strukturelle Gründe, warum kein KI-Suchsystem im Retrieval-Stack eine vom Seitenbetreiber kuratierte Inhaltsbeschreibung als vertrauenswürdiges Signal verwenden würde."}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-div-6">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-9">
                  An dieser Analyse ändert sich nichts. Wer eine llms.txt erstellt, um besser in ChatGPT, Perplexity oder den Google AI Overviews zu erscheinen, verschwendet weiterhin Zeit. Aber drei Entwicklungen der letzten Wochen zwingen mich, die Frage anders zu stellen.
                </strong>
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-div" data-component="heading">
                Signal 1: Google I/O 2026 — Search ist jetzt agentisch
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-div-45">
                {"Am 19. Mai hat Liz Reid auf der I/O das vorgestellt, was Google "}
                <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-div-63" data-component="link" href="https://blog.google/products-and-platforms/products/search/search-io-2026/" rel="noopener" target="_blank">
                  „a new era for AI Search“
                </a>
                {" nennt. Die nüchterne Übersetzung: Suche ist nicht mehr nur Retrieval. Suche wird Task-Ausführung."}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-footer-nav">
                Was Google angekündigt hat, ist in Summe ein Paradigmenwechsel:
              </p>
              {" "}
              <ul className="block max-w-180 mt-5 pl-[30.5px] text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] [list-style-type:disc] list-outside max-md:pl-[26.1px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:pl-[1.6875rem] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:pl-[31.3px] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-ul-17">
                {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
              </ul>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-li-25">
                {"Der entscheidende Punkt für unsere Frage: Diese Agenten "}
                <strong className="box-content inline font-bold" data-ditto-id="style-link-7">
                  besuchen Websites, navigieren durch URL-Strukturen, lesen Detailseiten, vergleichen, buchen, rufen an
                </strong>
                . Sie sind keine klassischen Indexer, die einmalig crawlen und in einem Embedding-Index landen. Sie sind Operatoren, die zur Inferenzzeit auf live Inhalte zugreifen — mit einem konkreten Task im Kontext.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-span-5">
                Genau für diesen Anwendungsfall war llms.txt von Anfang an gedacht. Howards Originaltext spricht von „inference-time use cases“ und zielt explizit auf Tools wie Cursor und Claude Code. Was 2024 nach einem Nischen-Use-Case für Coding-Assistenten klang, ist 2026 die Standardoperation jedes Mainstream-Suchanbieters.
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-li-23" data-component="heading">
                Signal 2: Chrome Lighthouse prüft die llms.txt
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-link-8">
                {"Am 5. Mai 2026 tauchte in den Chrome-Developer-Docs ein neuer Lighthouse-Audit auf: "}
                <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-span-6" data-component="link" href="https://developer.chrome.com/docs/lighthouse/agentic-browsing/llms-txt" rel="noopener" target="_blank">
                  llms.txt
                </a>
                {", eingeordnet unter der Rubrik "}
                <strong className="box-content inline font-bold" data-ditto-id="style-div-66">
                  Agentic browsing audits
                </strong>
                .
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-div-3">
                Die Formulierung ist vorsichtig. Lighthouse markiert den Audit als „Not Applicable“, wenn die Datei fehlt — „providing the file is optional at the moment“. Geflagged wird nur, wenn der Server bei Abruf einen Fehler liefert. Das ist weit entfernt von einem Ranking-Faktor.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-10">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-199">
                  Trotzdem ist die symbolische Bedeutung erheblich. Erstens kommt diese Dokumentation aus dem Hause Google — dem gleichen Konzern, der im Februar via Mueller und Illyes explizit klargestellt hatte, dass keine offizielle Unterstützung geplant sei. Zweitens — und das ist der wichtigere Punkt — wird llms.txt unter „Agentic browsing audits“ einsortiert, nicht unter „SEO audits“. Die Kategorie zählt.
                </strong>
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-link-9">
                Lighthouse sagt damit: Wenn Agenten deine Seite besuchen, ist eine maschinenlesbare Zusammenfassung dessen, was deine Seite anbietet und wie sie strukturiert ist, ein hilfreicher Baustein. Ohne diese Datei verbringen Agenten mehr Zeit damit, die Seitenstruktur zu rekonstruieren. Das ist eine sehr andere Aussage als „die Datei hilft beim Ranking“.
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-p-176" data-component="heading">
                Signal 3: Eine neue Use-Case-Kategorie wird sichtbar
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-blockquote-15">
                Im Februar habe ich „publizieren“ und „konsumieren“ als Verwechslung beschrieben: Dass Anthropic, OpenAI und Perplexity llms.txt-Dateien auf ihren Developer-Docs haben, sagt nichts darüber aus, ob ihre Retrieval-Systeme die llms.txt anderer Sites lesen. Das stimmt weiterhin.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-200">
                <strong className="box-content inline font-bold" data-ditto-id="style-ftnref1">
                  Was ich aber unterbelichtet habe: Es gibt einen dritten Modus jenseits von „publizieren für die eigene Sichtbarkeit“ und „konsumieren im Retrieval“.
                </strong>
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-201">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-181">
                  Es gibt das Szenario, in dem ein Agent — aus welchem Grund auch immer — sich entschieden hat, deine Seite zu besuchen, und nun eine konkrete Aufgabe abarbeiten soll.
                </strong>
                {" Der Agent hat dich nicht „gefunden“, weil er deine llms.txt gelesen hat. Er hat dich gefunden, weil ihn der Nutzer dort hingeschickt hat oder weil ein klassisches Retrieval ihn dort hingeführt hat. Aber sobald er da ist, hat er ein Problem: "}
                <strong className="box-content inline font-bold" data-ditto-id="style-ftnref2">
                  Welche URLs sind die richtigen Einstiegspunkte für seine Aufgabe? Wie sind die Slugs aufgebaut? Welche Aktionen darf er ohne Bestätigung ausführen, welche nicht?
                </strong>
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-151">
                Für dieses Problem ist eine gut gepflegte llms.txt eine plausible Lösung. Nicht als Ranking-Signal. Sondern als Operating Manual.
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-em-8" data-component="heading">
                Was meine ursprüngliche These nicht erfasst hat
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-204">
                Beides kann gleichzeitig wahr sein:
              </p>
              {" "}
              <ol className="block max-w-180 mt-5 pl-[30.5px] text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] [list-style-type:decimal] list-outside max-md:pl-[26.1px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:pl-[1.6875rem] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:pl-[31.3px] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-202">
                <li className="box-content list-item mt-2" data-ditto-id="style-cite-3">
                  llms.txt als GEO-Hebel ist gescheitert und wird scheitern. Die strukturellen Gründe — Manipulationsanfälligkeit, Retrieval-Ineffizienz, Redundanz zur robots.txt, fehlende Adoption auf Consumer-Seite — gelten unverändert.
                </li>
                <li className="box-content list-item mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" data-ditto-id="style-link-23">
                  llms.txt als agentische Discovery-Datei ist im aufkommenden Browsing-Stack potenziell nützlich. Hier zählt nicht, ob ein Embedding-Index die Datei einmal pro Quartal crawlt. Hier zählt, ob ein Agent zur Inferenzzeit damit schneller zur richtigen URL kommt.
                </li>
              </ol>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-206">
                Diese zwei Anwendungen sind nicht das gleiche Produkt mit zwei Namen. Sie haben unterschiedliche Adressaten, unterschiedliche Erfolgskriterien und unterschiedliche Designprinzipien. Eine llms.txt, die als „Pitch an Crawler“ geschrieben ist, ist für agentische Nutzung untauglich. Eine llms.txt, die als „Bedienungsanleitung für Agenten“ geschrieben ist, hat in der GEO-Welt nichts verloren.
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-p-203" data-component="heading">
                Wie eine agentische llms.txt aussieht: drei Beispiele aus dem deutschen Telefonbuchmarkt
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong">
                {"Um zu zeigen, was ich meine, habe ich drei Beispieldateien für gut bekannte deutsche Verzeichnisdienste gebaut — "}
                <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-hr" data-component="link" href="https://www.afaik.de/wp-content/uploads/2026/05/gelbeseiten-llms-agentic.txt" rel="noopener" target="_blank">
                  Gelbe Seiten
                </a>
                {", "}
                <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-heading-48" data-component="link" href="https://www.afaik.de/wp-content/uploads/2026/05/dastelefonbuch-llms-agentic.txt" rel="noopener" target="_blank">
                  Das Telefonbuch
                </a>
                {" und "}
                <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-p-11" data-component="link" href="https://www.afaik.de/wp-content/uploads/2026/05/dasoertliche-llms-agentic.txt" rel="noopener" target="_blank">
                  Das Örtliche
                </a>
                . Die Wahl ist kein Zufall: Branchen- und Personenverzeichnisse sind ein Lehrbuchfall für agentische Aufgaben und könnten den Plattformen zu neuer Relevanz für KI-Systeme verhelfen, wenn man nicht gerade Google mit Zugriff auf Google Maps oder Apple mit Apple Maps ist.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-blockquote-2">
                „Friseur in Berlin-Mitte mit Öffnungszeit Samstag“, „Rückwärtssuche zu dieser Telefonnummer“, „Notapotheke in der Nähe“ — das sind exakt die Tasks, die Information Agents und Agentic Booking aus Reids Keynote bedienen sollen.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-185">
                {"Was in diesen Dateien steht, ist explizit "}
                <strong className="box-content inline font-bold" data-ditto-id="style-strong-135">
                  keine
                </strong>
                {" Marketing-Beschreibung der Plattform. Es sind sechs Dinge:"}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-186">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-187">
                  Erstens: Eine knappe Intent-Beschreibung.
                </strong>
                {" Wofür ist diese Seite zuständig, wofür nicht? Beispiel aus der Datei für Das Örtliche: Lokale Kontakt-, Telefonbuch- und Branchensuche; für stark gewerbliche Dienstleisterauswahl kann Gelbe Seiten ergänzend sinnvoll sein. Das ist eine Routing-Empfehlung, keine Werbung."}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-128">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-213">
                  Zweitens: URL-Patterns, die ein Agent direkt zur Resolution nutzen kann.
                </strong>
                {" Statt einen Agenten erst die Suchmaske parsen zu lassen, gebe ich ihm das kanonische Muster:"}
              </p>
              {" "}
              <ul className="block max-w-180 mt-5 pl-[30.5px] text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] [list-style-type:disc] list-outside max-md:pl-[26.1px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:pl-[1.6875rem] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:pl-[31.3px] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-130">
                <li className="box-content list-item mt-2" data-ditto-id="style-p-205">
                  <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-blockquote-3">
                    {"https://www.gelbeseiten.de/branchen/{branche-slug}/{ort-slug}"}
                  </code>
                  {" für Branchen-Ortslisten"}
                </li>
                <li className="box-content list-item mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" data-ditto-id="style-p-207">
                  <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-p-23">
                    {"https://www.dastelefonbuch.de/Branchen/{branche-slug}/{ort-slug}"}
                  </code>
                  {" mit dem Hinweis, dass Stadtteile via doppeltem Bindestrich angehängt werden ("}
                  <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-blockquote-4">
                    Berlin--Biesdorf
                  </code>
                  )
                </li>
                <li className="box-content list-item mt-[0.725rem] max-lg:mt-2.5 2xl:mt-3" data-ditto-id="style-p-152">
                  <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-p-24">
                    {"https://www.dasoertliche.de/Themen/{thema-slug}/{ort-slug}.html"}
                  </code>
                  {" mit Query-Fallback, wenn das Thema nicht kanonisch ist"}
                </li>
              </ul>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-hr-2">
                <strong className="box-content inline font-bold" data-ditto-id="style-heading-40">
                  Drittens: Normalisierungsregeln.
                </strong>
                {" „Frankfurt am Main“ wird in der einen Plattform mit URL-kodierten Leerzeichen geschrieben, in der anderen mit Bindestrichen verbunden. Umlaute werden mal kodiert, mal nicht. Berliner Bezirke folgen einem Sondermuster ("}
                <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-p-25">
                  berlin%20bezirk%20mitte
                </code>
                ). Ohne diese Hinweise rät der Agent — und scheitert in 30 Prozent der Fälle.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-26">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-16">
                  Viertens: Resolver-Workflows.
                </strong>
                {" „Nutzeranfrage zerlegen in Branche, Ort, optional Stadtteil und Zeitwunsch. Wenn ein kanonisches Thema bekannt ist, /Themen aufrufen, sonst Query-Fallback.“ Das ist Pseudocode für agentisches Verhalten."}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-blockquote-6">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-27">
                  Fünftens: Bestätigungs- und Datenschutzgrenzen.
                </strong>
                {" Bei Aktionen wie Anrufen, Reservieren, Routenplanung oder Kontaktanlage muss der Agent "}
                <strong className="box-content inline font-bold" data-ditto-id="style-strong-136">
                  vor Ausführung den Nutzer bestätigen lassen
                </strong>
                . Personenbezogene Treffer dürfen nicht massenhaft profiliert werden. Diese Regeln gehören in die llms.txt, weil sie genau zur Inferenzzeit gebraucht werden, in der ein Agent gerade kurz davor ist, etwas Unwiderrufliches zu tun.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-183">
                <strong className="box-content inline font-bold" data-ditto-id="style-hr-6">
                  Sechstens: Discovery-Links.
                </strong>
                {" robots.txt, Sitemaps, Impressum, Datenschutz. Das ist nichts Magisches — aber es ist genau das, was ein Agent als Erstes braucht, um sich auf der Domain zu orientieren."}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-heading-17">
                {"Was diese drei Dateien gemeinsam haben: Sie sind "}
                <strong className="box-content inline font-bold" data-ditto-id="style-p-86">
                  nicht
                </strong>
                {" „kuratierte Inhaltsbeschreibung gegenüber einem Crawler“. Sie sind eine "}
                <strong className="box-content inline font-bold" data-ditto-id="style-p-12">
                  API-artige Dokumentation der Site-Logik
                </strong>
                . Wer sie liest, ist nicht der Indexer, sondern der Operator.
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-p-17" data-component="heading">
                Konkrete Empfehlungen für die nächsten Wochen
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-2">
                Wenn du heute überlegst, was du tun sollst, würde ich nach drei Kategorien sortieren:
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-208">
                <strong className="box-content inline font-bold" data-ditto-id="style-heading">
                  Wenn du eine Entwickler-Dokumentation hast — JETZT.
                </strong>
                {" Wer eine API anbietet, ein SDK pflegt, ein Framework dokumentiert oder eine technische Spezifikation veröffentlicht, sollte heute eine llms.txt bereitstellen und idealerweise auch Markdown-Versionen der relevanten Dokumentationsseiten ausliefern (etwa unter "}
                <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-p-28">
                  /seite.md
                </code>
                {" neben "}
                <code className="box-content inline py-[2.3px] px-[5.3px] rounded-sm [font-family:ui-monospace,_SFMono-Regular,_Menlo,_Monaco,_Consolas,_'Liberation_Mono',_'Courier_New',_monospace] text-[1.1875rem] leading-[2.0625rem] bg-surface max-lg:py-0.5 max-md:px-[4.5px] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:px-[4.7px] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.8125rem] 2xl:px-[0.3375rem]" data-ditto-id="style-blockquote-13">
                  /seite.html
                </code>
                ). Das war Jeremy Howards Original-Use-Case, das ist das, wofür Mintlify, Anthropic und Cursor die Dateien haben, und das ist der Bereich, in dem die Adoption durch Coding Agents real ist. Hier zahlt sich die Investition unmittelbar aus, weil deine API von einem Cursor- oder Claude-Code-Nutzer schneller verstanden und korrekt eingesetzt wird.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-195">
                <strong className="box-content inline font-bold" data-ditto-id="style-strong-129">
                  Wenn du einen Service anbietest, der agentisch genutzt werden könnte — denk in Szenarien.
                </strong>
                {" Beispiele: Verzeichnisdienste, Buchungsplattformen, Marktplätze, lokale Dienstleister, Kartenanwendungen, Behörden-Services. Frag dich: Was würde ein Information Agent von Google bei einer typischen Nutzeranfrage auf meiner Seite tun müssen? Welche URLs sind die richtigen Einstiegspunkte? Welche Aktionen sind reversibel, welche nicht? Welche Datenschutzgrenzen muss ein Agent kennen? Daraus entsteht eine sinnvolle llms.txt, die — ob sie heute schon gelesen wird oder nicht — als interne Klärungsübung wertvoll ist."}
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-87">
                <strong className="box-content inline font-bold" data-ditto-id="style-p-18">
                  Wenn du eine klassische Content-Site betreibst — abwarten und beobachten.
                </strong>
                {" Für News-Seiten, Magazine, Corporate Sites, Blogs gilt meine Februar-Analyse weiterhin: Eine llms.txt als Sichtbarkeits-Hebel zu pflegen ist Opportunitätskosten ohne nachweisbaren Nutzen. Wenn die Adoption sich verschiebt, lässt sich eine Datei in einer Stunde generieren. Wer jetzt Zeit investiert, sollte sie in Content-Qualität und Zitierfähigkeit stecken."}
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-p-177" data-component="heading">
                Was bleibt richtig
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-strong-134">
                OtterlyAIs 0,1-Prozent-Zahl ist immer noch die belastbarste Datenquelle, die wir haben. Mueller und Illyes haben ihre Position nicht widerrufen. Die strukturellen Argumente gegen llms.txt als Retrieval-Signal — Manipulationsanfälligkeit, Effizienz-Probleme im Retrieval-Stack, Redundanz zur robots.txt — sind unverändert gültig.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-hr-7">
                Wer nach diesem Artikel zurück ans Whiteboard geht und in den nächsten GEO-Audit „llms.txt erstellen und optimieren“ als Workstream schreibt, hat ihn missverstanden. Die llms.txt ist weiterhin kein Ranking-Hebel. Sie wird auch keiner werden.
              </p>
              {" "}
              <h2 className="box-content block max-w-180 mt-[5.0375rem] mb-[1.2rem] [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.75rem] tracking-[-1.34px] text-pretty max-lg:mt-[3.8875rem] max-lg:mb-[0.925rem] max-lg:text-3xl max-lg:leading-[2.125rem] max-lg:tracking-[-1.04px] 2xl:mt-[5.4625rem] 2xl:mb-[1.3rem] 2xl:text-[2.625rem] 2xl:leading-[2.9375rem] 2xl:tracking-[-1.46px]" data-ditto-id="style-heading-49" data-component="heading">
                Fazit
              </h2>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-153">
                <strong className="box-content inline font-bold" data-ditto-id="style-ol-3">
                  Mein Februar-Titel war zugespitzt. Das war Absicht, und die Pointe trifft die Sache, die ich angreifen wollte: llms.txt als GEO-Maßnahme.
                </strong>
              </p>
              {" "}
              <blockquote className="border-l-[3px] border-solid border-l-foreground block max-w-180 my-9 py-[0.15rem] pl-[1.35rem] font-light leading-[2rem] [overflow-wrap:break-word] text-pretty max-md:leading-[1.6875rem] md:max-lg:leading-[1.875rem]" data-ditto-id="style-p-196">
                <p className="box-content block text-[1.75rem] leading-[2.5rem] max-md:text-[1.375rem] max-md:leading-[1.9375rem] md:max-lg:text-2xl md:max-lg:leading-[2.125rem] 2xl:text-[1.8125rem] 2xl:leading-[2.625rem]" data-ditto-id="style-em-9">
                  Was ich nicht ausreichend gewürdigt habe: Mit der Verschiebung von „Search als Retrieval“ zu „Search als Task-Ausführung“ entsteht eine zweite Klasse von Nutzungsszenarien. In diesen Szenarien ist eine gut gepflegte llms.txt keine Marketing-Datei, sondern eine Bedienungsanleitung. Sie wird nicht von einem Crawler gewichtet — sie wird von einem Operator gelesen, der gerade eine Aufgabe abarbeitet.
                </p>
                {" "}
              </blockquote>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-ul-18">
                Diese Lesart ist näher an Jeremy Howards Originalvorschlag von September 2024 als die GEO-Interpretation, die im Frühjahr 2025 viral ging. Vielleicht war die llms.txt nie tot. Vielleicht war sie nur in einer Diskussion gefangen, die mit ihrem eigentlichen Zweck wenig zu tun hatte.
              </p>
              {" "}
              <p className="box-content block max-w-180 my-6 text-[1.3125rem] leading-[2.25rem] tracking-[-0.06px] text-pretty max-md:my-[20.7px] max-md:text-lg max-md:leading-[1.875rem] max-md:tracking-[-0.05px] md:max-lg:my-[21.3px] md:max-lg:text-[1.1875rem] md:max-lg:leading-8 2xl:my-[1.55rem] 2xl:leading-[2.3125rem] 2xl:[font-size:inherit] 2xl:tracking-[inherit]" data-ditto-id="style-p-19">
                <strong className="box-content inline font-bold" data-ditto-id="style-ul-8">
                  Wenn die agentische Suche das wird, was Google auf der I/O versprochen hat, dann werden wir alle in den nächsten Monaten darüber nachdenken, welche URLs unserer Sites für welche Tasks die richtigen sind — und wie wir das einem Agenten in einer halben Seite Markdown erklären. Das ist eine Konversation, die es wert ist, geführt zu werden. Sie hat nur nicht das Etikett verdient, unter dem sie 2025 vermarktet wurde.
                </strong>
              </p>
              {" "}
              <div className="box-content block max-w-180 mt-[2.7rem] p-8 text-background bg-muted max-md:mt-[36.5px] md:max-lg:mt-10" data-ditto-id="style-li-4" id="newsletter-leads-bottom">
                <h2 className="box-content block my-8 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] text-[2.375rem] [font-weight:750] leading-[2.6875rem] tracking-[-1.54px] text-pretty max-md:my-[1.4125rem] max-md:text-[1.6875rem] max-md:leading-[1.9375rem] max-md:tracking-[-1.09px] md:max-lg:my-[27.5px] md:max-lg:text-[2.0625rem] md:max-lg:leading-[2.3125rem] md:max-lg:tracking-[-1.32px]" data-ditto-id="style-em-7" data-component="heading">
                  Abonniere das AFAIK-Update
                </h2>
                {" "}
                <p className="box-content block my-[1.35rem] leading-[2.3125rem] text-pretty max-md:my-[1.1375rem] max-md:leading-[1.9375rem] md:max-lg:my-5 md:max-lg:leading-[2.125rem]" data-ditto-id="style-p-194">
                  <strong className="box-content inline font-bold" data-ditto-id="style-strong-133">
                    Bleib auf dem Laufenden in Sachen Künstliche Intelligenz im Online Marketing!
                  </strong>
                </p>
                {" "}
                <p className="box-content block my-[1.35rem] leading-[2.3125rem] text-pretty max-md:my-[1.1375rem] max-md:leading-[1.9375rem] md:max-lg:my-5 md:max-lg:leading-[2.125rem]" data-ditto-id="style-p-184">
                  Melde Dich jetzt mit Deiner E-Mail-Adresse an und ich versorge Dich kostenlos mit News-Updates, Tools, Tipps und Empfehlungen Rund um KI aus den Bereichen Online-Marketing, SEO, GEO, WordPress und vieles mehr.
                </p>
                <div className="box-content block max-w-125" data-ditto-id="style-hr-3">
                  <form className="box-content block" data-ditto-id="style-heading-47">
                    {" "}
                    <div className="box-content block mb-[15.1px] max-md:mb-[0.8rem] md:max-lg:mb-3.5" data-ditto-id="style-p-154">
                      <label className="box-content block mb-[4.9px] text-[1.1875rem] leading-5.5 cursor-default max-md:mb-1 max-md:text-base max-md:leading-5 md:max-lg:mb-[4.5px] md:max-lg:text-lg md:max-lg:leading-[1.3125rem]" data-ditto-id="style-em-10" htmlFor="tnp-1">
                        Dein Vorname
                      </label>
                      {" "}
                      <input className="w-full h-14 block p-[15.1px] overflow-clip text-muted [font-family:Arial] leading-6.5 tracking-[normal] bg-surface-3 cursor-text max-md:h-12 max-md:p-[0.8rem] max-md:leading-5.5 md:max-lg:h-[3.1875rem] md:max-lg:p-3.5 md:max-lg:leading-[1.4375rem]" data-ditto-id="style-em-12" data-component="input" id="tnp-1" name="nn" type="text" value="" />
                    </div>
                    {" "}
                    <div className="box-content block mb-[15.1px] max-md:mb-[0.8rem] md:max-lg:mb-3.5" data-ditto-id="style-p-209">
                      <label className="box-content block mb-[4.9px] text-[1.1875rem] leading-5.5 cursor-default max-md:mb-1 max-md:text-base max-md:leading-5 md:max-lg:mb-[4.5px] md:max-lg:text-lg md:max-lg:leading-[1.3125rem]" data-ditto-id="style-heading-2" htmlFor="tnp-2">
                        Deine beste E-Mail Adresse
                      </label>
                      {" "}
                      <input className="w-full h-14 block p-[15.1px] overflow-clip text-muted [font-family:Arial] leading-6.5 tracking-[normal] bg-surface-3 cursor-text max-md:h-12 max-md:p-[0.8rem] max-md:leading-5.5 md:max-lg:h-[3.1875rem] md:max-lg:p-3.5 md:max-lg:leading-[1.4375rem]" data-ditto-id="style-p-178" data-component="input" id="tnp-2" name="ne" type="email" value="" />
                    </div>
                    {" "}
                    <div className="box-content block mb-[15.1px] max-md:mb-[0.8rem] md:max-lg:mb-3.5" data-ditto-id="style-p-20">
                      <label className="box-content block mb-[4.9px] text-[1.1875rem] leading-5.5 cursor-default max-md:mb-1 max-md:text-base max-md:leading-5 md:max-lg:mb-[4.5px] md:max-lg:text-lg md:max-lg:leading-[1.3125rem]" data-ditto-id="style-ul-2">
                        <input className="w-[0.8125rem] h-[0.8125rem] inline-block max-w-[13.3px] my-[0.1875rem] mr-[6.7px] ml-1 text-color-001 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] tracking-[normal]" data-ditto-id="style-p-88" data-component="input" name="ny" type="checkbox" />
                        {" "}
                        <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-p-197" data-component="link" href="/datenschutz" target="_blank">
                          Ich akzeptiere die Einwilligungserklärung.
                        </a>
                      </label>
                    </div>
                    <div className="box-content block mb-[15.1px] text-left max-md:mb-[0.8rem] md:max-lg:mb-3.5" data-ditto-id="style-em-11">
                      <input className="w-[11.0625rem] h-14 inline-block p-[15.1px] overflow-clip [font-family:Arial] leading-6.5 tracking-[normal] text-center whitespace-pre text-nowrap bg-color-005 cursor-default max-md:w-[14.4375rem] max-md:h-12 max-md:p-[0.8rem] max-md:leading-5.5 md:max-lg:w-41 md:max-lg:h-[3.1875rem] md:max-lg:p-3.5 md:max-lg:leading-[1.4375rem]" data-ditto-id="style-p-21" data-component="button" type="submit" value="Jetzt anmelden" />
                      {" "}
                    </div>
                    {" "}
                  </form>
                  {" "}
                </div>
                {" "}
                <p className="box-content block my-[1.35rem] leading-[2.3125rem] text-pretty max-md:my-[1.1375rem] max-md:leading-[1.9375rem] md:max-lg:my-5 md:max-lg:leading-[2.125rem]" data-ditto-id="style-strong-74">
                  <em className="box-content inline italic" data-ditto-id="style-p-22">
                    Keine Sorge, ich mag Spam genauso wenig wie Du und gebe Deine Daten niemals weiter! Du bekommst höchstens einmal pro Monat eine E-Mail von mir. Versprochen.
                  </em>
                </p>
              </div>
            </div>
            {" "}
            <div className="block relative max-w-180 mt-20 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] max-md:mt-10 md:max-lg:mt-[3.3625rem]" data-ditto-id="style-p-29">
              <nav className="box-content border-t border-solid border-t-clr-2 border-b border-b-clr-2 flex max-w-180 py-[0.9rem] flex-wrap items-center gap-4 text-muted-foreground text-[0.9375rem] leading-[1.625rem]" data-ditto-id="style-p-188" data-component="nav" aria-label="Beitrag teilen">
                <span className="box-content block" data-ditto-id="style-blockquote-14">
                  Teilen
                </span>
                <a className="box-content block text-foreground font-medium cursor-pointer" data-ditto-id="style-p-77" data-component="link" href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fwww.afaik.de%2Fllms-txt-agentic-search%2F" rel="noopener noreferrer" target="_blank">
                  LinkedIn
                </a>
                <a className="box-content block text-foreground font-medium cursor-pointer" data-ditto-id="style-strong-3" data-component="link" href={"mailto:?subject=Habe%20ich%20mich%20bei%20der%20llms.txt%20geirrt%3F%20Drei%20Signale%2C%20die%20das%20Bild%20verschieben.&body=https%3A%2F%2Fwww.afaik.de%2Fllms-txt-agentic-search%2F"}>
                  E-Mail
                </a>
                <button className="block text-foreground font-medium tracking-[normal] text-center cursor-pointer" data-ditto-id="style-newsletter-leads-bottom" data-component="button" type="button">
                  Link kopieren
                </button>
              </nav>
              {" "}
              <section className="box-content border-t border-solid border-t-clr-0 grid max-w-180 mt-16 pt-7 items-start gap-4 grid-cols-[auto_1fr] max-md:mt-10 max-md:grid-cols-[56px_223px] md:max-lg:mt-[2.875rem]" data-ditto-id="style-heading-3" aria-label="Autoreninformation">
                <a className="box-content flex text-primary leading-0 underline cursor-pointer" data-ditto-id="style-p-30" data-component="link" href="https://www.afaik.de/author/kaiadmin/">
                  <span className="box-content w-18 h-18 flex rounded-[999px] justify-center items-center aspect-square text-foreground text-[1.375rem] [font-weight:750] bg-surface max-md:w-14 max-md:h-14" data-ditto-id="style-strong-21" aria-hidden="true">
                    K
                  </span>
                </a>
                <p className="box-content block my-[1.35rem] leading-[2.3125rem] text-pretty max-md:my-[1.1375rem] max-md:leading-[1.9375rem] md:max-lg:my-5 md:max-lg:leading-[2.125rem]" data-ditto-id="style-p-36" />
                {" "}
                <div className="box-content block" data-ditto-id="style-div-12">
                  <p className="box-content block text-muted-foreground text-[0.8125rem] font-semibold leading-[1.4375rem] tracking-[0.26px] uppercase text-pretty" data-ditto-id="style-form">
                    Geschrieben von
                  </p>
                  {" "}
                  <p className="box-content block mt-[3.5px] font-bold leading-[2.3125rem] text-pretty max-md:leading-[1.9375rem] md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-51">
                    <a className="box-content inline cursor-pointer" data-ditto-id="style-label-2" data-component="link" href="https://www.afaik.de/author/kaiadmin/">
                      Kai Spriestersbach
                    </a>
                  </p>
                  {" "}
                  <div className="box-content block mt-[0.6rem] text-muted-foreground text-[0.9375rem] leading-[1.5rem]" data-ditto-id="style-tnp-1">
                    <p className="box-content block leading-[1.625rem] text-pretty" data-ditto-id="style-div-52">
                      Kai Spriestersbach ist KI-Forscher, Autor und Head of AI bei einer Online-Marketing-Agentur. Er hat einen Master of Science in Web-Wissenschaften von der TH Köln und promoviert an der RPTU im Bereich angewandter KI (PhD in CS) und bringt über 20 Jahre SEO-Erfahrung mit. Seine Schwerpunkte liegen im Bereich GEO sowie der Entwicklung KI-gestützter Tools und Workflows. Er hat mehrere Bücher über künstliche Intelligenz veröffentlicht, unter anderem den Bestseller „Richtig texten mit KI“.
                      <br className="box-content inline" data-ditto-id="style-label-3" />
                      {" "}
                      <em className="box-content inline italic" data-ditto-id="style-tnp-2">
                        KI-Hinweis: Kai nutzt Claude von Anthropic als Schreibwerkzeug und ChatGPT Pro als Denkhilfe. Alle Inhalte sind von ihm konzipiert, redigiert und auf Korrektheit geprüft.
                      </em>
                    </p>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              {" "}
            </div>
            {" "}
          </article>
          {" "}
          <div className="border-t border-solid border-t-clr-0 block relative max-w-180 mt-14 mx-auto pt-6 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] max-md:mt-9 md:max-lg:mt-[2.4rem]" data-ditto-id="style-div-8">
            <div className="block max-w-180 my-16 max-md:my-9 md:max-lg:my-[2.4rem]" data-ditto-id="style-label-4">
              <nav className="border-t border-solid border-t-clr-0 flex py-5 justify-between items-center gap-5" data-ditto-id="style-input" data-component="nav" aria-label="Beitragsnavigation">
                <div className="box-content block text-[1.0625rem] leading-[1.8125rem] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:leading-[1.75rem]" data-ditto-id="style-link-10">
                  <span className="box-content inline-block mr-[0.6rem] max-md:mr-[0.5625rem] md:max-lg:mr-[9.3px]" data-ditto-id="style-div-32" aria-hidden="true">
                    ←
                  </span>
                  <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-button-2" data-component="link" href="/schema-org-knowledge-graph-ki-suche" rel="prev">
                    Mit Schema.org in den Knowledge Graph der KI-Suche?
                  </a>
                </div>
                {" "}
                <div className="box-content block text-[1.0625rem] leading-[1.8125rem] max-md:text-base max-md:leading-[1.6875rem] md:max-lg:leading-[1.75rem]" data-ditto-id="style-p-13">
                  <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-em" data-component="link" href="/wissenschaft-im-geo" rel="next">
                    Vom Bauchgefühl zur Evidenz: Warum GEO wissenschaftlicher arbeiten muss
                  </a>
                  <span className="box-content inline-block ml-[0.6rem] max-md:ml-[0.5625rem] md:max-lg:ml-[9.3px]" data-ditto-id="style-div-9" aria-hidden="true">
                    →
                  </span>
                </div>
                {" "}
              </nav>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <div className="block relative max-w-180 mt-5 mx-auto [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif]" data-ditto-id="style-beitrag-teilen" />
          {" "}
          <div className="block relative max-w-180 mt-5 mx-auto [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif]" data-ditto-id="style-span-18">
            <div className="block relative max-w-280 py-16 max-md:py-9 md:max-lg:py-[2.4rem]" data-ditto-id="style-link-11">
              <h2 className="box-content block max-w-280 text-[0.9375rem] font-bold leading-[1.0625rem] tracking-[1.4px] uppercase text-pretty" data-ditto-id="style-link-12" data-component="heading">
                Weitere Beiträge
              </h2>
              {" "}
              <div className="box-content block max-w-280 mt-5" data-ditto-id="style-button">
                <ul className="block [list-style-type:none] list-outside" data-ditto-id="style-autoreninformation">
                  {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} />)}
                </ul>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </main>
        {" "}
        <footer className="box-content border-t border-solid border-t-clr-0 block mt-24 [font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif] max-md:mt-14 md:max-lg:mt-[3.8375rem]" data-ditto-id="style-p-32">
          <div className="block relative pt-16 pb-[2.4rem] px-5 max-md:pt-9 max-lg:pb-6 md:max-lg:pt-[2.4rem] 2xl:pb-10" data-ditto-id="style-figure-2">
            <div className="block max-w-280 mx-auto" data-ditto-id="style-blockquote-9">
              <div className="block leading-0" data-ditto-id="style-p-2">
                <a className="box-content h-[51.7px] inline-block text-primary underline cursor-pointer" data-ditto-id="style-cite" data-component="link" href="/" rel="home">
                  <img className="box-content w-30 h-13 inline max-w-full overflow-clip aspect-[auto_318/137]" data-ditto-id="style-p-33" data-component="image" alt="Afaik min" height="137" src="/assets/cloned/svg/d179f89faeae.svg" width="318" />
                </a>
              </div>
              {" "}
              <div className="flex mt-5 flex-wrap justify-between items-start gap-5" data-ditto-id="style-figure-11">
                <div className="flex gap-[2.4rem] max-lg:flex-wrap max-lg:gap-6 2xl:gap-10" data-ditto-id="style-image-7">
                  <div className="box-content block min-w-0 basis-full [word-break:break-word] [overflow-wrap:break-word] max-lg:grow" data-ditto-id="style-p-3">
                    <p className="block text-muted-foreground text-[0.9375rem] leading-[1.5625rem] text-pretty" data-ditto-id="style-heading-46">
                      As Far As I Know
                    </p>
                  </div>
                  {" "}
                  <div className="box-content h-[25.3px] block min-w-0 flex-1 [word-break:break-word] [overflow-wrap:break-word] max-lg:h-5 max-lg:basis-full" data-ditto-id="style-p-4">
                    <div className="box-content w-0 h-5 block clear-both" data-ditto-id="style-blockquote" aria-hidden="true" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="flex flex-wrap justify-between items-start gap-36 max-md:gap-20 md:max-lg:gap-[5.7625rem]" data-ditto-id="style-p-34">
                  <nav className="box-content flex relative flex-col flex-wrap items-start gap-5 text-[0.9375rem] font-medium leading-[1.5625rem]" data-ditto-id="style-cite-2" data-component="nav" aria-label="Footer Nav">
                    <ul className="flex relative flex-col flex-wrap items-start grow gap-5 [list-style-type:none] list-outside" data-ditto-id="style-link-24">
                      <li className="box-content flex relative items-center" data-ditto-id="style-p-5">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-figure-5" data-component="link" href="/newsletter">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-image-3">
                            Newsletter abonnieren
                          </span>
                        </a>
                      </li>
                      <li className="box-content flex relative items-center" data-ditto-id="style-p-7">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-figure-4" data-component="link" href="/podcast">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-image-36">
                            Podcast Synapsensprung
                          </span>
                        </a>
                      </li>
                    </ul>
                  </nav>
                  {" "}
                  <nav className="box-content flex relative flex-col flex-wrap items-start gap-5 text-[0.9375rem] font-medium leading-[1.5625rem]" data-ditto-id="style-p-35" data-component="nav" aria-label="Footer Nav 2">
                    <ul className="flex relative flex-col flex-wrap items-start grow gap-5 [list-style-type:none] list-outside" data-ditto-id="style-p-6">
                      <li className="box-content flex relative items-center" data-ditto-id="style-figure-14">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-image-4" data-component="link" href="/datenschutz">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-p-8">
                            Datenschutz
                          </span>
                        </a>
                      </li>
                      <li className="box-content flex relative items-center" data-ditto-id="style-footer-3">
                        <a className="box-content h-[1.5625rem] block z-1 cursor-pointer" data-ditto-id="style-div-10" data-component="link" href="/impressum">
                          <span className="box-content inline [overflow-wrap:break-word]" data-ditto-id="style-div-13">
                            Impressum
                          </span>
                        </a>
                      </li>
                    </ul>
                  </nav>
                </div>
                {" "}
              </div>
              {" "}
              <div className="box-content h-24 block clear-both mt-5 max-md:h-14 md:max-lg:h-[3.8375rem]" data-ditto-id="style-div-56" aria-hidden="true" />
              {" "}
              <div className="flex mt-5 flex-wrap justify-between items-center gap-2" data-ditto-id="style-link-17">
                <p className="box-content block text-[0.9375rem] leading-[1.5625rem] text-pretty" data-ditto-id="style-image-5">
                  © Kai Spriestersbach
                </p>
                {" "}
                <p className="box-content block text-[0.9375rem] leading-[1.5625rem] text-pretty" data-ditto-id="style-div-22">
                  {"Gehosted von "}
                  <a className="box-content inline text-primary underline cursor-pointer" data-ditto-id="style-div-33" data-component="link" href="https://www.cms-admins.de/" rel="noopener" target="_blank">
                    CMS ADMINS
                  </a>
                </p>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
      {" "}
    </>
  );
}
