import Icon18 from "../svgs/svg-icon18";
import MediaCard2, { type MediaCard2Data } from "../components/media-card2";
import { MediaCard2_styles } from "../_styles";
const MediaCard2_data: MediaCard2Data[] = [
    { id: "radix-_R_dihbsnpf6bamivb_", title: "What is AEO (Answer Engine Optimization)?", arialabelledby: "radix-_R_dihbsnpf6bamivb_", id2: "radix-_R_8dihbsnpf6bamivb_", text: "Answer Engine Optimization (AEO) is the practice of making content easy for AI-powered answer systems to find, understand, quote, cite, and recommend. In 2026 that includes Google AI Overviews and AI Mode, ChatGPT Search, Perplexity, Claude, Gemini, and voice assistants. The work combines classic SEO foundations with structured data, entity consistency, crawler access, direct-answer content, source citations, and measurement of AI mentions or citations." },
    { id: "radix-_R_lihbsnpf6bamivb_", title: "What is the difference between AEO and SEO?", arialabelledby: "radix-_R_lihbsnpf6bamivb_", id2: "radix-_R_8lihbsnpf6bamivb_", text: "SEO optimizes for visibility in search results; AEO optimizes for visibility inside generated answers. They overlap heavily: crawlability, page quality, technical SEO, structured data, internal links, and authority still matter. The difference is the output. SEO success is usually a ranking and a click. AEO success may be a citation, a recommendation, a quoted answer, or a brand mention before the user ever visits your site." },
    { id: "radix-_R_tihbsnpf6bamivb_", title: "How do AI assistants choose which websites to recommend?", arialabelledby: "radix-_R_tihbsnpf6bamivb_", id2: "radix-_R_8tihbsnpf6bamivb_", text: "AI assistants do not all use the same source stack. Google AI features are built on Google Search systems and surface links from the web index; ChatGPT Search can use OpenAI search crawlers and source links; Perplexity is citation-first; other assistants may combine model memory, search retrieval, user-provided context, and partner indexes. Durable recommendation signals include crawl access, source authority, clear entities, fresh pages, structured facts, direct answers, citations, and consistency across first-party and third-party sources." },
    { id: "radix-_R_15ihbsnpf6bamivb_", title: "What is llms.txt and why does it matter?", arialabelledby: "radix-_R_15ihbsnpf6bamivb_", id2: "radix-_R_95ihbsnpf6bamivb_", text: "llms.txt is an emerging convention for giving AI agents a concise, markdown-like map of a website: what the site is, which pages matter, and where canonical facts live. It matters because agents and retrieval systems benefit from a high-signal starting point. But it does not replace normal SEO infrastructure. Keep XML sitemaps, robots.txt, schema markup, canonical tags, and crawlable pages healthy; use llms.txt as an additional orientation layer." },
    { id: "radix-_R_1dihbsnpf6bamivb_", title: "What is GEO (Generative Engine Optimization)?", arialabelledby: "radix-_R_1dihbsnpf6bamivb_", id2: "radix-_R_9dihbsnpf6bamivb_", text: "Generative Engine Optimization (GEO) is the subset of AEO focused on improving visibility inside AI-generated responses. It started as an academic framing for testing which content changes make a source more likely to appear in generative answers. In practice, GEO means increasing evidence density, source quality, clarity, and retrievability so an AI system can cite the page when it answers a user question." },
    { id: "radix-_R_1lihbsnpf6bamivb_", title: "What are the Princeton 9 GEO methods?", arialabelledby: "radix-_R_1lihbsnpf6bamivb_", id2: "radix-_R_9lihbsnpf6bamivb_", text: "The original GEO research tested nine content changes: adding citations, adding relevant statistics, adding quotations, improving fluency, using appropriate technical terms, simplifying the explanation, using an authoritative tone, adding unique vocabulary, and keyword stuffing. The durable lesson is not to stuff keywords; it is to make claims easier to verify and quote. Start with citations, statistics, clear definitions, expert context, and concise answer blocks." },
    { id: "radix-_R_1tihbsnpf6bamivb_", title: "How do I measure AEO success?", arialabelledby: "radix-_R_1tihbsnpf6bamivb_", id2: "radix-_R_9tihbsnpf6bamivb_", text: "Measure AEO through a mix of first-party and panel data: Search Console generative-AI reports where available, server logs for AI crawler user agents, referral traffic from AI products, citation tracking tools, and repeated prompt panels across Google AI Mode, ChatGPT Search, Perplexity, Claude, and Gemini. Record the exact prompt, date, engine, answer, citations, and competitors cited. One manual test is anecdotal; a repeated panel over time becomes a useful visibility metric." },
    { id: "radix-_R_25ihbsnpf6bamivb_", title: "Do ChatGPT ads replace AEO?", arialabelledby: "radix-_R_25ihbsnpf6bamivb_", id2: "radix-_R_a5ihbsnpf6bamivb_", text: "No. Paid placements can create reach in AI interfaces, but they do not replace organic citations, source authority, or answer quality. Treat ChatGPT ads and other AI-search ad products as a separate paid channel: useful for demand capture and testing message-market fit, but not evidence that an assistant will cite or recommend your site organically. AEO still depends on crawlable pages, structured facts, current sources, and trustworthy content." },
    { id: "radix-_R_2dihbsnpf6bamivb_", title: "What does AEO implementation cost?", arialabelledby: "radix-_R_2dihbsnpf6bamivb_", id2: "radix-_R_adihbsnpf6bamivb_", text: "AEO implementation cost depends on scope. A small technical foundation — crawl audit, robots.txt review, llms.txt, core schema, brand facts, and a few FAQ sections — can be a low-four-figure project. A full operating system with answer hubs, multilingual pages, schema automation, citation monitoring, Search Console reporting, log analysis, and recurring content refresh is closer to a strategic SEO or content-engineering retainer. Be skeptical of guaranteed citation packages; AI visibility must be measured over time." },
    { id: "radix-_R_2lihbsnpf6bamivb_", title: "How long does AEO take to show results?", arialabelledby: "radix-_R_2lihbsnpf6bamivb_", id2: "radix-_R_alihbsnpf6bamivb_", text: "Basic access and markup fixes can be visible after the next crawl, but AI answer visibility usually needs repeated retrieval and source comparison cycles. Expect technical fixes in days, content and citation improvements in weeks, and durable brand/entity gains over months. Timelines vary by engine: Google AI features depend on Search crawling and eligibility, while ChatGPT Search and Perplexity may pick up fresh pages faster if crawler access and source quality are strong." },
    { id: "radix-_R_2tihbsnpf6bamivb_", title: "Can I do AEO without technical skills?", arialabelledby: "radix-_R_2tihbsnpf6bamivb_", id2: "radix-_R_atihbsnpf6bamivb_", text: "Basic AEO is accessible to non-developers: llms.txt is a plain text file, brand-facts.json can be written manually, and some CMS platforms auto-generate schema markup. However, advanced AEO (NLP entity optimization, automated pipelines, custom schema implementations) requires development expertise. Content-focused AEO — writing quotable TL;DRs, implementing Princeton 9 methods — is achievable by skilled content writers. For comprehensive implementation, working with an AEO-specialized agency accelerates results and avoids common pitfalls." },
    { id: "radix-_R_35ihbsnpf6bamivb_", title: "What is brand-facts.json?", arialabelledby: "radix-_R_35ihbsnpf6bamivb_", id2: "radix-_R_b5ihbsnpf6bamivb_", text: "brand-facts.json is a machine-readable file at /.well-known/brand-facts.json containing verified facts about your organization: name, founding date, location, services, key personnel, and other structured data. It prevents AI hallucination by providing an authoritative source for company information. Best practice is pairing this with a human-readable /brand-facts page in Wikipedia style. When ChatGPT or Perplexity describes your company, they can reference verified facts rather than inferring from scattered web mentions." },
    { id: "radix-_R_3dihbsnpf6bamivb_", title: "Why are FAQ sections critical for AEO?", arialabelledby: "radix-_R_3dihbsnpf6bamivb_", id2: "radix-_R_bdihbsnpf6bamivb_", text: "FAQ sections with FAQPage schema markup are among the highest-impact AEO tactics because they directly mirror how users query AI assistants. When someone asks ChatGPT \"What does AEO cost?\", the AI scans for question-answer pairs that match. FAQPage schema makes these pairs machine-readable and explicitly structured. Google AI Overviews also pull from FAQ schema. Well-optimized sites implement FAQ sections across all landing pages, guides, and the homepage — each one a potential citation source for AI assistants." },
    { id: "radix-_R_3lihbsnpf6bamivb_", title: "Should I block or allow AI crawlers?", arialabelledby: "radix-_R_3lihbsnpf6bamivb_", id2: "radix-_R_blihbsnpf6bamivb_", text: "Allow the AI crawlers that support your visibility goals and block the ones that conflict with your data policy. Do not use one blanket rule for everything. Google Search AI features rely on normal Search crawling controls; OpenAI separates GPTBot, OAI-SearchBot and ChatGPT-User; other vendors have their own user agents. Audit robots.txt, CDN bot protection, server logs, and paywall rules so public answer pages are reachable while proprietary or private content remains protected." },
    { id: "radix-_R_3tihbsnpf6bamivb_", title: "Are press releases relevant for AEO?", arialabelledby: "radix-_R_3tihbsnpf6bamivb_", id2: "radix-_R_btihbsnpf6bamivb_", text: "Press releases can support AEO only when they publish real, verifiable news and consistent entity facts. Their value is not the old SEO idea of low-quality link distribution; it is corroboration. If reputable publications repeat the same company name, service category, location, founder, funding, product launch, or benchmark, AI systems have more independent evidence to reconcile. Thin syndication without substance is unlikely to help and can reduce trust." },
    { id: "radix-_R_45ihbsnpf6bamivb_", title: "Does local business presence on maps affect AEO?", arialabelledby: "radix-_R_45ihbsnpf6bamivb_", id2: "radix-_R_c5ihbsnpf6bamivb_", text: "Yes — for local and regional queries, map and directory listings directly influence AI recommendations. (1) Google Business Profile: Google AI Overviews and Gemini pull verified business data directly from GBP. An optimized profile improves local AI recommendation accuracy. (2) Bing Places: Microsoft Copilot uses Bing data as its primary source — a Bing Places listing makes your business visible to Copilot for local queries. (3) Apple Maps Connect: Siri and Apple Intelligence use Apple Maps data for local recommendations. (4) OpenStreetMap: Used by DuckDuckGo, many privacy-focused AI tools, and open-source LLMs. Less impactful than the above, but relevant for coverage breadth. (5) Brave Search: Brave has its own independent web index (not derived from Google/Bing) powering Leo, its built-in AI assistant. Submitting your site via the Brave Search Web Discovery Project ensures Leo can recommend you. For local service businesses, maintaining consistent NAP data (Name, Address, Phone) across all five platforms is a foundational AEO step — AI assistants cross-reference these sources to verify business legitimacy." }
];
/** Frequently Asked Questions section. */
export default function FrequentlyAskedQuestionsSection({ mediaCard2Data = MediaCard2_data } = {}) {
  return (
    <div className="block" id="faq">
      <section className="block mb-12">
        <h2 className="flex mb-6 items-center gap-2 [font-family:'Space_Grotesk',_system-ui,_-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Arial,_sans-serif,_system-ui,_sans-serif] text-2xl font-bold leading-[1.625rem] tracking-[-0.6px]" data-component="heading">
          <Icon18 />
          Frequently Asked Questions
        </h2>
        <div className="border border-solid border-border block rounded-[14px] overflow-hidden bg-color-004">
          <div className="block w-full">
            {mediaCard2Data.map((d, i) => <MediaCard2 key={i} d={d} styles={MediaCard2_styles[i]} />)}
          </div>
        </div>
      </section>
    </div>
  );
}
